// Dicionário EN. Toda chave daqui existe em `ptBR.js`, e vice-versa: a
// paridade é cobrada por teste, e chave sem par é falha, não pendência.

export default {
  'idioma.escolher': 'Language',
  'idioma.pt-BR': 'Português',
  'idioma.en': 'English',
  'idioma.es': 'Español',


  // Navegação. A CHAVE é a ROTA — o mesmo identificador que o roteador usa.
  // Derivar a chave do rótulo em português quebraria na primeira renomeação;
  // derivá-la da rota amarra a tradução ao destino, que é o que não muda.
  'nav.inicio': 'Home',
  'nav.campeonatos': 'Championships',
  'nav.atletas': 'Athletes',
  'nav.ranking': 'Ranking',
  'nav.social': 'Social',
  'nav.messenger': 'Messenger',
  'nav.comunidades': 'Communities',
  'nav.meu-painel': 'My dashboard',
  'nav.minha-filiacao': 'My affiliation',
  'nav.meu-historico': 'My history',
  'nav.admin': 'Dashboard',
  'nav.admin/eventos': 'Events',
  'nav.admin/inscricoes': 'Registrations',
  'nav.admin/solicitacoes': 'Requests',
  'nav.admin/checkin': 'Check-in',
  'nav.admin/pesagem': 'Weigh-in',
  'nav.admin/credenciamento': 'Credentialing',
  'nav.admin/palco': 'Stage',
  'nav.admin/resultados': 'Results',
  'nav.admin/ranking': 'Ranking',
  'nav.admin/overall': 'Overall',
  'nav.admin/lancamentos': 'Point entries',
  'nav.admin/musclewar': 'MuscleWare',
  'nav.admin/auditoria': 'Audit log',
  'nav.admin/configuracoes': 'Settings',
  'grupo.plataforma': 'Platform',
  'grupo.administracao': 'Administration',
  'navegacao.principal': 'Main navigation',
  'navegacao.abrirMenu': 'Open menu',
  'navegacao.fecharMenu': 'Close menu',
  'navegacao.inicio': 'Home',
  'navegacao.campeonatos': 'Championships',
  'navegacao.ranking': 'Ranking',
  'navegacao.atletas': 'Athletes',
  'navegacao.inscricoes': 'Registrations',
  'navegacao.resultados': 'Results',
  'navegacao.importacoes': 'Imports',
  'navegacao.solicitacoes': 'Requests',
  'navegacao.minhaCarreira': 'My career',
  'navegacao.configuracoes': 'Settings',

  'topo.busca': 'Search',
  'topo.somLigado': 'Sound on',
  'topo.somDesligado': 'Sound off',
  'topo.ligarSom': 'Turn system sound on',
  'topo.desligarSom': 'Turn system sound off',
  'topo.notificacoes': 'Notifications',
  'topo.naoLidas': '{n} unread',
  'topo.meuPerfil': 'My social profile',
  'topo.sair': 'Sign out',

  'acao.aplicar': 'Apply',
  'acao.revisar': 'Review',
  'acao.excluir': 'Delete',
  'acao.invalidar': 'Void',
  'acao.cancelar': 'Cancel',
  'acao.confirmar': 'Confirm',
  'acao.salvar': 'Save',
  'acao.voltar': 'Back',
  'acao.fechar': 'Close',
  'acao.filtrar': 'Filter',
  'acao.limparFiltros': 'Clear filters',

  'estado.carregando': 'Loading…',
  'estado.vazio': 'Nothing here yet',
  'estado.erro': 'Could not load',
  'estado.semPermissao': 'You do not have permission to see this',

  'pagina.anterior': 'Previous page',
  'pagina.proxima': 'Next page',
  'pagina.de': 'Page {atual} of {total}',

  'ranking.geral': 'Overall Ranking',
  'ranking.superOverall': 'Super Overall',
  'ranking.equipes': 'Team ranking',
  'ranking.empresas': 'Company ranking',
  'ranking.pontos': 'Points',
  'ranking.posicao': 'Position',
  'ranking.etapas': 'Stages',
  'ranking.empateNaoResolvido': 'Unresolved tie',
  'ranking.semCadastro': 'Not registered with MCI',

  'importacao.resumo':
    '{n} results will be added to the history/ranking. '
    + 'Athletes who are not yet registered will remain pending linkage. '
    + 'No athlete will be created automatically.',
  'importacao.totalRegistros': 'Records read',
  'importacao.reconhecidos': 'Recognized',
  'importacao.pendentes': 'Pending linkage',
  'importacao.conflitos': 'Conflicts',
  'importacao.duplicados': 'Duplicates',
  'importacao.rejeitados': 'Rejected',
  'importacao.aplicaveis': 'Applicable',

  'vinculo.automatico': 'Automatically linked',
  'vinculo.porCpf': 'Automatically linked by CPF',
  'vinculo.porMatricula': 'Automatically linked by affiliation + member number',
  'vinculo.pendente': 'Pending linkage',
  'vinculo.conflito': 'Identity conflict',
  'vinculo.naoIdentificado': 'Not identified',

  // Tela de recuperação do limite de erro. Ela aparece JUSTAMENTE quando algo
  // quebrou — e em espanhol ou inglês continua tendo de dizer o que fazer.
  'erro.titulo': 'This screen stopped responding',
  'erro.explicacao': 'The rest of the system keeps working. Go back to the home screen and try again; if it happens again, tell technical support which screen it was.',
  'erro.voltarAoInicio': 'Back to home',
  'erro.recarregar': 'Reload',

  // Abertura e entrada. O NOME do campeonato não entra aqui: é dado oficial, e
  // sai como está nos três idiomas.
  'abertura.rotulo': 'MCI Platform opening',
  'abertura.entrarAgora': 'Enter now',
  'login.entrar': 'Sign in',
  'login.semConta': 'No account yet?',
  'login.criarConta': 'Create account',

  // Busca global do topo.
  'busca.placeholder': 'Search athlete, event, profile, community…',
  'busca.rotulo': 'Global search',
  'busca.nadaEncontrado': 'Nothing found.',
  'busca.atleta': 'Athlete',
  'busca.campeonato': 'Championship',
  'busca.perfil': 'Profile',
  'busca.comunidade': 'Community',
  'abertura.ativarSom': 'Turn sound on',
  'abertura.silenciar': 'Mute',
  'login.email': 'Email',
  'login.senha': 'Password',
  'estado.aguarde': 'Please wait…',
  'busca.perfilDe': 'Profile',
  // Blocos compartilhados de interface: esqueleto, erro, vazio, modal, toast,
  // paginação e credencial. Traduzidos num lugar só porque aparecem em todas as
  // telas — texto repetido em quinze páginas é quinze chances de divergir.
  'ui.carregando': 'Loading',
  'ui.tentarDeNovo': 'Try again',
  'ui.vazioDescricao': 'Records will show up on this screen once they exist.',
  'ui.midiaIndisponivel': 'Media unavailable.',
  'ui.imagemAmpliada': 'Enlarged image',
  'ui.fecharImagem': 'Close image',
  'ui.dispensar': 'Dismiss',
  'ui.carregarMais': 'Load more',
  'ui.qrFalhou': 'The QR code could not be drawn. The code next to it is still readable.',
  'ui.qrDaCredencial': 'Credential QR code {valor}',
  'ui.atualizadoAgora': 'Updated just now',
  'ui.atualizadoMinutos': 'Updated {n} min ago',
  'ui.atualizadoHoras': 'Updated {n} h ago',
  // Minha filiação e meu histórico — a área do atleta sobre a própria carreira.
  // O NOME da entidade, da categoria e da classe vem do banco e não é traduzido:
  // o que traduz é o rótulo em volta.
  'carreira.meuEspaco': 'My space',
  'carreira.minhaFiliacao': 'My affiliation',
  'carreira.minhaFiliacaoDescricao': 'The body you compete for and your registration number with it.',
  'carreira.semPerfil': 'You do not have an athlete profile yet',
  'carreira.semPerfilDescricao': 'Competing requires an affiliation confirmed by the federation. Send your request with your CPF, affiliation body and registration number — an operator will review it.',
  'carreira.semFiliacao': 'No affiliation on record',
  'carreira.semFiliacaoDescricao': 'Your profile exists in {organizacao}, but no affiliation body is linked to it. The federation is the one that records the link and the number.',
  'carreira.suaOrganizacao': 'your organization',
  'carreira.ativa': 'Active',
  'carreira.inativa': 'Inactive',
  'carreira.codigoDaEntidade': 'Body code',
  'carreira.minhaMatricula': 'My membership number',
  'carreira.uf': 'State',
  'carreira.organizacaoNota': 'The body and the number are recorded by the federation — if anything is wrong, talk to an operator.',
  'carreira.organizacao': 'Organization',
  'carreira.meuHistorico': 'My history',
  'carreira.meuHistoricoDescricao': 'Every scoring appearance, with the arithmetic in the open: placement, Overall bonus and total.',
  'carreira.semPontos': 'You have not scored yet',
  'carreira.semPontosDescricao': 'As soon as a result is published and the stage is linked to a season, your appearance shows up here.',
  'carreira.porCategoria': 'Performance by category',
  'carreira.porCategoriaNota': 'Each category has its own ranking',
  'carreira.semCategoria': 'No category',
  'carreira.participacoesContagem': '{n} appearances',
  'carreira.participacaoContagem': '{n} appearance',
  'carreira.participacoes': 'Appearances',
  'carreira.pontosDeColocacao': 'Placement points',
  'carreira.bonusOverall': 'Overall bonus',
  'carreira.totalGeral': 'Overall total',
  'carreira.totalGeralNota': 'Sum of every category',
  'carreira.colunaCampeonato': 'Championship',
  'carreira.colunaCategoriaClasse': 'Category · class',
  'carreira.colunaColocacaoCurta': 'Pl.',
  'carreira.colunaColocacao': 'Placement',
  'carreira.colunaOverall': 'Overall',
  'carreira.colunaTotal': 'Total',
  'carreira.colunaFiliacaoNaEpoca': 'Affiliation at the time',
  'carreira.colunaPtsColocacao': 'Placement pts',
  'carreira.colunaCategoria': 'Category',
  'carreira.colunaFiliacao': 'Affiliation',
  'carreira.campeaoOverall': 'Overall champion',
  'carreira.numeroAbreviado': 'no. {numero}',
  'carreira.filiacaoNaoRegistrada': 'not recorded',
  'carreira.rodapeContagem': 'Showing {mostrando} of {total} appearance(s).',
  'carreira.rodapeOverall': 'The Overall bonus belongs to the overall class and counts once per title.',
  // Mensagens de validação dos formulários. A VALIDAÇÃO devolve a CHAVE, e não
  // a frase: `lib/formulario.js` não é componente, não tem contexto de idioma, e
  // devolver português de dentro dela deixaria o erro em português numa tela em
  // espanhol. Quem traduz é quem desenha o erro na tela.
  'form.erro.nome': 'Enter your full name',
  'form.erro.nomeDocumento': 'Enter the name exactly as it appears on your ID',
  'form.erro.nascimento': 'Enter a valid date of birth',
  'form.erro.email': 'Enter a valid email address',
  'form.erro.senha': 'The password needs at least 8 characters',
  'form.erro.telefone': 'Phone with area code and 8 or 9 digits',
  'form.erro.whatsapp': 'WhatsApp with area code and 8 or 9 digits',
  'form.erro.cep': 'Postal code with 8 digits',
  'form.erro.endereco': 'Enter the street address',
  'form.erro.numero': 'Enter the number',
  'form.erro.uf': 'Select the state',
  'form.erro.cidade': 'Enter the city',
  'form.erro.cpf': 'Invalid CPF',
  'form.erro.sexo': 'Select the competition category',
  'form.erro.filiacao': 'Select the affiliation body',
  'form.erro.matricula': 'Enter the registration number',
  // Perfis abertos no cadastro. O CÓDIGO ('ATHLETE', 'COACH'…) é o que vai para
  // a API e nunca muda; aqui traduz-se só o que a pessoa lê.
  'papel.ATHLETE': 'Athlete',
  'papel.ATHLETE.descricao': 'Competes in the Brazilian Championship stages',
  'papel.COACH': 'Coach',
  'papel.COACH.descricao': 'Prepares and supports athletes',
  'papel.GYM': 'Gym',
  'papel.GYM.descricao': 'Training center',
  'papel.TEAM': 'Team',
  'papel.TEAM.descricao': 'A team that brings athletes together',
  'papel.BRAND': 'Brand',
  'papel.BRAND.descricao': 'Brand in the ecosystem',
  'papel.SPONSOR': 'Sponsor',
  'papel.SPONSOR.descricao': 'Supports athletes and stages',
  'papel.MEDIA': 'Media',
  'papel.MEDIA.descricao': 'Coverage and content',
  // Cadastro em cinco etapas.
  'cadastro.etapa1': 'IDENTITY',
  'cadastro.etapa1.titulo': 'Who you are',
  'cadastro.etapa2': 'CONTACT',
  'cadastro.etapa2.titulo': 'How we reach you',
  'cadastro.etapa3': 'ADDRESS',
  'cadastro.etapa3.titulo': 'Where you are',
  'cadastro.etapa4': 'SPORTS PROFILE',
  'cadastro.etapa4.titulo': 'What comes next',
  'cadastro.etapa5': 'REVIEW',
  'cadastro.etapa5.titulo': 'Check before sending',
  'cadastro.etapaDe': 'Step {atual} of {total}',
  'cadastro.emailJaCadastrado': 'This email is already registered',
  'cadastro.nomeCompleto': 'Full name',
  'cadastro.dataDeNascimento': 'Date of birth',
  'cadastro.voceE': 'You are',
  'cadastro.voceEHint': 'Defines how you appear on the platform. It is not an access level.',
  'cadastro.email': 'Email',
  'cadastro.senha': 'Password',
  'cadastro.senhaHint': 'At least 8 characters.',
  'cadastro.telefone': 'Phone',
  'cadastro.whatsapp': 'WhatsApp',
  'cadastro.mesmoNumero': 'Use the same number as the phone',
  'cadastro.cep': 'Postal code',
  'cadastro.cepHint': 'We fill in the address for you.',
  'cadastro.buscandoEndereco': 'Looking up the address…',
  'cadastro.endereco': 'Address',
  'cadastro.numero': 'Number',
  'cadastro.complemento': 'Address line 2',
  'cadastro.cidade': 'City',
  'cadastro.uf': 'State',
  'cadastro.filiacaoTitulo': 'Your affiliation is confirmed by the federation',
  'cadastro.filiacaoTexto': 'Competing requires a link the MCI does not grant on its own: the federation you are affiliated with is the one that confirms it. That is why your athlete profile goes through a review — and it only starts once your account exists.',
  'cadastro.filiacaoProximoPasso': 'As soon as you finish signing up, we will open the <b>My request</b> page, where you provide your <b>CPF</b>, the <b>affiliation body</b> and your <b>registration number</b>. An operator from the federation reviews and approves it.',
  'cadastro.cpfDepois': 'The CPF is deliberately not requested here: it is only typed once your session exists, and it goes straight to the federation — it is never stored in this browser.',
  'cadastro.semMaisNada': 'We do not need anything else',
  'cadastro.semMaisNadaTexto': 'The <b>{papel}</b> profile does not compete in the stages, so we do not ask for a CPF or an affiliation — it would mean collecting an ID from someone who is not going on stage.',
  'cadastro.funcoesDeOperacao': 'Operating roles — event direction, credentialing, weigh-in, stage, results — are not chosen here. They are granted by the championship organization to an account that already exists.',
  'cadastro.confiraOsDados': 'Check the details. You can go back and fix any step.',
  'cadastro.jaTenhoConta': 'I already have an account',
  'cadastro.continuar': 'Continue',
  'cadastro.enviando': 'Sending…',
  'cadastro.revisaoIdentidade': 'Identity',
  'cadastro.revisaoContato': 'Contact',
  'cadastro.revisaoEndereco': 'Address',
  'cadastro.revisaoNome': 'Name',
  'cadastro.revisaoNascimento': 'Date of birth',
  'cadastro.revisaoPerfil': 'Profile',
  'cadastro.editar': 'Edit',
  // Conferência local da foto. `lib/foto.js` devolve CHAVE e valores, pelo mesmo
  // motivo de `lib/formulario.js`: não é componente e não sabe o idioma.
  'foto.erro.semArquivo': 'Choose an image.',
  'foto.erro.tipo': 'The photo must be JPG, PNG or WebP.',
  'foto.erro.tamanho': 'The photo is {tamanho} MB and the limit is {limite} MB.',
  'foto.erro.vazio': 'The file is empty.',
  // Solicitação de perfil de atleta.
  'solicitacao.perfilDeAtleta': 'Athlete profile',
  'solicitacao.minhaSolicitacao': 'My request',
  'solicitacao.descricao': 'Competing requires an affiliation confirmed by the federation. You send the details; an operator reviews them.',
  'solicitacao.emAnalise': 'Under review',
  'solicitacao.aprovada': 'Approved',
  'solicitacao.recusada': 'Rejected',
  'solicitacao.cancelada': 'Cancelled',
  'solicitacao.canceladaAviso': 'Request cancelled.',
  'solicitacao.perfilAtivo': 'Athlete profile active',
  'solicitacao.jaCompete': 'You already compete with the MCI',
  'solicitacao.jaCompeteTexto': 'Your athlete profile is active. To correct the affiliation, registration number or any detail on your record, talk to your federation — those fields are maintained by it, not by this screen.',
  'solicitacao.foiAprovada': 'Your request was approved',
  'solicitacao.foiAprovadaTexto': 'The federation approved your profile. If it still does not show up here, refresh the session.',
  'solicitacao.atualizarSessao': 'Refresh my session',
  'solicitacao.cancelarSolicitacao': 'Cancel request',
  'solicitacao.cancelarAviso': 'The request leaves the federation queue and the CPF you sent is erased. You can send another one later.',
  'solicitacao.naFila': 'Your request is in the federation queue',
  'solicitacao.enviadaEm': 'Sent on {data}. An operator from',
  'solicitacao.suaFederacao': 'your federation',
  'solicitacao.vaiAnalisar': 'will review it. In the meantime, you can use the platform normally.',
  'solicitacao.nome': 'Name',
  'solicitacao.entidade': 'Affiliation body',
  'solicitacao.numeroDeRegistro': 'Registration number',
  'solicitacao.cpfGuardado': 'Held with the federation until the review',
  'solicitacao.fotoEnviada': 'Photo sent',
  'solicitacao.fotoEnviadaAlt': 'Photo sent with the request',
  'solicitacao.semFoto': 'No photo',
  'solicitacao.removerFoto': 'Remove photo',
  'solicitacao.fotoEnviadaAviso': 'Photo sent.',
  'solicitacao.fotoRemovidaAviso': 'Photo removed.',
  'solicitacao.historico': 'History',
  'solicitacao.historicoTexto': 'The queue keeps what has already happened — including what was rejected.',
  'solicitacao.motivo': 'Reason',
  'solicitacao.fotoDePerfil': 'Profile photo',
  'solicitacao.fotoOpcional': 'Optional. The federation uses the photo to confirm your identity.',
  'solicitacao.previaDaFoto': 'Preview of the chosen photo: {nome}',
  'solicitacao.trocarFoto': 'Change photo',
  'solicitacao.escolherFoto': 'Choose photo',
  'solicitacao.remover': 'Remove',
  'solicitacao.formatosDaFoto': 'JPG, PNG or WebP, up to 5 MB.',
  'solicitacao.solicitarPerfil': 'Request an athlete profile',
  'solicitacao.solicitarTexto': 'These details go straight to the federation you choose. Nothing is kept in this browser.',
  'solicitacao.ultimaRecusada': 'Your last request was rejected.',
  'solicitacao.nomeHint': 'As it appears on your ID.',
  'solicitacao.cpfHint': 'Used to link your results. It never shows up in public search.',
  'solicitacao.cpfSeraEnviado': 'It will be sent as {resumo}',
  'solicitacao.categoriaDeCompeticao': 'Competition category',
  'solicitacao.categoriaHint': 'Defines which categories you can be entered in.',
  'solicitacao.feminino': 'Female',
  'solicitacao.masculino': 'Male',
  'solicitacao.nascimentoHint': 'Optional. Used to check your age group.',
  'solicitacao.entidadeHint': 'The federation that confirms your link.',
  'solicitacao.semEntidades': 'No active affiliation body is available for your account. Talk to the championship organization.',
  'solicitacao.erroEntidades': 'We could not load the affiliation bodies.',
  'solicitacao.matriculaHint': 'The number the federation gave you.',
  'solicitacao.avisoDeEnvio': 'Your details will be sent to the federation for validation.',
  'solicitacao.enviarParaAnalise': 'Send for review',
  'solicitacao.enviada': 'Request sent. The federation will review it.',
  'solicitacao.enviadaSemFoto': 'Request sent, but the photo did not upload: {erro} You can send it again below.',
  // Painel do atleta e conta do usuário.
  'painel.meuPainel': 'My dashboard',
  'painel.descricao': 'Registrations, schedule, batches, results, ranking and social life.',
  'painel.semPerfilDescricao': 'Competing requires an affiliation confirmed by the federation. Send your request with your CPF, affiliation body and registration number — an operator will review it. In the meantime, the social area is fully available.',
  'painel.irParaOFeed': 'Go to the feed',
  'painel.semFiliacao': 'No affiliation',
  'painel.semEquipe': 'No team',
  'painel.semAcademia': 'No gym',
  'painel.titulos': 'Titles',
  'painel.inscricoes': 'Registrations',
  'painel.publicacoes': 'Posts',
  'painel.seguidores': '{n} followers',
  'painel.mensagens': 'Messages',
  'painel.naCaixaDeEntrada': 'in the inbox',
  'painel.minhaAgenda': 'My schedule',
  'painel.semEventosFuturos': 'No upcoming events',
  'painel.semEventosFuturosDescricao': 'Your next stages show up here.',
  'painel.minhasBaterias': 'My batches',
  'painel.horarioADefinir': 'time to be defined',
  'painel.meusResultados': 'My results',
  'painel.semResultados': 'No published results',
  'painel.meuRanking': 'My ranking',
  'painel.rankingGeral': 'Overall',
  'painel.minhasInscricoes': 'My registrations',
  'painel.pesagem': 'weigh-in {peso}',
  'painel.checkInFeito': 'Checked in',
  'painel.nenhumaInscricao': 'No registrations',
  'conta.conta': 'Account',
  'conta.minhaConta': 'My account',
  'conta.descricao': 'Sign-in details, roles and organization links.',
  'conta.dados': 'Details',
  'conta.editar': 'Edit',
  'conta.nome': 'Name',
  'conta.email': 'Email',
  'conta.papelGlobal': 'Global role',
  'conta.situacao': 'Status',
  'conta.trocarSenha': 'Change password',
  'conta.organizacoes': 'Organizations',
  'conta.semVinculo': 'No link',
  'conta.semVinculoDescricao': 'Operating roles are granted per organization.',
  'conta.dadosAtualizados': 'Details updated.',
  'conta.editarConta': 'Edit account',
  'conta.senhaAlterada': 'Password changed.',
  'conta.senhaAtual': 'Current password',
  'conta.novaSenha': 'New password',
  'conta.confirmarNovaSenha': 'Confirm new password',
  'conta.senhasNaoCoincidem': 'The passwords do not match',
  // Fila de solicitações de perfil de atleta, do lado da federação.
  'fila.federacao': 'Federation',
  'fila.titulo': 'Athlete requests',
  'fila.descricao': 'Athlete profile requests waiting for the affiliation to be confirmed.',
  'fila.filtrarPorSituacao': 'Filter by status',
  'fila.aprovadas': 'Approved',
  'fila.recusadas': 'Rejected',
  'fila.canceladas': 'Cancelled',
  'fila.todas': 'All',
  'fila.solicitante': 'Requester',
  'fila.registro': 'Registration',
  'fila.enviadaEm': 'Sent on',
  'fila.enviada': 'Sent',
  'fila.acoes': 'Actions',
  'fila.ver': 'View',
  'fila.verSolicitacao': 'View request',
  'fila.aprovadaAviso': 'Request approved. The athlete was created.',
  'fila.aprovadaTitulo': 'Request approved',
  'fila.aprovadaDescricao': 'The athlete profile was created.',
  'fila.recusadaAviso': 'Request rejected.',
  'fila.recusadaTitulo': 'Request rejected',
  'fila.recusadaDescricao': 'The reason was recorded and sent.',
  'fila.analisar': 'Review request',
  'fila.analisarDescricao': 'Confirm the affiliation before approving.',
  'fila.fotoDe': 'Photo sent by {nome}',
  'fila.semFotoNota': 'This request came without a photo. The photo is optional — check the identity against the other details.',
  'fila.nomeInformado': 'Name given',
  'fila.contaDoSolicitante': 'Account',
  'fila.cpfApagado': 'No longer stored in this request',
  'fila.nascimento': 'Date of birth',
  'fila.cidade': 'City',
  'fila.analisadaEm': 'Reviewed on',
  'fila.motivoDaRecusa': 'Reason for rejection',
  'fila.motivoHint': 'The requester sees this text. Say what they need to correct.',
  'fila.oQueAprovarFaz': 'Approving creates the athlete profile for <b>{nome}</b> in <b>{entidade}</b> and links the CPF to the record. The action is recorded in the audit log under your name.',
  'fila.pedidoProprio': 'This request is yours.',
  'fila.pedidoProprioNota': 'Whoever asks does not review. Ask another operator at the federation.',
  'fila.jaDecidida': 'This request has already been {situacao}.',
  'fila.recusando': 'Rejecting…',
  'fila.confirmarRecusa': 'Confirm rejection',
  'fila.recusar': 'Reject',
  'fila.aprovando': 'Approving…',
  'fila.aprovarECriar': 'Approve and create athlete',
  // MCI Messenger.
  'messenger.mensagens': 'Messages',
  'messenger.novaConversa': 'New conversation',
  'messenger.semMensagens': 'no messages',
  'messenger.nenhumaConversa': 'No conversations',
  'messenger.nenhumaConversaDescricao': 'Start a conversation with an athlete, coach or brand.',
  'messenger.selecioneUma': 'Select a conversation to get started.',
  'messenger.conversa': 'Conversation',
  'messenger.conversaIndividual': 'Direct conversation',
  'messenger.participantes': '{n} participants',
  'messenger.midiaDaMensagem': 'Message media',
  'messenger.mensagemApagada': 'Message deleted',
  'messenger.abrirMidia': 'Open media enlarged',
  'messenger.reagirCom': 'React with {emoji}',
  'messenger.apagarMensagem': 'Delete message',
  'messenger.falhaAoEnviar': 'Could not send',
  'messenger.enviarMidia': 'Send media',
  'messenger.escrevaUmaMensagem': 'Write a message…',
  'messenger.mensagem': 'Message',
  'messenger.enviandoMensagem': 'Sending message',
  'messenger.enviarMensagem': 'Send message',
  'messenger.grupo': 'Group',
  'messenger.novaConversaDescricao': 'Search by handle or display name.',
  'messenger.buscarPerfil': 'Search profile…',
  'messenger.buscarPerfilRotulo': 'Search profile',
  'messenger.buscar': 'Search',
  'messenger.selecionado': 'Selected',
  'messenger.busqueParaComecar': 'Search for a profile to get started.',
  'messenger.nomeDoGrupo': 'Group name',
  'messenger.exemploDeGrupo': 'E.g. Wellness Team',
  'messenger.abrirConversa': 'Open conversation',
  // Homologação do Overall. O texto insiste em dizer, nos três idiomas, que a
  // plataforma NÃO calcula nem escolhe o campeão: é registro de decisão alheia.
  'overall.ranking': 'Ranking',
  'overall.titulo': 'Overall ratification',
  'overall.descricao': 'A record of the organization\'s official decision. The platform neither calculates nor picks the Overall champion.',
  'overall.escolhaCampeonato': 'Choose a championship',
  'overall.escolhaCampeonatoDescricao': 'Ratification is per championship and per overall class.',
  'overall.semTemporada': 'No season',
  'overall.semClasseAbsoluta': 'No overall class in this championship',
  'overall.semClasseAbsolutaDescricao': 'The Overall title belongs to the overall class. Without a class marked as overall, there is nothing to ratify.',
  'overall.homologado': 'Ratified',
  'overall.semHomologacao': 'Not ratified',
  'overall.declaradoOficialmente': 'Overall officially declared',
  'overall.atletaHomologado': 'Ratified athlete',
  'overall.homologadoEm': 'ratified on {data}',
  'overall.revogar': 'Revoke',
  'overall.semResultadoPublicado': 'No published result',
  'overall.semResultadoDescricao': 'The candidates appear when the result for this class is published.',
  'overall.colocacaoCurta': 'Pl.',
  'overall.atleta': 'Athlete',
  'overall.matricula': 'Membership number',
  'overall.filiacao': 'Affiliation',
  'overall.colocacao': 'Placement',
  'overall.declararOverall': 'Declare Overall',
  'overall.homologadoAviso': 'Overall ratified.',
  'overall.falhaAoHomologar': 'Could not ratify.',
  'overall.confiraOImpacto': 'Check the impact before confirming.',
  'overall.campeonato': 'Championship',
  'overall.categoria': 'Category',
  'overall.pontosDaColocacao': 'Placement points',
  'overall.bonusOverall': 'Overall bonus',
  'overall.totalDaParticipacao': 'Appearance total',
  'overall.impactoNoAcumulado': 'Impact on the season total',
  'overall.declaracaoOficial': 'This action records an official Overall declaration.',
  'overall.naoCalculamos': 'The platform does not calculate and does not decide the champion.',
  'overall.homologando': 'Ratifying…',
  'overall.confirmarHomologacao': 'Confirm ratification',
  'overall.revogadaAviso': 'Ratification revoked.',
  'overall.falhaAoRevogar': 'Could not revoke.',
  'overall.revogarHomologacao': 'Revoke ratification',
  'overall.revogarDescricao': 'Revoking removes the +10 bonus. The placement is not changed.',
  'overall.corrigeDecisao': 'This corrects an official decision that is already on record.',
  'overall.motivoNaAuditoria': 'The reason stays in the audit log, along with who revoked it and when.',
  'overall.motivoDaRevogacao': 'Reason for revoking',
  'overall.exemploDeMotivo': 'E.g. official minutes corrected by the organization',
  'overall.revogando': 'Revoking…',
  // Lançamentos do campeonato: corrigir, invalidar, restaurar.
  'lancamento.titulo': 'Championship point entries',
  'lancamento.descricao': 'Correcting and voiding a result that is already published. Every change requires a reason and stays in the audit log.',
  'lancamento.escolhaCampeonato': 'Corrections are made with the championship score sheet in hand, entry by entry.',
  'lancamento.contagem': '{n} entries',
  'lancamento.invalidados': '{n} voided',
  'lancamento.nenhum': 'No entries in this championship',
  'lancamento.nenhumDescricao': 'Entries appear once an import is applied or a result is published.',
  'lancamento.classe': 'Class',
  'lancamento.pontos': 'Points',
  'lancamento.matricula': 'Membership number {numero}',
  'lancamento.invalidado': 'Voided',
  'lancamento.valido': 'Valid',
  'lancamento.restaurar': 'Restore',
  'lancamento.corrigir': 'Correct',
  'lancamento.corrigidoAviso': 'Entry corrected.',
  'lancamento.falhaAoCorrigir': 'Could not correct it.',
  'lancamento.corrigirLancamento': 'Correct entry',
  'lancamento.naoCompareceu': 'Did not show (NS)',
  'lancamento.naoSubiuAoPalco': 'The athlete did not go on stage in this class',
  'lancamento.colocacaoHint': 'Points are calculated by the server. From 6th place on it is worth zero.',
  'lancamento.motivoDaCorrecao': 'Reason for the correction',
  'lancamento.exemploCorrecao': 'E.g. official score sheet corrected by the organization',
  'lancamento.corrigindo': 'Correcting…',
  'lancamento.confirmarCorrecao': 'Confirm correction',
  'lancamento.colocacaoAntes': 'Placement before',
  'lancamento.colocacaoDepois': 'Placement after',
  'lancamento.pontosAntes': 'Points before',
  'lancamento.pontosDepois': 'Points after',
  'lancamento.diferenca': 'Difference',
  'lancamento.invalidadoAviso': 'Entry voided.',
  'lancamento.falhaAoInvalidar': 'Could not void it.',
  'lancamento.invalidarLancamento': 'Void entry',
  'lancamento.naoEApagada': 'The appearance is NOT deleted.',
  'lancamento.naoEApagadaTexto': 'It stays in the athlete\'s history worth zero, marked as voided and with this reason in plain sight. It loses the {pontos} point(s) and the Overall bonus, if any.',
  'lancamento.motivoDaInvalidacao': 'Reason for voiding',
  'lancamento.exemploInvalidacao': 'E.g. athlete disqualified by the technical committee',
  'lancamento.invalidando': 'Voiding…',
  'lancamento.restauradoAviso': 'Entry restored.',
  'lancamento.falhaAoRestaurar': 'Could not restore it.',
  'lancamento.restaurarLancamento': 'Restore entry',
  'lancamento.voltaAoEstado': 'It goes back to the state before the voiding.',
  'lancamento.voltaAoEstadoTexto': 'Placement {colocacao} scores again by the season\'s current table, not by a total frozen at the moment of voiding.',
  'lancamento.invalidadoPor': 'Voided because: {motivo}',
  'lancamento.motivoDaRestauracao': 'Reason for restoring',
  'lancamento.exemploRestauracao': 'E.g. disqualification reversed by the committee',
  'lancamento.restaurando': 'Restoring…',
  // Resultados. O MCI NÃO julga: a tela transcreve a colocação oficial recebida.
  'resultado.competicao': 'Competition',
  'resultado.titulo': 'Results',
  'resultado.descricao': 'Entering the official result received, protected publishing and versioned corrections.',
  'resultado.selecioneEvento': 'Select an event',
  'resultado.porClasse': 'Official result by class',
  'resultado.publicado': 'Published',
  'resultado.rascunho': 'Draft',
  'resultado.resumoDaLinha': '{situacao} · version {versao} · checksum {checksum}…',
  'resultado.aindaNaoRecebido': 'Result not received yet',
  'resultado.empateNaoResolvido': 'Unresolved tie',
  'resultado.relancar': 'Re-enter',
  'resultado.lancarResultado': 'Enter result',
  'resultado.publicar': 'Publish',
  'resultado.corrigir': 'Correct',
  'resultado.versoes': 'Versions',
  'resultado.semClasses': 'No classes registered',
  'resultado.tituloOverall': 'Overall title',
  'resultado.tituloOverallNota': 'Declared by the organization. The platform records it — it does not decide.',
  'resultado.overallDoEvento': 'Overall for the event',
  'resultado.declaradoEm': 'declared on {data}',
  'resultado.nenhumTitulo': 'No Overall title declared',
  'resultado.nenhumTituloDescricao': 'The Overall is decided by the committee and recorded here.',
  'resultado.versaoApurada': 'Version {versao} · computed on {data}',
  'resultado.empateCurto': 'TIE',
  'resultado.somaBruta': 'total {soma} · raw {bruta} · {votos} vote(s)',
  'resultado.lancadoComEmpate': 'Result entered with an unresolved tie: publishing stays locked until it is corrected.',
  'resultado.lancadoAviso': 'Official result entered.',
  'resultado.publicacaoTravada': 'Publishing stays locked until the committee decides.',
  'resultado.lancadoTitulo': 'Result entered',
  'resultado.lancarEm': 'Enter result — {classe}',
  'resultado.julgamentoExterno': 'Judging is external. Transcribe the official placement received; the platform neither recalculates nor breaks ties.',
  'resultado.colocado': 'Placed',
  'resultado.desclassificado': 'Disqualified',
  'resultado.ausente': 'Absent',
  'resultado.nenhumInscrito': 'Nobody registered in this class',
  'resultado.lancarOficial': 'Enter official result',
  'resultado.publicadoComPontos': 'Result published. {complemento}',
  'resultado.atletasPontuaram': '{n} athlete(s) scored in the ranking.',
  'resultado.semPontuacao': 'No ranking points (event without a season).',
  'resultado.publicadoTitulo': 'Result published',
  'resultado.classificacaoPublica': 'The standings are now public.',
  'resultado.publicarResultado': 'Publish result',
  'resultado.publicarDescricao': 'Publishing makes the standings public and triggers the ranking points.',
  'resultado.motivoObservacao': 'Reason / note',
  'resultado.motivoHint': 'It is recorded in the published version.',
  'resultado.exemploMotivo': 'E.g. official result checked by the technical committee',
  'resultado.correcaoRegistradaAviso': 'Correction recorded as a new version.',
  'resultado.correcaoRegistrada': 'Correction recorded',
  'resultado.versaoPreservada': 'The previous version was preserved.',
  'resultado.corrigirResultado': 'Correct result',
  'resultado.corrigirDescricao': 'A correction does not overwrite: it creates the next version, keeps the previous one and requires a reason.',
  'resultado.motivoDaCorrecao': 'Reason for the correction',
  'resultado.exemploCorrecao': 'E.g. tie broken at a technical committee meeting',
  'resultado.situacaoDe': 'Status of {nome}',
  'resultado.colocacaoDe': 'Placement of {nome}',
  'resultado.classificado': 'Ranked',
  'resultado.colocacaoRepetida': 'Repeated placement',
  'resultado.colocacaoRepetidaTexto': 'Two identical placements do not make a valid ranking.',
  'resultado.registrarCorrecao': 'Record correction',
  'resultado.historicoDeVersoes': 'Version history',
  'resultado.historicoDescricao': 'Every change of state in the result creates a preserved version.',
  'resultado.sistema': 'system',
  'resultado.semVersoes': 'No versions recorded',
  'resultado.tituloDeclaradoAviso': 'Overall title declared. The published results were rescored.',
  'resultado.campeaoOverall': 'Overall champion',
  'resultado.declararTitulo': 'Declare Overall title',
  'resultado.declararDescricao': 'The committee decides; the platform records. The declaration stays in the audit log and rescores the results already published.',
  'resultado.tituloNaoDeclarado': 'Title not declared',
  'resultado.nadaFoiRegistrado': 'Nothing was recorded. Check your choice and try again.',
  'resultado.somenteInscritos': 'Only athletes registered in this event.',
  'resultado.selecione': 'Select…',
  'resultado.recorte': 'Scope',
  'resultado.recorteHint': 'With no scope, it is the Overall for the whole event.',
  'resultado.observacao': 'Note',
  'resultado.observacaoHint': 'It is recorded alongside the declaration.',
  'resultado.exemploObservacao': 'E.g. technical committee decision on 14/09',
  // Telas públicas: início, campeonatos, atletas e ranking.
  'publico.subtitulo': 'Competition management, results, ranking and the Brazilian bodybuilding community on a single platform.',
  'publico.onzeCategorias': 'Eleven official categories',
  'publico.quemParticipa': 'Athletes, coaches, teams and gyms',
  'publico.temporadasERanking': 'Seasons and national ranking',
  'publico.campeonatos': 'Championships',
  'publico.atletas': 'Athletes',
  'publico.atletasPro': 'PRO athletes',
  'publico.resultadosPublicados': 'Published results',
  'publico.destinoCampeonatos': 'the championships',
  'publico.destinoAtletas': 'the athletes',
  'publico.destinoRanking': 'the ranking',
  'publico.proximosCampeonatos': 'Upcoming championships',
  'publico.verTodos': 'See all',
  'publico.localADefinir': 'Venue to be defined',
  'publico.nenhumAgendado': 'No championship scheduled',
  'publico.nenhumAgendadoDescricao': 'As soon as a stage is planned, it shows up here.',
  'publico.completo': 'Full ranking',
  'publico.geral': 'Overall',
  'publico.rankingEmConstrucao': 'Ranking under construction',
  'publico.rankingEmConstrucaoDescricao': 'Points appear once the first results are published.',
  'publico.competicoes': 'Competitions',
  'publico.etapasDoCampeonato': 'Stages of the Campeonato Brasileiro Muscle Contest.',
  'publico.buscarCampeonato': 'Search championship…',
  'publico.buscarCampeonatoRotulo': 'Search championship',
  'publico.nenhumEncontrado': 'No championship found',
  'publico.nenhumEncontradoDescricao': 'Adjust the search to see other stages.',
  'publico.proximaEtapa': 'Next stage',
  'publico.descricaoPadraoDaEtapa': 'A stage of the Campeonato Brasileiro Muscle Contest.',
  'publico.voltarParaCampeonatos': '← Championships',
  'publico.voltarParaAtletas': '← Athletes',
  'publico.atletasContagem': '{n} athletes',
  'publico.abaResultados': 'Results',
  'publico.abaCategorias': 'Categories',
  'publico.abaAgenda': 'Schedule',
  'publico.abaPatrocinadores': 'Sponsors',
  'publico.publicado': 'Published',
  'publico.semEquipe': 'No team',
  'publico.semResultados': 'Results not published yet',
  'publico.semResultadosDescricao': 'The standings appear here once the organization publishes them.',
  'publico.semClasses': 'No classes registered',
  'publico.semDivisoes': 'Divisions not registered yet.',
  'publico.semCategorias': 'Categories not defined',
  'publico.semCategoriasDescricao': 'The organization has not set up the category chart yet.',
  'publico.chamadasEBaterias': 'Calls and batches',
  'publico.horarioADefinir': 'Time to be defined',
  'publico.semAgenda': 'Schedule not published',
  'publico.semAgendaDescricao': 'The batches appear once the stage order is set.',
  'publico.atletasInscritos': 'Registered athletes',
  'publico.semInscritos': 'No confirmed entries',
  'publico.patrocinadoresEMarcas': 'Sponsors and brands',
  'publico.semPatrocinadores': 'No sponsors registered',
  'publico.semPatrocinadoresDescricao': 'The event\'s institutional support shows up here.',
  'publico.comunidade': 'Community',
  'publico.perfisPublicos': 'Public profiles of the athletes on the platform.',
  'publico.buscarAtleta': 'Search by name or stage name…',
  'publico.buscarAtletaRotulo': 'Search athlete',
  'publico.nenhumAtleta': 'No athlete found',
  'publico.nenhumAtletaDescricao': 'Adjust the search or wait for new registrations.',
  'publico.semFiliacao': 'No affiliation',
  'publico.comCoach': 'Coach {nome}',
  'publico.semCoach': 'No coach',
  'publico.titulos': 'Titles',
  'publico.temporadasNoRanking': 'Seasons in the ranking',
  'publico.pontosSomados': 'Points earned',
  'publico.historicoEsportivo': 'Competitive history',
  'publico.verEtapa': 'See stage',
  'publico.semResultadosDoAtleta': 'No published results yet',
  'publico.participacoes': '{n} appearance(s)',
  'publico.semPontuacao': 'No ranking points',
  'publico.abaCampeonato': 'Championship',
  'publico.abaSuperOverall': 'Super Overall',
  'publico.abaEquipes': 'Teams',
  'publico.abaEmpresas': 'Companies',
  'publico.temporada': 'Season',
  'publico.rankingDescricao': 'Points by athlete, team, company and season. Every point is traceable back to its source.',
  'publico.classificatorioAnual': 'Annual qualifier',
  'publico.classificatorioTexto': 'Every class scores in the championship, but only <b>Open</b> feeds the Super Overall. The numbers on this tab do not add up with the ones on the others.',
  'publico.temporadaMaisRecente': 'Most recent open season',
  'publico.todasAsCategorias': 'All categories',
  'publico.uf': 'State',
  'publico.etapas': 'Stages',
  'publico.pontos': 'Points',
  'publico.legendaDoRanking': 'Each placement scores by the season\'s official table (1st = 5, 2nd = 4, 3rd = 3, 4th = 2, 5th = 1). Each <b>Overall</b> title adds <b>+10</b>, once per championship — whoever won the Overall at two championships adds +20 in the season.',
  'publico.rankingVazio': 'Empty ranking',
  'publico.rankingVazioDescricao': 'Points appear once results are published or imported.',
  'publico.semElegiveis': 'No eligible result',
  'publico.semEquipes': 'No team scored',
  'publico.semEmpresas': 'No company scored',
  'publico.semElegiveisDescricao': 'Only published results from the Open class feed the annual qualifier.',
  'publico.semEquipesDescricao': 'A team scores through what its athletes achieve.',
  'publico.semEmpresasDescricao': 'A company scores through what its teams achieve.',
  'publico.equipe': 'Team',
  'publico.empresa': 'Company',
  'publico.primeiroCriterio': 'First tiebreak criterion',
  'publico.empate': 'tie',
  // MCI Social: feed, stories, publicações, perfis, comunidades e notificações.
  'social.storyPublicado': 'Story posted.',
  'social.enviando': 'Uploading…',
  'social.seuStory': 'Your story',
  'social.publicarStory': 'Post story',
  'social.story': 'Story',
  'social.expira': 'expires {quando}',
  'social.publicacaoCriadaAviso': 'Post created.',
  'social.publicacaoCriada': 'Post created',
  'social.jaNoPerfil': 'It is already on your profile.',
  'social.compartilhePlaceholder': 'Share a workout, a backstage moment, a result…',
  'social.conteudoDaPublicacao': 'Post content',
  'social.midia': 'Media',
  'social.anexarMidia': 'Attach media',
  'social.previaDe': 'Preview of {nome}',
  'social.removerArquivo': 'Remove {nome}',
  'social.visibilidade': 'Visibility',
  'social.publica': 'Public',
  'social.seguidores': 'Followers',
  'social.somenteEu': 'Only me',
  'social.publicando': 'Posting…',
  'social.publicar': 'Post',
  'social.responder': 'Reply',
  'social.apagar': 'Delete',
  'social.respondendoA': 'Replying to @{handle}…',
  'social.comentarPlaceholder': 'Comment…',
  'social.comentario': 'Comment',
  'social.compartilhadaAviso': 'Post shared.',
  'social.removidaAviso': 'Post removed.',
  'social.motivoDaDenuncia': 'Describe the reason for the report:',
  'social.denunciaRegistrada': 'Report filed. Moderation will review it.',
  'social.visibilidadeSeguidores': 'followers',
  'social.visibilidadePrivado': 'private',
  'social.apagarPublicacao': 'Delete post',
  'social.denunciarPublicacao': 'Report post',
  'social.midiaDaPublicacao': 'Post media',
  'social.curtirRotulo': 'Like post ({n})',
  'social.descurtirRotulo': 'Unlike post ({n})',
  'social.abrirComentarios': 'Open comments ({n})',
  'social.fecharComentarios': 'Close comments ({n})',
  'social.compartilharRotulo': 'Share post ({n})',
  'social.salvarRotulo': 'Save post ({n})',
  'social.removerDosSalvosRotulo': 'Remove post from saved ({n})',
  'social.mciSocial': 'MCI Social',
  'social.feed': 'Feed',
  'social.feedDescricao': 'The Muscle Contest community: athletes, coaches, gyms, teams and brands.',
  'social.seguindo': 'Following',
  'social.descobrir': 'Discover',
  'social.feedVazio': 'Your feed is empty',
  'social.semPublicasAinda': 'There are no public posts yet',
  'social.feedVazioDescricao': 'Follow athletes, coaches and brands to see what they post.',
  'social.publiqueAlgo': 'Post something to start the conversation.',
  'social.descobrirPerfis': 'Discover profiles',
  'social.comunidades': 'Communities',
  'social.membrosEPublicacoes': '{membros} members · {publicacoes} posts',
  'social.membro': 'Member',
  'social.perfilBloqueado': 'Profile blocked.',
  'social.publicacoes': 'posts',
  'social.seguidoresContagem': 'followers',
  'social.seguindoContagem': 'following',
  'social.deixarDeSeguir': 'Unfollow',
  'social.seguir': 'Follow',
  'social.bloquear': 'Block',
  'social.titulos': 'Titles',
  'social.podios': 'Podiums',
  'social.equipe': 'Team',
  'social.academia': 'Gym',
  'social.verEtapa': 'See stage',
  'social.semPublicacoes': 'No posts',
  'social.semPublicacoesDescricao': 'This profile has not posted anything visible to you yet.',
  'social.perfilPrivado': 'Private profile',
  'social.perfilPrivadoDescricao': 'Follow this profile to see the posts.',
  'social.mciCommunity': 'MCI Community',
  'social.comunidadesDescricao': 'Spaces by category, role and championship.',
  'social.privada': 'Private',
  'social.semDescricao': 'No description.',
  'social.membros': '{n} members',
  'social.publicacoesContagem': '{n} posts',
  'social.abrir': 'Open',
  'social.entrar': 'Join',
  'social.nenhumaComunidade': 'No community available',
  'social.entrouEm': 'You joined {nome}.',
  'social.publicadoNaComunidade': 'Posted in the community.',
  'social.voltarParaComunidades': '← Communities',
  'social.sair': 'Leave',
  'social.regras': 'Rules',
  'social.publicarEm': 'Post in {nome}…',
  'social.publicacaoNaComunidade': 'Community post',
  'social.sejaOPrimeiro': 'Be the first to post here.',
  'social.entreParaParticipar': 'Join the community to take part.',
  'social.membrosTitulo': 'Members',
  'social.admin': 'Admin',
  'social.salvos': 'Saved',
  'social.salvosDescricao': 'Posts you have saved.',
  'social.nadaSalvo': 'Nothing saved yet',
  'social.nadaSalvoDescricao': 'Use the bookmark on a post to keep it here.',
  'social.central': 'Center',
  'social.notificacoes': 'Notifications',
  'social.notificacoesDescricao': 'Social interactions, messages and championship activity.',
  'social.marcarTodas': 'Mark all as read',
  'social.marcarLida': 'Mark as read',
  'social.nenhumaNotificacao': 'No notifications',
  'social.nenhumaNotificacaoDescricao': 'Likes, comments, messages and results show up here.',
  'social.meuPerfilSocial': 'My social profile',
  'social.meuPerfilDescricao': 'Public identity in the Muscle Contest community.',
  'social.semBio': 'No bio.',
  'social.editarPerfil': 'Edit profile',
  'social.formatoNaoAceito': 'Format not accepted. Use JPG, PNG or WebP.',
  'social.fotoGrandeDemais': 'The photo is over 5 MB. Choose a smaller one.',
  'social.fotoAtualizada': 'Profile photo updated.',
  'social.fotoRemovida': 'Profile photo removed.',
  'social.previaDaNovaFoto': 'Preview of the new profile photo',
  'social.salvando': 'Saving…',
  'social.salvarFoto': 'Save photo',
  'social.trocarFoto': 'Change photo',
  'social.adicionarFoto': 'Add photo',
  'social.removerFoto': 'Remove photo',
  'social.escolherFoto': 'Choose profile photo',
  'social.perfilAtualizado': 'Profile updated.',
  'social.editarPerfilSocial': 'Edit social profile',
  'social.nomeDeExibicao': 'Display name',
  'social.identificador': 'Handle',
  'social.identificadorHint': 'Lowercase letters, numbers, dot and underscore only.',
  'social.bio': 'Bio',
  'social.perfilPrivadoOpcao': 'Private profile (only followers see the posts)',
};
