// Dicionário ES. Toda chave daqui existe em `ptBR.js`, e vice-versa: a
// paridade é cobrada por teste, e chave sem par é falha, não pendência.

export default {
  'idioma.escolher': 'Idioma',
  'idioma.pt-BR': 'Português',
  'idioma.en': 'English',
  'idioma.es': 'Español',


  // Navegação. A CHAVE é a ROTA — o mesmo identificador que o roteador usa.
  // Derivar a chave do rótulo em português quebraria na primeira renomeação;
  // derivá-la da rota amarra a tradução ao destino, que é o que não muda.
  'nav.inicio': 'Inicio',
  'nav.campeonatos': 'Campeonatos',
  'nav.atletas': 'Atletas',
  'nav.ranking': 'Ranking',
  'nav.social': 'Social',
  'nav.messenger': 'Messenger',
  'nav.comunidades': 'Comunidades',
  'nav.meu-painel': 'Mi panel',
  'nav.minha-filiacao': 'Mi afiliación',
  'nav.meu-historico': 'Mi historial',
  'nav.admin': 'Panel',
  'nav.admin/eventos': 'Eventos',
  'nav.admin/inscricoes': 'Inscripciones',
  'nav.admin/solicitacoes': 'Solicitudes',
  'nav.admin/checkin': 'Check-in',
  'nav.admin/pesagem': 'Pesaje',
  'nav.admin/credenciamento': 'Acreditación',
  'nav.admin/palco': 'Escenario',
  'nav.admin/resultados': 'Resultados',
  'nav.admin/ranking': 'Ranking',
  'nav.admin/overall': 'Overall',
  'nav.admin/lancamentos': 'Asientos de puntos',
  'nav.admin/musclewar': 'MuscleWare',
  'nav.admin/auditoria': 'Auditoría',
  'nav.admin/configuracoes': 'Configuración',
  'grupo.plataforma': 'Plataforma',
  'grupo.administracao': 'Administración',
  'navegacao.principal': 'Navegación principal',
  'navegacao.abrirMenu': 'Abrir menú',
  'navegacao.fecharMenu': 'Cerrar menú',
  'navegacao.inicio': 'Inicio',
  'navegacao.campeonatos': 'Campeonatos',
  'navegacao.ranking': 'Ranking',
  'navegacao.atletas': 'Atletas',
  'navegacao.inscricoes': 'Inscripciones',
  'navegacao.resultados': 'Resultados',
  'navegacao.importacoes': 'Importaciones',
  'navegacao.solicitacoes': 'Solicitudes',
  'navegacao.minhaCarreira': 'Mi carrera',
  'navegacao.configuracoes': 'Configuración',

  'topo.busca': 'Buscar',
  'topo.somLigado': 'Sonido activado',
  'topo.somDesligado': 'Sonido desactivado',
  'topo.ligarSom': 'Activar el sonido del sistema',
  'topo.desligarSom': 'Desactivar el sonido del sistema',
  'topo.notificacoes': 'Notificaciones',
  'topo.naoLidas': '{n} sin leer',
  'topo.meuPerfil': 'Mi perfil social',
  'topo.sair': 'Salir',

  'acao.aplicar': 'Aplicar',
  'acao.revisar': 'Revisar',
  'acao.excluir': 'Eliminar',
  'acao.invalidar': 'Anular',
  'acao.cancelar': 'Cancelar',
  'acao.confirmar': 'Confirmar',
  'acao.salvar': 'Guardar',
  'acao.voltar': 'Volver',
  'acao.fechar': 'Cerrar',
  'acao.filtrar': 'Filtrar',
  'acao.limparFiltros': 'Limpiar filtros',

  'estado.carregando': 'Cargando…',
  'estado.vazio': 'Todavía no hay nada aquí',
  'estado.erro': 'No se pudo cargar',
  'estado.semPermissao': 'No tienes permiso para ver esto',

  'pagina.anterior': 'Página anterior',
  'pagina.proxima': 'Página siguiente',
  'pagina.de': 'Página {atual} de {total}',

  'ranking.geral': 'Ranking General',
  'ranking.superOverall': 'Super Overall',
  'ranking.equipes': 'Ranking de equipos',
  'ranking.empresas': 'Ranking de empresas',
  'ranking.pontos': 'Puntos',
  'ranking.posicao': 'Posición',
  'ranking.etapas': 'Etapas',
  'ranking.empateNaoResolvido': 'Empate no resuelto',
  'ranking.semCadastro': 'Sin registro en el MCI',

  'importacao.resumo':
    'Se agregarán {n} resultados al historial/ranking. '
    + 'Los atletas que aún no estén registrados permanecerán pendientes de vinculación. '
    + 'No se creará ningún atleta automáticamente.',
  'importacao.totalRegistros': 'Registros leídos',
  'importacao.reconhecidos': 'Reconocidos',
  'importacao.pendentes': 'Pendientes de vinculación',
  'importacao.conflitos': 'Conflictos',
  'importacao.duplicados': 'Duplicados',
  'importacao.rejeitados': 'Rechazados',
  'importacao.aplicaveis': 'Aplicables',

  'vinculo.automatico': 'Vinculado automáticamente',
  'vinculo.porCpf': 'Vinculado automáticamente por CPF',
  'vinculo.porMatricula': 'Vinculado automáticamente por afiliación + matrícula',
  'vinculo.pendente': 'Pendiente de vinculación',
  'vinculo.conflito': 'Conflicto de identidad',
  'vinculo.naoIdentificado': 'No identificado',

  // Tela de recuperação do limite de erro. Ela aparece JUSTAMENTE quando algo
  // quebrou — e em espanhol ou inglês continua tendo de dizer o que fazer.
  'erro.titulo': 'Esta pantalla dejó de responder',
  'erro.explicacao': 'El resto del sistema sigue funcionando. Vuelva al inicio e inténtelo de nuevo; si ocurre otra vez, avise al soporte técnico indicando en qué pantalla fue.',
  'erro.voltarAoInicio': 'Volver al inicio',
  'erro.recarregar': 'Recargar',

  // Abertura e entrada. O NOME do campeonato não entra aqui: é dado oficial, e
  // sai como está nos três idiomas.
  'abertura.rotulo': 'Apertura de MCI Platform',
  'abertura.entrarAgora': 'Entrar ahora',
  'login.entrar': 'Entrar',
  'login.semConta': '¿No tiene cuenta?',
  'login.criarConta': 'Crear cuenta',

  // Busca global do topo.
  'busca.placeholder': 'Buscar atleta, evento, perfil, comunidad…',
  'busca.rotulo': 'Búsqueda global',
  'busca.nadaEncontrado': 'No se encontró nada.',
  'busca.atleta': 'Atleta',
  'busca.campeonato': 'Campeonato',
  'busca.perfil': 'Perfil',
  'busca.comunidade': 'Comunidad',
  'abertura.ativarSom': 'Activar la experiencia sonora',
  'abertura.silenciar': 'Silenciar',
  'login.email': 'Correo electrónico',
  'login.senha': 'Contraseña',
  'estado.aguarde': 'Espere…',
  'busca.perfilDe': 'Perfil',
  // Blocos compartilhados de interface: esqueleto, erro, vazio, modal, toast,
  // paginação e credencial. Traduzidos num lugar só porque aparecem em todas as
  // telas — texto repetido em quinze páginas é quinze chances de divergir.
  'ui.carregando': 'Cargando',
  'ui.tentarDeNovo': 'Intentar de nuevo',
  'ui.vazioDescricao': 'Cuando haya registros, aparecerán en esta pantalla.',
  'ui.midiaIndisponivel': 'Medio no disponible.',
  'ui.imagemAmpliada': 'Imagen ampliada',
  'ui.fecharImagem': 'Cerrar la imagen',
  'ui.dispensar': 'Descartar',
  'ui.carregarMais': 'Cargar más',
  'ui.qrFalhou': 'No se pudo dibujar el QR. El código sigue legible al lado.',
  'ui.qrDaCredencial': 'QR de la credencial {valor}',
  'ui.atualizadoAgora': 'Actualizado ahora',
  'ui.atualizadoMinutos': 'Actualizado hace {n} min',
  'ui.atualizadoHoras': 'Actualizado hace {n} h',
  // Minha filiação e meu histórico — a área do atleta sobre a própria carreira.
  // O NOME da entidade, da categoria e da classe vem do banco e não é traduzido:
  // o que traduz é o rótulo em volta.
  'carreira.meuEspaco': 'Mi espacio',
  'carreira.minhaFiliacao': 'Mi afiliación',
  'carreira.minhaFiliacaoDescricao': 'La entidad por la que compite y su número de registro en ella.',
  'carreira.semPerfil': 'Todavía no tiene perfil de atleta',
  'carreira.semPerfilDescricao': 'Competir exige afiliación confirmada por la federación. Envíe su solicitud con CPF, entidad de afiliación y número de registro — un operador la analiza.',
  'carreira.semFiliacao': 'Sin afiliación registrada',
  'carreira.semFiliacaoDescricao': 'Su perfil existe en {organizacao}, pero ninguna entidad de afiliación está vinculada a él. La federación es quien registra el vínculo y el número.',
  'carreira.suaOrganizacao': 'su organización',
  'carreira.ativa': 'Activa',
  'carreira.inativa': 'Inactiva',
  'carreira.codigoDaEntidade': 'Código de la entidad',
  'carreira.minhaMatricula': 'Mi matrícula',
  'carreira.uf': 'Estado',
  'carreira.organizacaoNota': 'La entidad y el número son registrados por la federación — si algo está mal, hable con un operador.',
  'carreira.organizacao': 'Organización',
  'carreira.meuHistorico': 'Mi historial',
  'carreira.meuHistoricoDescricao': 'Cada participación que puntuó, con la cuenta abierta: colocación, bono de Overall y total.',
  'carreira.semPontos': 'Todavía no ha puntuado',
  'carreira.semPontosDescricao': 'En cuanto se publique un resultado y la etapa esté vinculada a una temporada, su participación aparece aquí.',
  'carreira.porCategoria': 'Desempeño por categoría',
  'carreira.porCategoriaNota': 'Cada categoría tiene su propio ranking',
  'carreira.semCategoria': 'Sin categoría',
  'carreira.participacoesContagem': '{n} participaciones',
  'carreira.participacaoContagem': '{n} participación',
  'carreira.participacoes': 'Participaciones',
  'carreira.pontosDeColocacao': 'Puntos de colocación',
  'carreira.bonusOverall': 'Bono Overall',
  'carreira.totalGeral': 'Total general',
  'carreira.totalGeralNota': 'Suma de todas las categorías',
  'carreira.colunaCampeonato': 'Campeonato',
  'carreira.colunaCategoriaClasse': 'Categoría · clase',
  'carreira.colunaColocacaoCurta': 'Col.',
  'carreira.colunaColocacao': 'Colocación',
  'carreira.colunaOverall': 'Overall',
  'carreira.colunaTotal': 'Total',
  'carreira.colunaFiliacaoNaEpoca': 'Afiliación en la época',
  'carreira.colunaPtsColocacao': 'Pts colocación',
  'carreira.colunaCategoria': 'Categoría',
  'carreira.colunaFiliacao': 'Afiliación',
  'carreira.campeaoOverall': 'Campeón Overall',
  'carreira.numeroAbreviado': 'n.º {numero}',
  'carreira.filiacaoNaoRegistrada': 'no registrada',
  'carreira.rodapeContagem': 'Mostrando {mostrando} de {total} participación(es).',
  'carreira.rodapeOverall': 'El bono de Overall es de la clase absoluta y vale una vez por título.',
  // Mensagens de validação dos formulários. A VALIDAÇÃO devolve a CHAVE, e não
  // a frase: `lib/formulario.js` não é componente, não tem contexto de idioma, e
  // devolver português de dentro dela deixaria o erro em português numa tela em
  // espanhol. Quem traduz é quem desenha o erro na tela.
  'form.erro.nome': 'Indique su nombre completo',
  'form.erro.nomeDocumento': 'Indique el nombre tal como consta en el documento',
  'form.erro.nascimento': 'Indique una fecha de nacimiento válida',
  'form.erro.email': 'Indique un correo electrónico válido',
  'form.erro.senha': 'La contraseña necesita al menos 8 caracteres',
  'form.erro.telefone': 'Teléfono con prefijo y 8 o 9 dígitos',
  'form.erro.whatsapp': 'WhatsApp con prefijo y 8 o 9 dígitos',
  'form.erro.cep': 'Código postal con 8 dígitos',
  'form.erro.endereco': 'Indique la dirección',
  'form.erro.numero': 'Indique el número',
  'form.erro.uf': 'Seleccione el estado',
  'form.erro.cidade': 'Indique la ciudad',
  'form.erro.cpf': 'CPF inválido',
  'form.erro.sexo': 'Seleccione la categoría de competición',
  'form.erro.filiacao': 'Seleccione la entidad de afiliación',
  'form.erro.matricula': 'Indique el número de registro',
  // Perfis abertos no cadastro. O CÓDIGO ('ATHLETE', 'COACH'…) é o que vai para
  // a API e nunca muda; aqui traduz-se só o que a pessoa lê.
  'papel.ATHLETE': 'Atleta',
  'papel.ATHLETE.descricao': 'Compite en las etapas del Campeonato Brasileño',
  'papel.COACH': 'Coach',
  'papel.COACH.descricao': 'Prepara y acompaña a atletas',
  'papel.GYM': 'Gimnasio',
  'papel.GYM.descricao': 'Centro de entrenamiento',
  'papel.TEAM': 'Equipo',
  'papel.TEAM.descricao': 'Equipo que reúne a atletas',
  'papel.BRAND': 'Marca',
  'papel.BRAND.descricao': 'Marca del ecosistema',
  'papel.SPONSOR': 'Patrocinador',
  'papel.SPONSOR.descricao': 'Apoya a atletas y etapas',
  'papel.MEDIA': 'Prensa',
  'papel.MEDIA.descricao': 'Cobertura y contenido',
  // Cadastro em cinco etapas.
  'cadastro.etapa1': 'IDENTIDAD',
  'cadastro.etapa1.titulo': 'Quién es usted',
  'cadastro.etapa2': 'CONTACTO',
  'cadastro.etapa2.titulo': 'Cómo hablamos con usted',
  'cadastro.etapa3': 'DIRECCIÓN',
  'cadastro.etapa3.titulo': 'Dónde está',
  'cadastro.etapa4': 'PERFIL DEPORTIVO',
  'cadastro.etapa4.titulo': 'Lo que viene después',
  'cadastro.etapa5': 'REVISIÓN',
  'cadastro.etapa5.titulo': 'Revise antes de enviar',
  'cadastro.etapaDe': 'Paso {atual} de {total}',
  'cadastro.emailJaCadastrado': 'Este correo ya está registrado',
  'cadastro.nomeCompleto': 'Nombre completo',
  'cadastro.dataDeNascimento': 'Fecha de nacimiento',
  'cadastro.voceE': 'Usted es',
  'cadastro.voceEHint': 'Define cómo aparece en la plataforma. No es un nivel de acceso.',
  'cadastro.email': 'Correo electrónico',
  'cadastro.senha': 'Contraseña',
  'cadastro.senhaHint': 'Al menos 8 caracteres.',
  'cadastro.telefone': 'Teléfono',
  'cadastro.whatsapp': 'WhatsApp',
  'cadastro.mesmoNumero': 'Usar el mismo número del teléfono',
  'cadastro.cep': 'Código postal',
  'cadastro.cepHint': 'Completamos la dirección por usted.',
  'cadastro.buscandoEndereco': 'Buscando la dirección…',
  'cadastro.endereco': 'Dirección',
  'cadastro.numero': 'Número',
  'cadastro.complemento': 'Complemento',
  'cadastro.cidade': 'Ciudad',
  'cadastro.uf': 'Estado',
  'cadastro.filiacaoTitulo': 'Su afiliación la confirma la federación',
  'cadastro.filiacaoTexto': 'Competir exige un vínculo que la MCI no concede por sí sola: quien lo confirma es la federación a la que está afiliado. Por eso su perfil de atleta pasa por un análisis — y solo empieza después de que su cuenta exista.',
  'cadastro.filiacaoProximoPasso': 'En cuanto complete el registro, abriremos la página <b>Mi solicitud</b>, donde indica el <b>CPF</b>, la <b>entidad de afiliación</b> y su <b>número de registro</b>. Un operador de la federación lo analiza y aprueba.',
  'cadastro.cpfDepois': 'El CPF no se pide aquí a propósito: solo se escribe después de que exista su sesión, y va directo a la federación — nunca queda guardado en este navegador.',
  'cadastro.semMaisNada': 'No necesitamos nada más',
  'cadastro.semMaisNadaTexto': 'El perfil <b>{papel}</b> no compite en las etapas, así que no pedimos CPF ni afiliación — sería recoger un documento de quien no va a competir.',
  'cadastro.funcoesDeOperacao': 'Las funciones de operación — dirección de evento, acreditación, pesaje, escenario, resultados — no se eligen aquí. Las concede la organización del campeonato a una cuenta que ya existe.',
  'cadastro.confiraOsDados': 'Revise los datos. Puede volver y corregir cualquier paso.',
  'cadastro.jaTenhoConta': 'Ya tengo cuenta',
  'cadastro.continuar': 'Continuar',
  'cadastro.enviando': 'Enviando…',
  'cadastro.revisaoIdentidade': 'Identidad',
  'cadastro.revisaoContato': 'Contacto',
  'cadastro.revisaoEndereco': 'Dirección',
  'cadastro.revisaoNome': 'Nombre',
  'cadastro.revisaoNascimento': 'Nacimiento',
  'cadastro.revisaoPerfil': 'Perfil',
  'cadastro.editar': 'Editar',
  // Conferência local da foto. `lib/foto.js` devolve CHAVE e valores, pelo mesmo
  // motivo de `lib/formulario.js`: não é componente e não sabe o idioma.
  'foto.erro.semArquivo': 'Elija una imagen.',
  'foto.erro.tipo': 'La foto debe ser JPG, PNG o WebP.',
  'foto.erro.tamanho': 'La foto tiene {tamanho} MB y el límite es {limite} MB.',
  'foto.erro.vazio': 'El archivo está vacío.',
  // Solicitação de perfil de atleta.
  'solicitacao.perfilDeAtleta': 'Perfil de atleta',
  'solicitacao.minhaSolicitacao': 'Mi solicitud',
  'solicitacao.descricao': 'Competir exige afiliación confirmada por la federación. Usted envía los datos; un operador los analiza.',
  'solicitacao.emAnalise': 'En análisis',
  'solicitacao.aprovada': 'Aprobada',
  'solicitacao.recusada': 'Rechazada',
  'solicitacao.cancelada': 'Cancelada',
  'solicitacao.canceladaAviso': 'Solicitud cancelada.',
  'solicitacao.perfilAtivo': 'Perfil de atleta activo',
  'solicitacao.jaCompete': 'Ya compite por la MCI',
  'solicitacao.jaCompeteTexto': 'Su perfil de atleta está activo. Para corregir la afiliación, el número de registro o cualquier dato de su ficha, hable con su federación — esos campos los mantiene ella, no esta pantalla.',
  'solicitacao.foiAprovada': 'Su solicitud fue aprobada',
  'solicitacao.foiAprovadaTexto': 'La federación aprobó su perfil. Si todavía no aparece aquí, actualice la sesión.',
  'solicitacao.atualizarSessao': 'Actualizar mi sesión',
  'solicitacao.cancelarSolicitacao': 'Cancelar solicitud',
  'solicitacao.cancelarAviso': 'La solicitud sale de la cola de la federación y el CPF enviado se borra. Puede enviar otra después.',
  'solicitacao.naFila': 'Su solicitud está en la cola de la federación',
  'solicitacao.enviadaEm': 'Enviada el {data}. Un operador de',
  'solicitacao.suaFederacao': 'su federación',
  'solicitacao.vaiAnalisar': 'la analizará. Mientras tanto, puede usar la plataforma normalmente.',
  'solicitacao.nome': 'Nombre',
  'solicitacao.entidade': 'Entidad de afiliación',
  'solicitacao.numeroDeRegistro': 'Número de registro',
  'solicitacao.cpfGuardado': 'Guardado con la federación hasta el análisis',
  'solicitacao.fotoEnviada': 'Foto enviada',
  'solicitacao.fotoEnviadaAlt': 'Foto enviada en la solicitud',
  'solicitacao.semFoto': 'Sin foto',
  'solicitacao.removerFoto': 'Quitar la foto',
  'solicitacao.fotoEnviadaAviso': 'Foto enviada.',
  'solicitacao.fotoRemovidaAviso': 'Foto eliminada.',
  'solicitacao.historico': 'Historial',
  'solicitacao.historicoTexto': 'La cola guarda lo que ya ocurrió — incluso lo que fue rechazado.',
  'solicitacao.motivo': 'Motivo',
  'solicitacao.fotoDePerfil': 'Foto de perfil',
  'solicitacao.fotoOpcional': 'Opcional. La federación usa la foto para confirmar su identidad.',
  'solicitacao.previaDaFoto': 'Vista previa de la foto elegida: {nome}',
  'solicitacao.trocarFoto': 'Cambiar la foto',
  'solicitacao.escolherFoto': 'Elegir foto',
  'solicitacao.remover': 'Quitar',
  'solicitacao.formatosDaFoto': 'JPG, PNG o WebP, hasta 5 MB.',
  'solicitacao.solicitarPerfil': 'Solicitar perfil de atleta',
  'solicitacao.solicitarTexto': 'Estos datos van directo a la federación que elija. Nada queda guardado en este navegador.',
  'solicitacao.ultimaRecusada': 'Su última solicitud fue rechazada.',
  'solicitacao.nomeHint': 'Tal como consta en su documento.',
  'solicitacao.cpfHint': 'Se usa para vincular sus resultados. Nunca aparece en búsquedas públicas.',
  'solicitacao.cpfSeraEnviado': 'Se enviará como {resumo}',
  'solicitacao.categoriaDeCompeticao': 'Categoría de competición',
  'solicitacao.categoriaHint': 'Define en qué categorías puede ser inscrito.',
  'solicitacao.feminino': 'Femenino',
  'solicitacao.masculino': 'Masculino',
  'solicitacao.nascimentoHint': 'Opcional. Se usa para comprobar su franja de edad.',
  'solicitacao.entidadeHint': 'La federación que confirma su vínculo.',
  'solicitacao.semEntidades': 'Ninguna entidad de afiliación activa está disponible para su cuenta. Hable con la organización del campeonato.',
  'solicitacao.erroEntidades': 'No pudimos cargar las entidades de afiliación.',
  'solicitacao.matriculaHint': 'El número que le dio la federación.',
  'solicitacao.avisoDeEnvio': 'Sus datos se enviarán para su validación por la federación.',
  'solicitacao.enviarParaAnalise': 'Enviar para análisis',
  'solicitacao.enviada': 'Solicitud enviada. La federación la analizará.',
  'solicitacao.enviadaSemFoto': 'Solicitud enviada, pero la foto no se subió: {erro} Puede volver a enviarla abajo.',
};
