// Dicionário ES. Toda chave daqui existe em `ptBR.js`, e vice-versa: a
// paridade é cobrada por teste, e chave sem par é falha, não pendência.

export default {
  'idioma.escolher': 'Idioma',
  'idioma.pt-BR': 'Português',
  'idioma.en': 'English',
  'idioma.es': 'Español',


  // Navegação. A CHAVE é a ROTA — o mesmo identificador que o roteador usa.
  // Derivar a chave do rótulo em português quebraria na primeira renomeação;
  // derivá-la da rota amarra a tradução ao destino, que é o que não muda.
  'nav.inicio': 'Inicio',
  'nav.campeonatos': 'Campeonatos',
  'nav.atletas': 'Atletas',
  'nav.ranking': 'Ranking',
  'nav.social': 'Social',
  'nav.messenger': 'Messenger',
  'nav.comunidades': 'Comunidades',
  'nav.meu-painel': 'Mi panel',
  'nav.minha-filiacao': 'Mi afiliación',
  'nav.meu-historico': 'Mi historial',
  'nav.admin': 'Panel',
  'nav.admin/eventos': 'Eventos',
  'nav.admin/inscricoes': 'Inscripciones',
  'nav.admin/solicitacoes': 'Solicitudes',
  'nav.admin/checkin': 'Check-in',
  'nav.admin/pesagem': 'Pesaje',
  'nav.admin/credenciamento': 'Acreditación',
  'nav.admin/palco': 'Escenario',
  'nav.admin/resultados': 'Resultados',
  'nav.admin/ranking': 'Ranking',
  'nav.admin/overall': 'Overall',
  'nav.admin/lancamentos': 'Asientos de puntos',
  'nav.admin/musclewar': 'MuscleWare',
  'nav.admin/auditoria': 'Auditoría',
  'nav.admin/configuracoes': 'Configuración',
  'grupo.plataforma': 'Plataforma',
  'grupo.administracao': 'Administración',
  'navegacao.principal': 'Navegación principal',
  'navegacao.abrirMenu': 'Abrir menú',
  'navegacao.fecharMenu': 'Cerrar menú',
  'navegacao.inicio': 'Inicio',
  'navegacao.campeonatos': 'Campeonatos',
  'navegacao.ranking': 'Ranking',
  'navegacao.atletas': 'Atletas',
  'navegacao.inscricoes': 'Inscripciones',
  'navegacao.resultados': 'Resultados',
  'navegacao.importacoes': 'Importaciones',
  'navegacao.solicitacoes': 'Solicitudes',
  'navegacao.minhaCarreira': 'Mi carrera',
  'navegacao.configuracoes': 'Configuración',

  'topo.busca': 'Buscar',
  'topo.somLigado': 'Sonido activado',
  'topo.somDesligado': 'Sonido desactivado',
  'topo.ligarSom': 'Activar el sonido del sistema',
  'topo.desligarSom': 'Desactivar el sonido del sistema',
  'topo.notificacoes': 'Notificaciones',
  'topo.naoLidas': '{n} sin leer',
  'topo.meuPerfil': 'Mi perfil social',
  'topo.sair': 'Salir',

  'acao.aplicar': 'Aplicar',
  'acao.revisar': 'Revisar',
  'acao.excluir': 'Eliminar',
  'acao.invalidar': 'Anular',
  'acao.cancelar': 'Cancelar',
  'acao.confirmar': 'Confirmar',
  'acao.salvar': 'Guardar',
  'acao.voltar': 'Volver',
  'acao.fechar': 'Cerrar',
  'acao.filtrar': 'Filtrar',
  'acao.limparFiltros': 'Limpiar filtros',

  'estado.carregando': 'Cargando…',
  'estado.vazio': 'Todavía no hay nada aquí',
  'estado.erro': 'No se pudo cargar',
  'estado.semPermissao': 'No tienes permiso para ver esto',

  'pagina.anterior': 'Página anterior',
  'pagina.proxima': 'Página siguiente',
  'pagina.de': 'Página {atual} de {total}',

  'ranking.geral': 'Ranking General',
  'ranking.superOverall': 'Super Overall',
  'ranking.equipes': 'Ranking de equipos',
  'ranking.empresas': 'Ranking de empresas',
  'ranking.pontos': 'Puntos',
  'ranking.posicao': 'Posición',
  'ranking.etapas': 'Etapas',
  'ranking.empateNaoResolvido': 'Empate no resuelto',
  'ranking.semCadastro': 'Sin registro en el MCI',

  'importacao.resumo':
    'Se agregarán {n} resultados al historial/ranking. '
    + 'Los atletas que aún no estén registrados permanecerán pendientes de vinculación. '
    + 'No se creará ningún atleta automáticamente.',
  'importacao.totalRegistros': 'Registros leídos',
  'importacao.reconhecidos': 'Reconocidos',
  'importacao.pendentes': 'Pendientes de vinculación',
  'importacao.conflitos': 'Conflictos',
  'importacao.duplicados': 'Duplicados',
  'importacao.rejeitados': 'Rechazados',
  'importacao.aplicaveis': 'Aplicables',

  'vinculo.automatico': 'Vinculado automáticamente',
  'vinculo.porCpf': 'Vinculado automáticamente por CPF',
  'vinculo.porMatricula': 'Vinculado automáticamente por afiliación + matrícula',
  'vinculo.pendente': 'Pendiente de vinculación',
  'vinculo.conflito': 'Conflicto de identidad',
  'vinculo.naoIdentificado': 'No identificado',

  // Tela de recuperação do limite de erro. Ela aparece JUSTAMENTE quando algo
  // quebrou — e em espanhol ou inglês continua tendo de dizer o que fazer.
  'erro.titulo': 'Esta pantalla dejó de responder',
  'erro.explicacao': 'El resto del sistema sigue funcionando. Vuelva al inicio e inténtelo de nuevo; si ocurre otra vez, avise al soporte técnico indicando en qué pantalla fue.',
  'erro.voltarAoInicio': 'Volver al inicio',
  'erro.recarregar': 'Recargar',

  // Abertura e entrada. O NOME do campeonato não entra aqui: é dado oficial, e
  // sai como está nos três idiomas.
  'abertura.rotulo': 'Apertura de MCI Platform',
  'abertura.entrarAgora': 'Entrar ahora',
  'login.entrar': 'Entrar',
  'login.semConta': '¿No tiene cuenta?',
  'login.criarConta': 'Crear cuenta',

  // Busca global do topo.
  'busca.placeholder': 'Buscar atleta, evento, perfil, comunidad…',
  'busca.rotulo': 'Búsqueda global',
  'busca.nadaEncontrado': 'No se encontró nada.',
  'busca.atleta': 'Atleta',
  'busca.campeonato': 'Campeonato',
  'busca.perfil': 'Perfil',
  'busca.comunidade': 'Comunidad',
  'abertura.ativarSom': 'Activar la experiencia sonora',
  'abertura.silenciar': 'Silenciar',
  'login.email': 'Correo electrónico',
  'login.senha': 'Contraseña',
  'estado.aguarde': 'Espere…',
  'busca.perfilDe': 'Perfil',
  // Blocos compartilhados de interface: esqueleto, erro, vazio, modal, toast,
  // paginação e credencial. Traduzidos num lugar só porque aparecem em todas as
  // telas — texto repetido em quinze páginas é quinze chances de divergir.
  'ui.carregando': 'Cargando',
  'ui.tentarDeNovo': 'Intentar de nuevo',
  'ui.vazioDescricao': 'Cuando haya registros, aparecerán en esta pantalla.',
  'ui.midiaIndisponivel': 'Medio no disponible.',
  'ui.imagemAmpliada': 'Imagen ampliada',
  'ui.fecharImagem': 'Cerrar la imagen',
  'ui.dispensar': 'Descartar',
  'ui.carregarMais': 'Cargar más',
  'ui.qrFalhou': 'No se pudo dibujar el QR. El código sigue legible al lado.',
  'ui.qrDaCredencial': 'QR de la credencial {valor}',
  'ui.atualizadoAgora': 'Actualizado ahora',
  'ui.atualizadoMinutos': 'Actualizado hace {n} min',
  'ui.atualizadoHoras': 'Actualizado hace {n} h',
  // Minha filiação e meu histórico — a área do atleta sobre a própria carreira.
  // O NOME da entidade, da categoria e da classe vem do banco e não é traduzido:
  // o que traduz é o rótulo em volta.
  'carreira.meuEspaco': 'Mi espacio',
  'carreira.minhaFiliacao': 'Mi afiliación',
  'carreira.minhaFiliacaoDescricao': 'La entidad por la que compite y su número de registro en ella.',
  'carreira.semPerfil': 'Todavía no tiene perfil de atleta',
  'carreira.semPerfilDescricao': 'Competir exige afiliación confirmada por la federación. Envíe su solicitud con CPF, entidad de afiliación y número de registro — un operador la analiza.',
  'carreira.semFiliacao': 'Sin afiliación registrada',
  'carreira.semFiliacaoDescricao': 'Su perfil existe en {organizacao}, pero ninguna entidad de afiliación está vinculada a él. La federación es quien registra el vínculo y el número.',
  'carreira.suaOrganizacao': 'su organización',
  'carreira.ativa': 'Activa',
  'carreira.inativa': 'Inactiva',
  'carreira.codigoDaEntidade': 'Código de la entidad',
  'carreira.minhaMatricula': 'Mi matrícula',
  'carreira.uf': 'Estado',
  'carreira.organizacaoNota': 'La entidad y el número son registrados por la federación — si algo está mal, hable con un operador.',
  'carreira.organizacao': 'Organización',
  'carreira.meuHistorico': 'Mi historial',
  'carreira.meuHistoricoDescricao': 'Cada participación que puntuó, con la cuenta abierta: colocación, bono de Overall y total.',
  'carreira.semPontos': 'Todavía no ha puntuado',
  'carreira.semPontosDescricao': 'En cuanto se publique un resultado y la etapa esté vinculada a una temporada, su participación aparece aquí.',
  'carreira.porCategoria': 'Desempeño por categoría',
  'carreira.porCategoriaNota': 'Cada categoría tiene su propio ranking',
  'carreira.semCategoria': 'Sin categoría',
  'carreira.participacoesContagem': '{n} participaciones',
  'carreira.participacaoContagem': '{n} participación',
  'carreira.participacoes': 'Participaciones',
  'carreira.pontosDeColocacao': 'Puntos de colocación',
  'carreira.bonusOverall': 'Bono Overall',
  'carreira.totalGeral': 'Total general',
  'carreira.totalGeralNota': 'Suma de todas las categorías',
  'carreira.colunaCampeonato': 'Campeonato',
  'carreira.colunaCategoriaClasse': 'Categoría · clase',
  'carreira.colunaColocacaoCurta': 'Col.',
  'carreira.colunaColocacao': 'Colocación',
  'carreira.colunaOverall': 'Overall',
  'carreira.colunaTotal': 'Total',
  'carreira.colunaFiliacaoNaEpoca': 'Afiliación en la época',
  'carreira.colunaPtsColocacao': 'Pts colocación',
  'carreira.colunaCategoria': 'Categoría',
  'carreira.colunaFiliacao': 'Afiliación',
  'carreira.campeaoOverall': 'Campeón Overall',
  'carreira.numeroAbreviado': 'n.º {numero}',
  'carreira.filiacaoNaoRegistrada': 'no registrada',
  'carreira.rodapeContagem': 'Mostrando {mostrando} de {total} participación(es).',
  'carreira.rodapeOverall': 'El bono de Overall es de la clase absoluta y vale una vez por título.',
  // Mensagens de validação dos formulários. A VALIDAÇÃO devolve a CHAVE, e não
  // a frase: `lib/formulario.js` não é componente, não tem contexto de idioma, e
  // devolver português de dentro dela deixaria o erro em português numa tela em
  // espanhol. Quem traduz é quem desenha o erro na tela.
  'form.erro.nome': 'Indique su nombre completo',
  'form.erro.nomeDocumento': 'Indique el nombre tal como consta en el documento',
  'form.erro.nascimento': 'Indique una fecha de nacimiento válida',
  'form.erro.email': 'Indique un correo electrónico válido',
  'form.erro.senha': 'La contraseña necesita al menos 8 caracteres',
  'form.erro.telefone': 'Teléfono con prefijo y 8 o 9 dígitos',
  'form.erro.whatsapp': 'WhatsApp con prefijo y 8 o 9 dígitos',
  'form.erro.cep': 'Código postal con 8 dígitos',
  'form.erro.endereco': 'Indique la dirección',
  'form.erro.numero': 'Indique el número',
  'form.erro.uf': 'Seleccione el estado',
  'form.erro.cidade': 'Indique la ciudad',
  'form.erro.cpf': 'CPF inválido',
  'form.erro.sexo': 'Seleccione la categoría de competición',
  'form.erro.filiacao': 'Seleccione la entidad de afiliación',
  'form.erro.matricula': 'Indique el número de registro',
  // Perfis abertos no cadastro. O CÓDIGO ('ATHLETE', 'COACH'…) é o que vai para
  // a API e nunca muda; aqui traduz-se só o que a pessoa lê.
  'papel.ATHLETE': 'Atleta',
  'papel.ATHLETE.descricao': 'Compite en las etapas del Campeonato Brasileño',
  'papel.COACH': 'Coach',
  'papel.COACH.descricao': 'Prepara y acompaña a atletas',
  'papel.GYM': 'Gimnasio',
  'papel.GYM.descricao': 'Centro de entrenamiento',
  'papel.TEAM': 'Equipo',
  'papel.TEAM.descricao': 'Equipo que reúne a atletas',
  'papel.BRAND': 'Marca',
  'papel.BRAND.descricao': 'Marca del ecosistema',
  'papel.SPONSOR': 'Patrocinador',
  'papel.SPONSOR.descricao': 'Apoya a atletas y etapas',
  'papel.MEDIA': 'Prensa',
  'papel.MEDIA.descricao': 'Cobertura y contenido',
  // Cadastro em cinco etapas.
  'cadastro.etapa1': 'IDENTIDAD',
  'cadastro.etapa1.titulo': 'Quién es usted',
  'cadastro.etapa2': 'CONTACTO',
  'cadastro.etapa2.titulo': 'Cómo hablamos con usted',
  'cadastro.etapa3': 'DIRECCIÓN',
  'cadastro.etapa3.titulo': 'Dónde está',
  'cadastro.etapa4': 'PERFIL DEPORTIVO',
  'cadastro.etapa4.titulo': 'Lo que viene después',
  'cadastro.etapa5': 'REVISIÓN',
  'cadastro.etapa5.titulo': 'Revise antes de enviar',
  'cadastro.etapaDe': 'Paso {atual} de {total}',
  'cadastro.emailJaCadastrado': 'Este correo ya está registrado',
  'cadastro.nomeCompleto': 'Nombre completo',
  'cadastro.dataDeNascimento': 'Fecha de nacimiento',
  'cadastro.voceE': 'Usted es',
  'cadastro.voceEHint': 'Define cómo aparece en la plataforma. No es un nivel de acceso.',
  'cadastro.email': 'Correo electrónico',
  'cadastro.senha': 'Contraseña',
  'cadastro.senhaHint': 'Al menos 8 caracteres.',
  'cadastro.telefone': 'Teléfono',
  'cadastro.whatsapp': 'WhatsApp',
  'cadastro.mesmoNumero': 'Usar el mismo número del teléfono',
  'cadastro.cep': 'Código postal',
  'cadastro.cepHint': 'Completamos la dirección por usted.',
  'cadastro.buscandoEndereco': 'Buscando la dirección…',
  'cadastro.endereco': 'Dirección',
  'cadastro.numero': 'Número',
  'cadastro.complemento': 'Complemento',
  'cadastro.cidade': 'Ciudad',
  'cadastro.uf': 'Estado',
  'cadastro.filiacaoTitulo': 'Su afiliación la confirma la federación',
  'cadastro.filiacaoTexto': 'Competir exige un vínculo que la MCI no concede por sí sola: quien lo confirma es la federación a la que está afiliado. Por eso su perfil de atleta pasa por un análisis — y solo empieza después de que su cuenta exista.',
  'cadastro.filiacaoProximoPasso': 'En cuanto complete el registro, abriremos la página <b>Mi solicitud</b>, donde indica el <b>CPF</b>, la <b>entidad de afiliación</b> y su <b>número de registro</b>. Un operador de la federación lo analiza y aprueba.',
  'cadastro.cpfDepois': 'El CPF no se pide aquí a propósito: solo se escribe después de que exista su sesión, y va directo a la federación — nunca queda guardado en este navegador.',
  'cadastro.semMaisNada': 'No necesitamos nada más',
  'cadastro.semMaisNadaTexto': 'El perfil <b>{papel}</b> no compite en las etapas, así que no pedimos CPF ni afiliación — sería recoger un documento de quien no va a competir.',
  'cadastro.funcoesDeOperacao': 'Las funciones de operación — dirección de evento, acreditación, pesaje, escenario, resultados — no se eligen aquí. Las concede la organización del campeonato a una cuenta que ya existe.',
  'cadastro.confiraOsDados': 'Revise los datos. Puede volver y corregir cualquier paso.',
  'cadastro.jaTenhoConta': 'Ya tengo cuenta',
  'cadastro.continuar': 'Continuar',
  'cadastro.enviando': 'Enviando…',
  'cadastro.revisaoIdentidade': 'Identidad',
  'cadastro.revisaoContato': 'Contacto',
  'cadastro.revisaoEndereco': 'Dirección',
  'cadastro.revisaoNome': 'Nombre',
  'cadastro.revisaoNascimento': 'Nacimiento',
  'cadastro.revisaoPerfil': 'Perfil',
  'cadastro.editar': 'Editar',
  // Conferência local da foto. `lib/foto.js` devolve CHAVE e valores, pelo mesmo
  // motivo de `lib/formulario.js`: não é componente e não sabe o idioma.
  'foto.erro.semArquivo': 'Elija una imagen.',
  'foto.erro.tipo': 'La foto debe ser JPG, PNG o WebP.',
  'foto.erro.tamanho': 'La foto tiene {tamanho} MB y el límite es {limite} MB.',
  'foto.erro.vazio': 'El archivo está vacío.',
  // Solicitação de perfil de atleta.
  'solicitacao.perfilDeAtleta': 'Perfil de atleta',
  'solicitacao.minhaSolicitacao': 'Mi solicitud',
  'solicitacao.descricao': 'Competir exige afiliación confirmada por la federación. Usted envía los datos; un operador los analiza.',
  'solicitacao.emAnalise': 'En análisis',
  'solicitacao.aprovada': 'Aprobada',
  'solicitacao.recusada': 'Rechazada',
  'solicitacao.cancelada': 'Cancelada',
  'solicitacao.canceladaAviso': 'Solicitud cancelada.',
  'solicitacao.perfilAtivo': 'Perfil de atleta activo',
  'solicitacao.jaCompete': 'Ya compite por la MCI',
  'solicitacao.jaCompeteTexto': 'Su perfil de atleta está activo. Para corregir la afiliación, el número de registro o cualquier dato de su ficha, hable con su federación — esos campos los mantiene ella, no esta pantalla.',
  'solicitacao.foiAprovada': 'Su solicitud fue aprobada',
  'solicitacao.foiAprovadaTexto': 'La federación aprobó su perfil. Si todavía no aparece aquí, actualice la sesión.',
  'solicitacao.atualizarSessao': 'Actualizar mi sesión',
  'solicitacao.cancelarSolicitacao': 'Cancelar solicitud',
  'solicitacao.cancelarAviso': 'La solicitud sale de la cola de la federación y el CPF enviado se borra. Puede enviar otra después.',
  'solicitacao.naFila': 'Su solicitud está en la cola de la federación',
  'solicitacao.enviadaEm': 'Enviada el {data}. Un operador de',
  'solicitacao.suaFederacao': 'su federación',
  'solicitacao.vaiAnalisar': 'la analizará. Mientras tanto, puede usar la plataforma normalmente.',
  'solicitacao.nome': 'Nombre',
  'solicitacao.entidade': 'Entidad de afiliación',
  'solicitacao.numeroDeRegistro': 'Número de registro',
  'solicitacao.cpfGuardado': 'Guardado con la federación hasta el análisis',
  'solicitacao.fotoEnviada': 'Foto enviada',
  'solicitacao.fotoEnviadaAlt': 'Foto enviada en la solicitud',
  'solicitacao.semFoto': 'Sin foto',
  'solicitacao.removerFoto': 'Quitar la foto',
  'solicitacao.fotoEnviadaAviso': 'Foto enviada.',
  'solicitacao.fotoRemovidaAviso': 'Foto eliminada.',
  'solicitacao.historico': 'Historial',
  'solicitacao.historicoTexto': 'La cola guarda lo que ya ocurrió — incluso lo que fue rechazado.',
  'solicitacao.motivo': 'Motivo',
  'solicitacao.fotoDePerfil': 'Foto de perfil',
  'solicitacao.fotoOpcional': 'Opcional. La federación usa la foto para confirmar su identidad.',
  'solicitacao.previaDaFoto': 'Vista previa de la foto elegida: {nome}',
  'solicitacao.trocarFoto': 'Cambiar la foto',
  'solicitacao.escolherFoto': 'Elegir foto',
  'solicitacao.remover': 'Quitar',
  'solicitacao.formatosDaFoto': 'JPG, PNG o WebP, hasta 5 MB.',
  'solicitacao.solicitarPerfil': 'Solicitar perfil de atleta',
  'solicitacao.solicitarTexto': 'Estos datos van directo a la federación que elija. Nada queda guardado en este navegador.',
  'solicitacao.ultimaRecusada': 'Su última solicitud fue rechazada.',
  'solicitacao.nomeHint': 'Tal como consta en su documento.',
  'solicitacao.cpfHint': 'Se usa para vincular sus resultados. Nunca aparece en búsquedas públicas.',
  'solicitacao.cpfSeraEnviado': 'Se enviará como {resumo}',
  'solicitacao.categoriaDeCompeticao': 'Categoría de competición',
  'solicitacao.categoriaHint': 'Define en qué categorías puede ser inscrito.',
  'solicitacao.feminino': 'Femenino',
  'solicitacao.masculino': 'Masculino',
  'solicitacao.nascimentoHint': 'Opcional. Se usa para comprobar su franja de edad.',
  'solicitacao.entidadeHint': 'La federación que confirma su vínculo.',
  'solicitacao.semEntidades': 'Ninguna entidad de afiliación activa está disponible para su cuenta. Hable con la organización del campeonato.',
  'solicitacao.erroEntidades': 'No pudimos cargar las entidades de afiliación.',
  'solicitacao.matriculaHint': 'El número que le dio la federación.',
  'solicitacao.avisoDeEnvio': 'Sus datos se enviarán para su validación por la federación.',
  'solicitacao.enviarParaAnalise': 'Enviar para análisis',
  'solicitacao.enviada': 'Solicitud enviada. La federación la analizará.',
  'solicitacao.enviadaSemFoto': 'Solicitud enviada, pero la foto no se subió: {erro} Puede volver a enviarla abajo.',
  // Painel do atleta e conta do usuário.
  'painel.meuPainel': 'Mi panel',
  'painel.descricao': 'Inscripciones, agenda, tandas, resultados, ranking y vida social.',
  'painel.semPerfilDescricao': 'Competir exige afiliación confirmada por la federación. Envíe su solicitud con CPF, entidad de afiliación y número de registro — un operador la analiza. Mientras tanto, el área social está totalmente disponible.',
  'painel.irParaOFeed': 'Ir al feed',
  'painel.semFiliacao': 'Sin afiliación',
  'painel.semEquipe': 'Sin equipo',
  'painel.semAcademia': 'Sin gimnasio',
  'painel.titulos': 'Títulos',
  'painel.inscricoes': 'Inscripciones',
  'painel.publicacoes': 'Publicaciones',
  'painel.seguidores': '{n} seguidores',
  'painel.mensagens': 'Mensajes',
  'painel.naCaixaDeEntrada': 'en la bandeja de entrada',
  'painel.minhaAgenda': 'Mi agenda',
  'painel.semEventosFuturos': 'Sin eventos futuros',
  'painel.semEventosFuturosDescricao': 'Sus próximas etapas aparecen aquí.',
  'painel.minhasBaterias': 'Mis tandas',
  'painel.horarioADefinir': 'horario por definir',
  'painel.meusResultados': 'Mis resultados',
  'painel.semResultados': 'Sin resultados publicados',
  'painel.meuRanking': 'Mi ranking',
  'painel.rankingGeral': 'General',
  'painel.minhasInscricoes': 'Mis inscripciones',
  'painel.pesagem': 'pesaje {peso}',
  'painel.checkInFeito': 'Check-in hecho',
  'painel.nenhumaInscricao': 'Ninguna inscripción',
  'conta.conta': 'Cuenta',
  'conta.minhaConta': 'Mi cuenta',
  'conta.descricao': 'Datos de acceso, roles y vínculos de organización.',
  'conta.dados': 'Datos',
  'conta.editar': 'Editar',
  'conta.nome': 'Nombre',
  'conta.email': 'Correo electrónico',
  'conta.papelGlobal': 'Rol global',
  'conta.situacao': 'Situación',
  'conta.trocarSenha': 'Cambiar contraseña',
  'conta.organizacoes': 'Organizaciones',
  'conta.semVinculo': 'Sin vínculo',
  'conta.semVinculoDescricao': 'Los roles operativos los concede cada organización.',
  'conta.dadosAtualizados': 'Datos actualizados.',
  'conta.editarConta': 'Editar cuenta',
  'conta.senhaAlterada': 'Contraseña cambiada.',
  'conta.senhaAtual': 'Contraseña actual',
  'conta.novaSenha': 'Nueva contraseña',
  'conta.confirmarNovaSenha': 'Confirmar la nueva contraseña',
  'conta.senhasNaoCoincidem': 'Las contraseñas no coinciden',
  // Fila de solicitações de perfil de atleta, do lado da federação.
  'fila.federacao': 'Federación',
  'fila.titulo': 'Solicitudes de atletas',
  'fila.descricao': 'Solicitudes de perfil de atleta a la espera de la confirmación de la afiliación.',
  'fila.filtrarPorSituacao': 'Filtrar por situación',
  'fila.aprovadas': 'Aprobadas',
  'fila.recusadas': 'Rechazadas',
  'fila.canceladas': 'Canceladas',
  'fila.todas': 'Todas',
  'fila.solicitante': 'Solicitante',
  'fila.registro': 'Registro',
  'fila.enviadaEm': 'Enviada el',
  'fila.enviada': 'Enviada',
  'fila.acoes': 'Acciones',
  'fila.ver': 'Ver',
  'fila.verSolicitacao': 'Ver solicitud',
  'fila.aprovadaAviso': 'Solicitud aprobada. El atleta fue creado.',
  'fila.aprovadaTitulo': 'Solicitud aprobada',
  'fila.aprovadaDescricao': 'El perfil de atleta fue creado.',
  'fila.recusadaAviso': 'Solicitud rechazada.',
  'fila.recusadaTitulo': 'Solicitud rechazada',
  'fila.recusadaDescricao': 'El motivo fue registrado y enviado.',
  'fila.analisar': 'Analizar la solicitud',
  'fila.analisarDescricao': 'Confirme la afiliación antes de aprobar.',
  'fila.fotoDe': 'Foto enviada por {nome}',
  'fila.semFotoNota': 'Esta solicitud vino sin foto. La foto es opcional — compruebe la identidad con los demás datos.',
  'fila.nomeInformado': 'Nombre indicado',
  'fila.contaDoSolicitante': 'Cuenta',
  'fila.cpfApagado': 'Ya no está guardado en esta solicitud',
  'fila.nascimento': 'Nacimiento',
  'fila.cidade': 'Ciudad',
  'fila.analisadaEm': 'Analizada el',
  'fila.motivoDaRecusa': 'Motivo del rechazo',
  'fila.motivoHint': 'El solicitante ve este texto. Diga qué debe corregir.',
  'fila.oQueAprovarFaz': 'Aprobar crea el perfil de atleta de <b>{nome}</b> en <b>{entidade}</b> y vincula el CPF a la ficha. La acción queda registrada en la auditoría con su nombre.',
  'fila.pedidoProprio': 'Esta solicitud es suya.',
  'fila.pedidoProprioNota': 'Quien pide no analiza. Pídalo a otro operador de la federación.',
  'fila.jaDecidida': 'Esta solicitud ya fue {situacao}.',
  'fila.recusando': 'Rechazando…',
  'fila.confirmarRecusa': 'Confirmar el rechazo',
  'fila.recusar': 'Rechazar',
  'fila.aprovando': 'Aprobando…',
  'fila.aprovarECriar': 'Aprobar y crear el atleta',
  // MCI Messenger.
  'messenger.mensagens': 'Mensajes',
  'messenger.novaConversa': 'Nueva conversación',
  'messenger.semMensagens': 'sin mensajes',
  'messenger.nenhumaConversa': 'Ninguna conversación',
  'messenger.nenhumaConversaDescricao': 'Empiece una conversación con un atleta, coach o marca.',
  'messenger.selecioneUma': 'Seleccione una conversación para empezar.',
  'messenger.conversa': 'Conversación',
  'messenger.conversaIndividual': 'Conversación individual',
  'messenger.participantes': '{n} participantes',
  'messenger.midiaDaMensagem': 'Contenido de la mensaje',
  'messenger.mensagemApagada': 'Mensaje eliminado',
  'messenger.abrirMidia': 'Abrir el contenido ampliado',
  'messenger.reagirCom': 'Reaccionar con {emoji}',
  'messenger.apagarMensagem': 'Eliminar el mensaje',
  'messenger.falhaAoEnviar': 'No se pudo enviar',
  'messenger.enviarMidia': 'Enviar contenido',
  'messenger.escrevaUmaMensagem': 'Escriba un mensaje…',
  'messenger.mensagem': 'Mensaje',
  'messenger.enviandoMensagem': 'Enviando el mensaje',
  'messenger.enviarMensagem': 'Enviar el mensaje',
  'messenger.grupo': 'Grupo',
  'messenger.novaConversaDescricao': 'Busque por identificador o nombre visible.',
  'messenger.buscarPerfil': 'Buscar perfil…',
  'messenger.buscarPerfilRotulo': 'Buscar perfil',
  'messenger.buscar': 'Buscar',
  'messenger.selecionado': 'Seleccionado',
  'messenger.busqueParaComecar': 'Busque un perfil para empezar.',
  'messenger.nomeDoGrupo': 'Nombre del grupo',
  'messenger.exemploDeGrupo': 'Ej.: Equipo Wellness',
  'messenger.abrirConversa': 'Abrir la conversación',
  // Homologação do Overall. O texto insiste em dizer, nos três idiomas, que a
  // plataforma NÃO calcula nem escolhe o campeão: é registro de decisão alheia.
  'overall.ranking': 'Ranking',
  'overall.titulo': 'Homologación del Overall',
  'overall.descricao': 'Registro de la decisión oficial de la organización. La plataforma no calcula ni elige al campeón Overall.',
  'overall.escolhaCampeonato': 'Elija un campeonato',
  'overall.escolhaCampeonatoDescricao': 'La homologación es por campeonato y por clase absoluta.',
  'overall.semTemporada': 'Sin temporada',
  'overall.semClasseAbsoluta': 'Ninguna clase absoluta en este campeonato',
  'overall.semClasseAbsolutaDescricao': 'El título Overall es de la clase absoluta. Sin una clase marcada como absoluta, no hay nada que homologar.',
  'overall.homologado': 'Homologado',
  'overall.semHomologacao': 'Sin homologación',
  'overall.declaradoOficialmente': 'Overall declarado oficialmente',
  'overall.atletaHomologado': 'Atleta homologado',
  'overall.homologadoEm': 'homologado el {data}',
  'overall.revogar': 'Revocar',
  'overall.semResultadoPublicado': 'Sin resultado publicado',
  'overall.semResultadoDescricao': 'Los candidatos aparecen cuando se publica el resultado de esta clase.',
  'overall.colocacaoCurta': 'Col.',
  'overall.atleta': 'Atleta',
  'overall.matricula': 'Matrícula',
  'overall.filiacao': 'Afiliación',
  'overall.colocacao': 'Colocación',
  'overall.declararOverall': 'Declarar Overall',
  'overall.homologadoAviso': 'Overall homologado.',
  'overall.falhaAoHomologar': 'No se pudo homologar.',
  'overall.confiraOImpacto': 'Compruebe el impacto antes de confirmar.',
  'overall.campeonato': 'Campeonato',
  'overall.categoria': 'Categoría',
  'overall.pontosDaColocacao': 'Puntos de la colocación',
  'overall.bonusOverall': 'Bono Overall',
  'overall.totalDaParticipacao': 'Total de la participación',
  'overall.impactoNoAcumulado': 'Impacto en el acumulado',
  'overall.declaracaoOficial': 'Esta acción registra una declaración oficial de Overall.',
  'overall.naoCalculamos': 'La plataforma no calcula ni decide al campeón.',
  'overall.homologando': 'Homologando…',
  'overall.confirmarHomologacao': 'Confirmar la homologación',
  'overall.revogadaAviso': 'Homologación revocada.',
  'overall.falhaAoRevogar': 'No se pudo revocar.',
  'overall.revogarHomologacao': 'Revocar la homologación',
  'overall.revogarDescricao': 'La revocación retira el bono de +10. La colocación no se altera.',
  'overall.corrigeDecisao': 'Esto corrige una decisión oficial ya registrada.',
  'overall.motivoNaAuditoria': 'El motivo queda en la auditoría, junto con quién revocó y cuándo.',
  'overall.motivoDaRevogacao': 'Motivo de la revocación',
  'overall.exemploDeMotivo': 'Ej.: acta oficial corregida por la organización',
  'overall.revogando': 'Revocando…',
  // Lançamentos do campeonato: corrigir, invalidar, restaurar.
  'lancamento.titulo': 'Registros del campeonato',
  'lancamento.descricao': 'Corrección e invalidación de un resultado ya publicado. Todo cambio exige motivo y queda en la auditoría.',
  'lancamento.escolhaCampeonato': 'La corrección se hace con el acta del campeonato en la mano, registro por registro.',
  'lancamento.contagem': '{n} registro(s)',
  'lancamento.invalidados': '{n} invalidado(s)',
  'lancamento.nenhum': 'Ningún registro en este campeonato',
  'lancamento.nenhumDescricao': 'Los registros aparecen después de que se aplica una importación o se publica un resultado.',
  'lancamento.classe': 'Clase',
  'lancamento.pontos': 'Puntos',
  'lancamento.matricula': 'Matrícula {numero}',
  'lancamento.invalidado': 'Invalidado',
  'lancamento.valido': 'Válido',
  'lancamento.restaurar': 'Restaurar',
  'lancamento.corrigir': 'Corregir',
  'lancamento.corrigidoAviso': 'Registro corregido.',
  'lancamento.falhaAoCorrigir': 'No se pudo corregir.',
  'lancamento.corrigirLancamento': 'Corregir el registro',
  'lancamento.naoCompareceu': 'No se presentó (NS)',
  'lancamento.naoSubiuAoPalco': 'El atleta no subió al escenario en esta clase',
  'lancamento.colocacaoHint': 'La puntuación la calcula el servidor. Del 6.º en adelante vale cero.',
  'lancamento.motivoDaCorrecao': 'Motivo de la corrección',
  'lancamento.exemploCorrecao': 'Ej.: acta oficial de la organización corregida',
  'lancamento.corrigindo': 'Corrigiendo…',
  'lancamento.confirmarCorrecao': 'Confirmar la corrección',
  'lancamento.colocacaoAntes': 'Colocación antes',
  'lancamento.colocacaoDepois': 'Colocación después',
  'lancamento.pontosAntes': 'Puntos antes',
  'lancamento.pontosDepois': 'Puntos después',
  'lancamento.diferenca': 'Diferencia',
  'lancamento.invalidadoAviso': 'Registro invalidado.',
  'lancamento.falhaAoInvalidar': 'No se pudo invalidar.',
  'lancamento.invalidarLancamento': 'Invalidar el registro',
  'lancamento.naoEApagada': 'La participación NO se borra.',
  'lancamento.naoEApagadaTexto': 'Sigue en el historial del atleta valiendo cero, marcada como invalidada y con este motivo a la vista. Pierde los {pontos} punto(s) y el bono de Overall, si lo hubiera.',
  'lancamento.motivoDaInvalidacao': 'Motivo de la invalidación',
  'lancamento.exemploInvalidacao': 'Ej.: atleta descalificado por la comisión técnica',
  'lancamento.invalidando': 'Invalidando…',
  'lancamento.restauradoAviso': 'Registro restaurado.',
  'lancamento.falhaAoRestaurar': 'No se pudo restaurar.',
  'lancamento.restaurarLancamento': 'Restaurar el registro',
  'lancamento.voltaAoEstado': 'Vuelve al estado anterior a la invalidación.',
  'lancamento.voltaAoEstadoTexto': 'La colocación {colocacao} vuelve a puntuar por la tabla vigente de la temporada, y no por un total congelado en el momento de la invalidación.',
  'lancamento.invalidadoPor': 'Invalidado por: {motivo}',
  'lancamento.motivoDaRestauracao': 'Motivo de la restauración',
  'lancamento.exemploRestauracao': 'Ej.: descalificación revertida por la comisión',
  'lancamento.restaurando': 'Restaurando…',
  // Resultados. O MCI NÃO julga: a tela transcreve a colocação oficial recebida.
  'resultado.competicao': 'Competición',
  'resultado.titulo': 'Resultados',
  'resultado.descricao': 'Registro del resultado oficial recibido, publicación protegida y corrección versionada.',
  'resultado.selecioneEvento': 'Seleccione un evento',
  'resultado.porClasse': 'Resultado oficial por clase',
  'resultado.publicado': 'Publicado',
  'resultado.rascunho': 'Borrador',
  'resultado.resumoDaLinha': '{situacao} · versión {versao} · checksum {checksum}…',
  'resultado.aindaNaoRecebido': 'Resultado aún no recibido',
  'resultado.empateNaoResolvido': 'Empate no resuelto',
  'resultado.relancar': 'Volver a registrar',
  'resultado.lancarResultado': 'Registrar el resultado',
  'resultado.publicar': 'Publicar',
  'resultado.corrigir': 'Corregir',
  'resultado.versoes': 'Versiones',
  'resultado.semClasses': 'Sin clases registradas',
  'resultado.tituloOverall': 'Título Overall',
  'resultado.tituloOverallNota': 'Declarado por la organización. La plataforma registra — no decide.',
  'resultado.overallDoEvento': 'Overall del evento',
  'resultado.declaradoEm': 'declarado el {data}',
  'resultado.nenhumTitulo': 'Ningún título Overall declarado',
  'resultado.nenhumTituloDescricao': 'El Overall lo decide la comisión y se registra aquí.',
  'resultado.versaoApurada': 'Versión {versao} · calculado el {data}',
  'resultado.empateCurto': 'EMP',
  'resultado.somaBruta': 'suma {soma} · bruta {bruta} · {votos} voto(s)',
  'resultado.lancadoComEmpate': 'Resultado registrado con empate no resuelto: la publicación queda bloqueada hasta la corrección.',
  'resultado.lancadoAviso': 'Resultado oficial registrado.',
  'resultado.publicacaoTravada': 'La publicación queda bloqueada hasta que decida la comisión.',
  'resultado.lancadoTitulo': 'Resultado registrado',
  'resultado.lancarEm': 'Registrar el resultado — {classe}',
  'resultado.julgamentoExterno': 'El juzgamiento es externo. Transcriba la colocación oficial recibida; la plataforma no recalcula ni desempata.',
  'resultado.colocado': 'Colocado',
  'resultado.desclassificado': 'Descalificado',
  'resultado.ausente': 'Ausente',
  'resultado.nenhumInscrito': 'Ningún inscrito en esta clase',
  'resultado.lancarOficial': 'Registrar el resultado oficial',
  'resultado.publicadoComPontos': 'Resultado publicado. {complemento}',
  'resultado.atletasPontuaram': '{n} atleta(s) puntuaron en el ranking.',
  'resultado.semPontuacao': 'Sin puntuación de ranking (evento sin temporada).',
  'resultado.publicadoTitulo': 'Resultado publicado',
  'resultado.classificacaoPublica': 'La clasificación ahora es pública.',
  'resultado.publicarResultado': 'Publicar el resultado',
  'resultado.publicarDescricao': 'Publicar hace pública la clasificación y dispara la puntuación de ranking.',
  'resultado.motivoObservacao': 'Motivo / observación',
  'resultado.motivoHint': 'Queda registrado en la versión publicada.',
  'resultado.exemploMotivo': 'Ej.: resultado oficial verificado por la comisión técnica',
  'resultado.correcaoRegistradaAviso': 'Corrección registrada como nueva versión.',
  'resultado.correcaoRegistrada': 'Corrección registrada',
  'resultado.versaoPreservada': 'La versión anterior se conservó.',
  'resultado.corrigirResultado': 'Corregir el resultado',
  'resultado.corrigirDescricao': 'La corrección no sobrescribe: crea la versión siguiente, conserva la anterior y exige motivo.',
  'resultado.motivoDaCorrecao': 'Motivo de la corrección',
  'resultado.exemploCorrecao': 'Ej.: desempate decidido en reunión de la comisión técnica',
  'resultado.situacaoDe': 'Situación de {nome}',
  'resultado.colocacaoDe': 'Colocación de {nome}',
  'resultado.classificado': 'Clasificado',
  'resultado.colocacaoRepetida': 'Colocación repetida',
  'resultado.colocacaoRepetidaTexto': 'Dos colocaciones iguales no forman una clasificación válida.',
  'resultado.registrarCorrecao': 'Registrar la corrección',
  'resultado.historicoDeVersoes': 'Historial de versiones',
  'resultado.historicoDescricao': 'Cada cambio de estado del resultado genera una versión conservada.',
  'resultado.sistema': 'sistema',
  'resultado.semVersoes': 'Sin versiones registradas',
  'resultado.tituloDeclaradoAviso': 'Título Overall declarado. Los resultados publicados se volvieron a puntuar.',
  'resultado.campeaoOverall': 'Campeón Overall',
  'resultado.declararTitulo': 'Declarar el título Overall',
  'resultado.declararDescricao': 'La comisión decide; la plataforma registra. La declaración queda en la auditoría y vuelve a puntuar los resultados ya publicados.',
  'resultado.tituloNaoDeclarado': 'Título no declarado',
  'resultado.nadaFoiRegistrado': 'No se registró nada. Compruebe la elección e inténtelo de nuevo.',
  'resultado.somenteInscritos': 'Solo inscritos en este evento.',
  'resultado.selecione': 'Seleccione…',
  'resultado.recorte': 'Recorte',
  'resultado.recorteHint': 'Sin recorte, es el Overall de todo el evento.',
  'resultado.observacao': 'Observación',
  'resultado.observacaoHint': 'Queda registrada junto a la declaración.',
  'resultado.exemploObservacao': 'Ej.: decisión de la comisión técnica el 14/09',
  // Telas públicas: início, campeonatos, atletas e ranking.
  'publico.subtitulo': 'Gestión de competición, resultados, ranking y la comunidad del fisicoculturismo brasileño en una sola plataforma.',
  'publico.onzeCategorias': 'Once categorías oficiales',
  'publico.quemParticipa': 'Atletas, coaches, equipos y gimnasios',
  'publico.temporadasERanking': 'Temporadas y ranking nacional',
  'publico.campeonatos': 'Campeonatos',
  'publico.atletas': 'Atletas',
  'publico.atletasPro': 'Atletas PRO',
  'publico.resultadosPublicados': 'Resultados publicados',
  'publico.destinoCampeonatos': 'los campeonatos',
  'publico.destinoAtletas': 'los atletas',
  'publico.destinoRanking': 'el ranking',
  'publico.proximosCampeonatos': 'Próximos campeonatos',
  'publico.verTodos': 'Ver todos',
  'publico.localADefinir': 'Lugar por definir',
  'publico.nenhumAgendado': 'Ningún campeonato agendado',
  'publico.nenhumAgendadoDescricao': 'En cuanto se planifique una etapa, aparecerá aquí.',
  'publico.completo': 'Completo',
  'publico.geral': 'General',
  'publico.rankingEmConstrucao': 'Ranking en construcción',
  'publico.rankingEmConstrucaoDescricao': 'La puntuación aparece tras la publicación de los primeros resultados.',
  'publico.competicoes': 'Competiciones',
  'publico.etapasDoCampeonato': 'Etapas del Campeonato Brasileiro Muscle Contest.',
  'publico.buscarCampeonato': 'Buscar campeonato…',
  'publico.buscarCampeonatoRotulo': 'Buscar campeonato',
  'publico.nenhumEncontrado': 'Ningún campeonato encontrado',
  'publico.nenhumEncontradoDescricao': 'Ajuste la búsqueda para ver otras etapas.',
  'publico.proximaEtapa': 'Próxima etapa',
  'publico.descricaoPadraoDaEtapa': 'Etapa del Campeonato Brasileiro Muscle Contest.',
  'publico.voltarParaCampeonatos': '← Campeonatos',
  'publico.voltarParaAtletas': '← Atletas',
  'publico.atletasContagem': '{n} atletas',
  'publico.abaResultados': 'Resultados',
  'publico.abaCategorias': 'Categorías',
  'publico.abaAgenda': 'Agenda',
  'publico.abaPatrocinadores': 'Patrocinadores',
  'publico.publicado': 'Publicado',
  'publico.semEquipe': 'Sin equipo',
  'publico.semResultados': 'Resultados aún no publicados',
  'publico.semResultadosDescricao': 'La clasificación aparece aquí cuando la organización publique el recuento.',
  'publico.semClasses': 'Sin clases registradas',
  'publico.semDivisoes': 'Divisiones aún no registradas.',
  'publico.semCategorias': 'Categorías no definidas',
  'publico.semCategoriasDescricao': 'La organización todavía no ha montado el cuadro de categorías.',
  'publico.chamadasEBaterias': 'Llamadas y tandas',
  'publico.horarioADefinir': 'Horario por definir',
  'publico.semAgenda': 'Agenda no publicada',
  'publico.semAgendaDescricao': 'Las tandas aparecen cuando se monte el orden de escenario.',
  'publico.atletasInscritos': 'Atletas inscritos',
  'publico.semInscritos': 'Sin inscritos confirmados',
  'publico.patrocinadoresEMarcas': 'Patrocinadores y marcas',
  'publico.semPatrocinadores': 'Sin patrocinadores registrados',
  'publico.semPatrocinadoresDescricao': 'El apoyo institucional del evento aparece aquí.',
  'publico.comunidade': 'Comunidad',
  'publico.perfisPublicos': 'Perfiles públicos de los atletas de la plataforma.',
  'publico.buscarAtleta': 'Buscar por nombre o nombre deportivo…',
  'publico.buscarAtletaRotulo': 'Buscar atleta',
  'publico.nenhumAtleta': 'Ningún atleta encontrado',
  'publico.nenhumAtletaDescricao': 'Ajuste la búsqueda o espere nuevos registros.',
  'publico.semFiliacao': 'Sin afiliación',
  'publico.comCoach': 'Coach {nome}',
  'publico.semCoach': 'Sin coach',
  'publico.titulos': 'Títulos',
  'publico.temporadasNoRanking': 'Temporadas en el ranking',
  'publico.pontosSomados': 'Puntos sumados',
  'publico.historicoEsportivo': 'Historial deportivo',
  'publico.verEtapa': 'Ver la etapa',
  'publico.semResultadosDoAtleta': 'Todavía sin resultados publicados',
  'publico.participacoes': '{n} participación(es)',
  'publico.semPontuacao': 'Sin puntuación de ranking',
  'publico.abaCampeonato': 'Campeonato',
  'publico.abaSuperOverall': 'Super Overall',
  'publico.abaEquipes': 'Equipos',
  'publico.abaEmpresas': 'Empresas',
  'publico.temporada': 'Temporada',
  'publico.rankingDescricao': 'Puntuación por atleta, equipo, empresa y temporada. Cada punto es rastreable hasta su origen.',
  'publico.classificatorioAnual': 'Clasificatorio anual',
  'publico.classificatorioTexto': 'Todas las clases puntúan en el campeonato, pero solo la <b>Open</b> alimenta el Super Overall. Los números de esta pestaña no se suman a los de las otras.',
  'publico.temporadaMaisRecente': 'Temporada abierta más reciente',
  'publico.todasAsCategorias': 'Todas las categorías',
  'publico.uf': 'Estado',
  'publico.etapas': 'Etapas',
  'publico.pontos': 'Puntos',
  'publico.legendaDoRanking': 'Cada colocación vale según la tabla oficial de la temporada (1.º = 5, 2.º = 4, 3.º = 3, 4.º = 2, 5.º = 1). Cada título de <b>Overall</b> suma <b>+10</b>, una vez por campeonato — quien ganó el Overall de dos campeonatos suma +20 en la temporada.',
  'publico.rankingVazio': 'Ranking vacío',
  'publico.rankingVazioDescricao': 'La puntuación aparece cuando se publiquen o importen resultados.',
  'publico.semElegiveis': 'Ningún resultado elegible',
  'publico.semEquipes': 'Ningún equipo puntuó',
  'publico.semEmpresas': 'Ninguna empresa puntuó',
  'publico.semElegiveisDescricao': 'Solo los resultados publicados de la clase Open alimentan el clasificatorio anual.',
  'publico.semEquipesDescricao': 'El equipo puntúa por lo que consiguen sus atletas.',
  'publico.semEmpresasDescricao': 'La empresa puntúa por lo que consiguen sus equipos.',
  'publico.equipe': 'Equipo',
  'publico.empresa': 'Empresa',
  'publico.primeiroCriterio': 'Primer criterio de desempate',
  'publico.empate': 'empate',
};
