// Dicionário PT-BR — o idioma padrão, e a lista de chaves que os outros dois
// precisam cobrir inteira. `lib/idioma.test.jsx` reprova quem ficar para trás.

export default {
  'idioma.escolher': 'Idioma',
  'idioma.pt-BR': 'Português',
  'idioma.en': 'English',
  'idioma.es': 'Español',


  // Navegação. A CHAVE é a ROTA — o mesmo identificador que o roteador usa.
  // Derivar a chave do rótulo em português quebraria na primeira renomeação;
  // derivá-la da rota amarra a tradução ao destino, que é o que não muda.
  'nav.inicio': 'Início',
  'nav.campeonatos': 'Campeonatos',
  'nav.atletas': 'Atletas',
  'nav.ranking': 'Ranking',
  'nav.social': 'Social',
  'nav.messenger': 'Messenger',
  'nav.comunidades': 'Comunidades',
  'nav.meu-painel': 'Meu painel',
  'nav.minha-filiacao': 'Minha filiação',
  'nav.meu-historico': 'Meu histórico',
  'nav.admin': 'Painel',
  'nav.admin/eventos': 'Eventos',
  'nav.admin/inscricoes': 'Inscrições',
  'nav.admin/solicitacoes': 'Solicitações',
  'nav.admin/checkin': 'Check-in',
  'nav.admin/pesagem': 'Pesagem',
  'nav.admin/credenciamento': 'Credenciamento',
  'nav.admin/palco': 'Palco',
  'nav.admin/resultados': 'Resultados',
  'nav.admin/ranking': 'Ranking',
  'nav.admin/overall': 'Overall',
  'nav.admin/lancamentos': 'Lançamentos',
  'nav.admin/musclewar': 'MuscleWare',
  'nav.admin/auditoria': 'Auditoria',
  'nav.admin/configuracoes': 'Configurações',
  'grupo.plataforma': 'Plataforma',
  'grupo.administracao': 'Administração',
  'navegacao.principal': 'Navegação principal',
  'navegacao.abrirMenu': 'Abrir menu',
  'navegacao.fecharMenu': 'Fechar menu',
  'navegacao.inicio': 'Início',
  'navegacao.campeonatos': 'Campeonatos',
  'navegacao.ranking': 'Ranking',
  'navegacao.atletas': 'Atletas',
  'navegacao.inscricoes': 'Inscrições',
  'navegacao.resultados': 'Resultados',
  'navegacao.importacoes': 'Importações',
  'navegacao.solicitacoes': 'Solicitações',
  'navegacao.minhaCarreira': 'Minha carreira',
  'navegacao.configuracoes': 'Configurações',

  'topo.busca': 'Buscar',
  'topo.somLigado': 'Som ligado',
  'topo.somDesligado': 'Som desligado',
  'topo.ligarSom': 'Ligar o som do sistema',
  'topo.desligarSom': 'Desligar o som do sistema',
  'topo.notificacoes': 'Notificações',
  'topo.naoLidas': '{n} não lidas',
  'topo.meuPerfil': 'Meu perfil social',
  'topo.sair': 'Sair',

  'acao.aplicar': 'Aplicar',
  'acao.revisar': 'Revisar',
  'acao.excluir': 'Excluir',
  'acao.invalidar': 'Invalidar',
  'acao.cancelar': 'Cancelar',
  'acao.confirmar': 'Confirmar',
  'acao.salvar': 'Salvar',
  'acao.voltar': 'Voltar',
  'acao.fechar': 'Fechar',
  'acao.filtrar': 'Filtrar',
  'acao.limparFiltros': 'Limpar filtros',

  'estado.carregando': 'Carregando…',
  'estado.vazio': 'Nada por aqui ainda',
  'estado.erro': 'Não foi possível carregar',
  'estado.semPermissao': 'Você não tem permissão para ver isto',

  'pagina.anterior': 'Página anterior',
  'pagina.proxima': 'Próxima página',
  'pagina.de': 'Página {atual} de {total}',

  'ranking.geral': 'Ranking Geral',
  'ranking.superOverall': 'Super Overall',
  'ranking.equipes': 'Ranking de equipes',
  'ranking.empresas': 'Ranking de empresas',
  'ranking.pontos': 'Pontos',
  'ranking.posicao': 'Posição',
  'ranking.etapas': 'Etapas',
  'ranking.empateNaoResolvido': 'Empate não resolvido',
  'ranking.semCadastro': 'Sem cadastro no MCI',

  'importacao.resumo':
    '{n} resultados serão adicionados ao histórico/ranking. '
    + 'Os atletas ainda não cadastrados permanecerão pendentes de vínculo. '
    + 'Nenhum atleta será criado automaticamente.',
  'importacao.totalRegistros': 'Registros lidos',
  'importacao.reconhecidos': 'Reconhecidos',
  'importacao.pendentes': 'Pendentes de vínculo',
  'importacao.conflitos': 'Conflitos',
  'importacao.duplicados': 'Duplicados',
  'importacao.rejeitados': 'Rejeitados',
  'importacao.aplicaveis': 'Aplicáveis',

  'vinculo.automatico': 'Vinculado automaticamente',
  'vinculo.porCpf': 'Vinculado automaticamente por CPF',
  'vinculo.porMatricula': 'Vinculado automaticamente por filiação + matrícula',
  'vinculo.pendente': 'Pendente de vínculo',
  'vinculo.conflito': 'Conflito de identidade',
  'vinculo.naoIdentificado': 'Não identificado',

  // Tela de recuperação do limite de erro. Ela aparece JUSTAMENTE quando algo
  // quebrou — e em espanhol ou inglês continua tendo de dizer o que fazer.
  'erro.titulo': 'Esta tela parou de responder',
  'erro.explicacao': 'O restante do sistema continua funcionando. Volte ao início e tente de novo; se acontecer outra vez, avise o suporte técnico informando em qual tela ocorreu.',
  'erro.voltarAoInicio': 'Voltar ao início',
  'erro.recarregar': 'Recarregar',

  // Abertura e entrada. O NOME do campeonato não entra aqui: é dado oficial, e
  // sai como está nos três idiomas.
  'abertura.rotulo': 'Abertura do MCI Platform',
  'abertura.entrarAgora': 'Entrar agora',
  'login.entrar': 'Entrar',
  'login.semConta': 'Não tem conta?',
  'login.criarConta': 'Criar conta',

  // Busca global do topo.
  'busca.placeholder': 'Buscar atleta, evento, perfil, comunidade…',
  'busca.rotulo': 'Busca global',
  'busca.nadaEncontrado': 'Nada encontrado.',
  'busca.atleta': 'Atleta',
  'busca.campeonato': 'Campeonato',
  'busca.perfil': 'Perfil',
  'busca.comunidade': 'Comunidade',
  'abertura.ativarSom': 'Ativar experiência sonora',
  'abertura.silenciar': 'Silenciar',
  'login.email': 'Email',
  'login.senha': 'Senha',
  'estado.aguarde': 'Aguarde…',
  'busca.perfilDe': 'Perfil',
  // Blocos compartilhados de interface: esqueleto, erro, vazio, modal, toast,
  // paginação e credencial. Traduzidos num lugar só porque aparecem em todas as
  // telas — texto repetido em quinze páginas é quinze chances de divergir.
  'ui.carregando': 'Carregando',
  'ui.tentarDeNovo': 'Tentar de novo',
  'ui.vazioDescricao': 'Quando houver registro, ele aparece nesta tela.',
  'ui.midiaIndisponivel': 'Mídia indisponível.',
  'ui.imagemAmpliada': 'Imagem ampliada',
  'ui.fecharImagem': 'Fechar imagem',
  'ui.dispensar': 'Dispensar',
  'ui.carregarMais': 'Carregar mais',
  'ui.qrFalhou': 'Não foi possível desenhar o QR. O código continua legível ao lado.',
  'ui.qrDaCredencial': 'QR da credencial {valor}',
  'ui.atualizadoAgora': 'Atualizado agora',
  'ui.atualizadoMinutos': 'Atualizado há {n} min',
  'ui.atualizadoHoras': 'Atualizado há {n} h',
  // Minha filiação e meu histórico — a área do atleta sobre a própria carreira.
  // O NOME da entidade, da categoria e da classe vem do banco e não é traduzido:
  // o que traduz é o rótulo em volta.
  'carreira.meuEspaco': 'Meu espaço',
  'carreira.minhaFiliacao': 'Minha filiação',
  'carreira.minhaFiliacaoDescricao': 'A entidade pela qual você compete e o seu número de registro nela.',
  'carreira.semPerfil': 'Você ainda não tem perfil de atleta',
  'carreira.semPerfilDescricao': 'Competir exige filiação confirmada pela federação. Envie sua solicitação com CPF, entidade de filiação e número de registro — um operador analisa.',
  'carreira.semFiliacao': 'Sem filiação registrada',
  'carreira.semFiliacaoDescricao': 'Seu perfil existe em {organizacao}, mas nenhuma entidade de filiação está vinculada a ele. A federação é quem registra o vínculo e o número.',
  'carreira.suaOrganizacao': 'sua organização',
  'carreira.ativa': 'Ativa',
  'carreira.inativa': 'Inativa',
  'carreira.codigoDaEntidade': 'Código da entidade',
  'carreira.minhaMatricula': 'Minha matrícula',
  'carreira.uf': 'UF',
  'carreira.organizacaoNota': 'A entidade e o número são registrados pela federação — se algo estiver errado, fale com um operador.',
  'carreira.organizacao': 'Organização',
  'carreira.meuHistorico': 'Meu histórico',
  'carreira.meuHistoricoDescricao': 'Cada participação que pontuou, com a conta aberta: colocação, bônus de Overall e total.',
  'carreira.semPontos': 'Você ainda não pontuou',
  'carreira.semPontosDescricao': 'Assim que um resultado for publicado e a etapa estiver vinculada a uma temporada, sua participação aparece aqui.',
  'carreira.porCategoria': 'Desempenho por categoria',
  'carreira.porCategoriaNota': 'Cada categoria tem ranking próprio',
  'carreira.semCategoria': 'Sem categoria',
  'carreira.participacoesContagem': '{n} participações',
  'carreira.participacaoContagem': '{n} participação',
  'carreira.participacoes': 'Participações',
  'carreira.pontosDeColocacao': 'Pontos de colocação',
  'carreira.bonusOverall': 'Bônus Overall',
  'carreira.totalGeral': 'Total geral',
  'carreira.totalGeralNota': 'Soma de todas as categorias',
  'carreira.colunaCampeonato': 'Campeonato',
  'carreira.colunaCategoriaClasse': 'Categoria · classe',
  'carreira.colunaColocacaoCurta': 'Col.',
  'carreira.colunaColocacao': 'Colocação',
  'carreira.colunaOverall': 'Overall',
  'carreira.colunaTotal': 'Total',
  'carreira.colunaFiliacaoNaEpoca': 'Filiação na época',
  'carreira.colunaPtsColocacao': 'Pts colocação',
  'carreira.colunaCategoria': 'Categoria',
  'carreira.colunaFiliacao': 'Filiação',
  'carreira.campeaoOverall': 'Campeão Overall',
  'carreira.numeroAbreviado': 'nº {numero}',
  'carreira.filiacaoNaoRegistrada': 'não registrada',
  'carreira.rodapeContagem': 'Mostrando {mostrando} de {total} participação(ões).',
  'carreira.rodapeOverall': 'O bônus de Overall é da classe absoluta e vale uma vez por título.',
  // Mensagens de validação dos formulários. A VALIDAÇÃO devolve a CHAVE, e não
  // a frase: `lib/formulario.js` não é componente, não tem contexto de idioma, e
  // devolver português de dentro dela deixaria o erro em português numa tela em
  // espanhol. Quem traduz é quem desenha o erro na tela.
  'form.erro.nome': 'Informe seu nome completo',
  'form.erro.nomeDocumento': 'Informe o nome como consta no documento',
  'form.erro.nascimento': 'Informe uma data de nascimento válida',
  'form.erro.email': 'Informe um e-mail válido',
  'form.erro.senha': 'A senha precisa de pelo menos 8 caracteres',
  'form.erro.telefone': 'Telefone com DDD e 8 ou 9 dígitos',
  'form.erro.whatsapp': 'WhatsApp com DDD e 8 ou 9 dígitos',
  'form.erro.cep': 'CEP com 8 dígitos',
  'form.erro.endereco': 'Informe o endereço',
  'form.erro.numero': 'Informe o número',
  'form.erro.uf': 'Selecione a UF',
  'form.erro.cidade': 'Informe a cidade',
  'form.erro.cpf': 'CPF inválido',
  'form.erro.sexo': 'Selecione a categoria de competição',
  'form.erro.filiacao': 'Selecione a entidade de filiação',
  'form.erro.matricula': 'Informe o número de registro',
  // Perfis abertos no cadastro. O CÓDIGO ('ATHLETE', 'COACH'…) é o que vai para
  // a API e nunca muda; aqui traduz-se só o que a pessoa lê.
  'papel.ATHLETE': 'Atleta',
  'papel.ATHLETE.descricao': 'Compete nas etapas do Campeonato Brasileiro',
  'papel.COACH': 'Coach',
  'papel.COACH.descricao': 'Prepara e acompanha atletas',
  'papel.GYM': 'Academia',
  'papel.GYM.descricao': 'Centro de treinamento',
  'papel.TEAM': 'Equipe',
  'papel.TEAM.descricao': 'Time que reúne atletas',
  'papel.BRAND': 'Marca',
  'papel.BRAND.descricao': 'Marca do ecossistema',
  'papel.SPONSOR': 'Patrocinador',
  'papel.SPONSOR.descricao': 'Apoia atletas e etapas',
  'papel.MEDIA': 'Imprensa',
  'papel.MEDIA.descricao': 'Cobertura e conteúdo',
  // Cadastro em cinco etapas.
  'cadastro.etapa1': 'IDENTIDADE',
  'cadastro.etapa1.titulo': 'Quem é você',
  'cadastro.etapa2': 'CONTATO',
  'cadastro.etapa2.titulo': 'Como falamos com você',
  'cadastro.etapa3': 'ENDEREÇO',
  'cadastro.etapa3.titulo': 'Onde você está',
  'cadastro.etapa4': 'PERFIL ESPORTIVO',
  'cadastro.etapa4.titulo': 'O que vem depois',
  'cadastro.etapa5': 'REVISÃO',
  'cadastro.etapa5.titulo': 'Confira antes de enviar',
  'cadastro.etapaDe': 'Etapa {atual} de {total}',
  'cadastro.emailJaCadastrado': 'Este e-mail já está cadastrado',
  'cadastro.nomeCompleto': 'Nome completo',
  'cadastro.dataDeNascimento': 'Data de nascimento',
  'cadastro.voceE': 'Você é',
  'cadastro.voceEHint': 'Define como você aparece na plataforma. Não é nível de acesso.',
  'cadastro.email': 'E-mail',
  'cadastro.senha': 'Senha',
  'cadastro.senhaHint': 'Ao menos 8 caracteres.',
  'cadastro.telefone': 'Telefone',
  'cadastro.whatsapp': 'WhatsApp',
  'cadastro.mesmoNumero': 'Usar o mesmo número do telefone',
  'cadastro.cep': 'CEP',
  'cadastro.cepHint': 'Preenchemos o endereço para você.',
  'cadastro.buscandoEndereco': 'Buscando endereço…',
  'cadastro.endereco': 'Endereço',
  'cadastro.numero': 'Número',
  'cadastro.complemento': 'Complemento',
  'cadastro.cidade': 'Cidade',
  'cadastro.uf': 'UF',
  'cadastro.filiacaoTitulo': 'Sua filiação é confirmada pela federação',
  'cadastro.filiacaoTexto': 'Competir exige um vínculo que a MCI não concede sozinha: quem confirma é a federação à qual você é filiado. Por isso o seu perfil de atleta passa por uma análise — e ela só começa depois de a sua conta existir.',
  'cadastro.filiacaoProximoPasso': 'Assim que você concluir o cadastro, abriremos a página <b>Minha solicitação</b>, onde você informa <b>CPF</b>, a <b>entidade de filiação</b> e o seu <b>número de registro</b>. Um operador da federação analisa e aprova.',
  'cadastro.cpfDepois': 'O CPF não é pedido aqui de propósito: ele só é digitado depois de a sua sessão existir, e vai direto para a federação — nunca fica guardado neste navegador.',
  'cadastro.semMaisNada': 'Não precisamos de mais nada',
  'cadastro.semMaisNadaTexto': 'O perfil <b>{papel}</b> não compete nas etapas, então não pedimos CPF nem filiação — seria coletar documento de quem não vai à prova.',
  'cadastro.funcoesDeOperacao': 'Funções de operação — direção de evento, credenciamento, pesagem, palco, resultados — não são escolhidas aqui. Elas são concedidas pela organização do campeonato a uma conta que já existe.',
  'cadastro.confiraOsDados': 'Confira os dados. Você pode voltar e corrigir qualquer etapa.',
  'cadastro.jaTenhoConta': 'Já tenho conta',
  'cadastro.continuar': 'Continuar',
  'cadastro.enviando': 'Enviando…',
  'cadastro.revisaoIdentidade': 'Identidade',
  'cadastro.revisaoContato': 'Contato',
  'cadastro.revisaoEndereco': 'Endereço',
  'cadastro.revisaoNome': 'Nome',
  'cadastro.revisaoNascimento': 'Nascimento',
  'cadastro.revisaoPerfil': 'Perfil',
  'cadastro.editar': 'Editar',
  // Conferência local da foto. `lib/foto.js` devolve CHAVE e valores, pelo mesmo
  // motivo de `lib/formulario.js`: não é componente e não sabe o idioma.
  'foto.erro.semArquivo': 'Escolha uma imagem.',
  'foto.erro.tipo': 'A foto precisa ser JPG, PNG ou WebP.',
  'foto.erro.tamanho': 'A foto tem {tamanho} MB e o limite é {limite} MB.',
  'foto.erro.vazio': 'O arquivo está vazio.',
  // Solicitação de perfil de atleta.
  'solicitacao.perfilDeAtleta': 'Perfil de atleta',
  'solicitacao.minhaSolicitacao': 'Minha solicitação',
  'solicitacao.descricao': 'Competir exige filiação confirmada pela federação. Você envia os dados; um operador analisa.',
  'solicitacao.emAnalise': 'Em análise',
  'solicitacao.aprovada': 'Aprovada',
  'solicitacao.recusada': 'Recusada',
  'solicitacao.cancelada': 'Cancelada',
  'solicitacao.canceladaAviso': 'Solicitação cancelada.',
  'solicitacao.perfilAtivo': 'Perfil de atleta ativo',
  'solicitacao.jaCompete': 'Você já compete pela MCI',
  'solicitacao.jaCompeteTexto': 'Seu perfil de atleta está ativo. Para corrigir filiação, número de registro ou qualquer dado da sua ficha, fale com a sua federação — esses campos são mantidos por ela, não por esta tela.',
  'solicitacao.foiAprovada': 'Sua solicitação foi aprovada',
  'solicitacao.foiAprovadaTexto': 'A federação aprovou o seu perfil. Se ele ainda não aparece aqui, atualize a sessão.',
  'solicitacao.atualizarSessao': 'Atualizar minha sessão',
  'solicitacao.cancelarSolicitacao': 'Cancelar solicitação',
  'solicitacao.cancelarAviso': 'A solicitação sai da fila da federação e o CPF enviado é apagado. Você pode enviar outra depois.',
  'solicitacao.naFila': 'Sua solicitação está na fila da federação',
  'solicitacao.enviadaEm': 'Enviada em {data}. Um operador de',
  'solicitacao.suaFederacao': 'sua federação',
  'solicitacao.vaiAnalisar': 'vai analisar. Enquanto isso, você pode usar a plataforma normalmente.',
  'solicitacao.nome': 'Nome',
  'solicitacao.entidade': 'Entidade de filiação',
  'solicitacao.numeroDeRegistro': 'Número de registro',
  'solicitacao.cpfGuardado': 'Guardado com a federação até a análise',
  'solicitacao.fotoEnviada': 'Foto enviada',
  'solicitacao.fotoEnviadaAlt': 'Foto enviada na solicitação',
  'solicitacao.semFoto': 'Sem foto',
  'solicitacao.removerFoto': 'Remover foto',
  'solicitacao.fotoEnviadaAviso': 'Foto enviada.',
  'solicitacao.fotoRemovidaAviso': 'Foto removida.',
  'solicitacao.historico': 'Histórico',
  'solicitacao.historicoTexto': 'A fila guarda o que já aconteceu — inclusive o que foi recusado.',
  'solicitacao.motivo': 'Motivo',
  'solicitacao.fotoDePerfil': 'Foto de perfil',
  'solicitacao.fotoOpcional': 'Opcional. A federação usa a foto para confirmar sua identidade.',
  'solicitacao.previaDaFoto': 'Pré-visualização da foto escolhida: {nome}',
  'solicitacao.trocarFoto': 'Trocar foto',
  'solicitacao.escolherFoto': 'Escolher foto',
  'solicitacao.remover': 'Remover',
  'solicitacao.formatosDaFoto': 'JPG, PNG ou WebP, até 5 MB.',
  'solicitacao.solicitarPerfil': 'Solicitar perfil de atleta',
  'solicitacao.solicitarTexto': 'Estes dados vão direto para a federação que você escolher. Nada fica guardado neste navegador.',
  'solicitacao.ultimaRecusada': 'Sua última solicitação foi recusada.',
  'solicitacao.nomeHint': 'Como consta no seu documento.',
  'solicitacao.cpfHint': 'Usado para vincular seus resultados. Nunca aparece em busca pública.',
  'solicitacao.cpfSeraEnviado': 'Será enviado como {resumo}',
  'solicitacao.categoriaDeCompeticao': 'Categoria de competição',
  'solicitacao.categoriaHint': 'Define em quais categorias você pode ser inscrito.',
  'solicitacao.feminino': 'Feminino',
  'solicitacao.masculino': 'Masculino',
  'solicitacao.nascimentoHint': 'Opcional. Usada para conferir sua faixa etária.',
  'solicitacao.entidadeHint': 'A federação que confirma o seu vínculo.',
  'solicitacao.semEntidades': 'Nenhuma entidade de filiação ativa está disponível para a sua conta. Fale com a organização do campeonato.',
  'solicitacao.erroEntidades': 'Não conseguimos carregar as entidades de filiação.',
  'solicitacao.matriculaHint': 'O número que a federação lhe deu.',
  'solicitacao.avisoDeEnvio': 'Seus dados serão enviados para validação da federação.',
  'solicitacao.enviarParaAnalise': 'Enviar para análise',
  'solicitacao.enviada': 'Solicitação enviada. A federação vai analisar.',
  'solicitacao.enviadaSemFoto': 'Solicitação enviada, mas a foto não subiu: {erro} Você pode reenviá-la abaixo.',
  // Painel do atleta e conta do usuário.
  'painel.meuPainel': 'Meu painel',
  'painel.descricao': 'Inscrições, agenda, baterias, resultados, ranking e vida social.',
  'painel.semPerfilDescricao': 'Competir exige filiação confirmada pela federação. Envie sua solicitação com CPF, entidade de filiação e número de registro — um operador analisa. Enquanto isso, a área social está toda disponível.',
  'painel.irParaOFeed': 'Ir para o feed',
  'painel.semFiliacao': 'Sem filiação',
  'painel.semEquipe': 'Sem equipe',
  'painel.semAcademia': 'Sem academia',
  'painel.titulos': 'Títulos',
  'painel.inscricoes': 'Inscrições',
  'painel.publicacoes': 'Publicações',
  'painel.seguidores': '{n} seguidores',
  'painel.mensagens': 'Mensagens',
  'painel.naCaixaDeEntrada': 'na caixa de entrada',
  'painel.minhaAgenda': 'Minha agenda',
  'painel.semEventosFuturos': 'Sem eventos futuros',
  'painel.semEventosFuturosDescricao': 'Suas próximas etapas aparecem aqui.',
  'painel.minhasBaterias': 'Minhas baterias',
  'painel.horarioADefinir': 'horário a definir',
  'painel.meusResultados': 'Meus resultados',
  'painel.semResultados': 'Sem resultados publicados',
  'painel.meuRanking': 'Meu ranking',
  'painel.rankingGeral': 'Geral',
  'painel.minhasInscricoes': 'Minhas inscrições',
  'painel.pesagem': 'pesagem {peso}',
  'painel.checkInFeito': 'Check-in feito',
  'painel.nenhumaInscricao': 'Nenhuma inscrição',
  'conta.conta': 'Conta',
  'conta.minhaConta': 'Minha conta',
  'conta.descricao': 'Dados de acesso, papéis e vínculos de organização.',
  'conta.dados': 'Dados',
  'conta.editar': 'Editar',
  'conta.nome': 'Nome',
  'conta.email': 'Email',
  'conta.papelGlobal': 'Papel global',
  'conta.situacao': 'Situação',
  'conta.trocarSenha': 'Trocar senha',
  'conta.organizacoes': 'Organizações',
  'conta.semVinculo': 'Sem vínculo',
  'conta.semVinculoDescricao': 'Papéis operacionais são concedidos por organização.',
  'conta.dadosAtualizados': 'Dados atualizados.',
  'conta.editarConta': 'Editar conta',
  'conta.senhaAlterada': 'Senha alterada.',
  'conta.senhaAtual': 'Senha atual',
  'conta.novaSenha': 'Nova senha',
  'conta.confirmarNovaSenha': 'Confirmar nova senha',
  'conta.senhasNaoCoincidem': 'As senhas não coincidem',
  // Fila de solicitações de perfil de atleta, do lado da federação.
  'fila.federacao': 'Federação',
  'fila.titulo': 'Solicitações de atletas',
  'fila.descricao': 'Pedidos de perfil de atleta aguardando a confirmação da filiação.',
  'fila.filtrarPorSituacao': 'Filtrar por situação',
  'fila.aprovadas': 'Aprovadas',
  'fila.recusadas': 'Recusadas',
  'fila.canceladas': 'Canceladas',
  'fila.todas': 'Todas',
  'fila.solicitante': 'Solicitante',
  'fila.registro': 'Registro',
  'fila.enviadaEm': 'Enviada em',
  'fila.enviada': 'Enviada',
  'fila.acoes': 'Ações',
  'fila.ver': 'Ver',
  'fila.verSolicitacao': 'Ver solicitação',
  'fila.aprovadaAviso': 'Solicitação aprovada. O atleta foi criado.',
  'fila.aprovadaTitulo': 'Solicitação aprovada',
  'fila.aprovadaDescricao': 'O perfil de atleta foi criado.',
  'fila.recusadaAviso': 'Solicitação recusada.',
  'fila.recusadaTitulo': 'Solicitação recusada',
  'fila.recusadaDescricao': 'O motivo foi registrado e enviado.',
  'fila.analisar': 'Analisar solicitação',
  'fila.analisarDescricao': 'Confirme a filiação antes de aprovar.',
  'fila.fotoDe': 'Foto enviada por {nome}',
  'fila.semFotoNota': 'Este pedido veio sem foto. A foto é opcional — confira a identidade pelos demais dados.',
  'fila.nomeInformado': 'Nome informado',
  'fila.contaDoSolicitante': 'Conta',
  'fila.cpfApagado': 'Já não está guardado neste pedido',
  'fila.nascimento': 'Nascimento',
  'fila.cidade': 'Cidade',
  'fila.analisadaEm': 'Analisada em',
  'fila.motivoDaRecusa': 'Motivo da recusa',
  'fila.motivoHint': 'O solicitante vê este texto. Diga o que ele precisa corrigir.',
  'fila.oQueAprovarFaz': 'Aprovar cria o perfil de atleta de <b>{nome}</b> em <b>{entidade}</b> e vincula o CPF à ficha. A ação fica registrada em auditoria com o seu nome.',
  'fila.pedidoProprio': 'Esta solicitação é sua.',
  'fila.pedidoProprioNota': 'Quem pede não analisa. Peça a outro operador da federação.',
  'fila.jaDecidida': 'Esta solicitação já foi {situacao}.',
  'fila.recusando': 'Recusando…',
  'fila.confirmarRecusa': 'Confirmar recusa',
  'fila.recusar': 'Recusar',
  'fila.aprovando': 'Aprovando…',
  'fila.aprovarECriar': 'Aprovar e criar atleta',
  // MCI Messenger.
  'messenger.mensagens': 'Mensagens',
  'messenger.novaConversa': 'Nova conversa',
  'messenger.semMensagens': 'sem mensagens',
  'messenger.nenhumaConversa': 'Nenhuma conversa',
  'messenger.nenhumaConversaDescricao': 'Comece uma conversa com um atleta, coach ou marca.',
  'messenger.selecioneUma': 'Selecione uma conversa para começar.',
  'messenger.conversa': 'Conversa',
  'messenger.conversaIndividual': 'Conversa individual',
  'messenger.participantes': '{n} participantes',
  'messenger.midiaDaMensagem': 'Mídia da mensagem',
  'messenger.mensagemApagada': 'Mensagem apagada',
  'messenger.abrirMidia': 'Abrir mídia ampliada',
  'messenger.reagirCom': 'Reagir com {emoji}',
  'messenger.apagarMensagem': 'Apagar mensagem',
  'messenger.falhaAoEnviar': 'Não foi possível enviar',
  'messenger.enviarMidia': 'Enviar mídia',
  'messenger.escrevaUmaMensagem': 'Escreva uma mensagem…',
  'messenger.mensagem': 'Mensagem',
  'messenger.enviandoMensagem': 'Enviando mensagem',
  'messenger.enviarMensagem': 'Enviar mensagem',
  'messenger.grupo': 'Grupo',
  'messenger.novaConversaDescricao': 'Busque por identificador ou nome de exibição.',
  'messenger.buscarPerfil': 'Buscar perfil…',
  'messenger.buscarPerfilRotulo': 'Buscar perfil',
  'messenger.buscar': 'Buscar',
  'messenger.selecionado': 'Selecionado',
  'messenger.busqueParaComecar': 'Busque um perfil para começar.',
  'messenger.nomeDoGrupo': 'Nome do grupo',
  'messenger.exemploDeGrupo': 'Ex: Equipe Wellness',
  'messenger.abrirConversa': 'Abrir conversa',
  // Homologação do Overall. O texto insiste em dizer, nos três idiomas, que a
  // plataforma NÃO calcula nem escolhe o campeão: é registro de decisão alheia.
  'overall.ranking': 'Ranking',
  'overall.titulo': 'Homologação do Overall',
  'overall.descricao': 'Registro da decisão oficial da organização. A plataforma não calcula nem escolhe o campeão Overall.',
  'overall.escolhaCampeonato': 'Escolha um campeonato',
  'overall.escolhaCampeonatoDescricao': 'A homologação é por campeonato e por classe absoluta.',
  'overall.semTemporada': 'Sem temporada',
  'overall.semClasseAbsoluta': 'Nenhuma classe absoluta neste campeonato',
  'overall.semClasseAbsolutaDescricao': 'O título Overall é da classe absoluta. Sem uma classe marcada como absoluta, não há o que homologar.',
  'overall.homologado': 'Homologado',
  'overall.semHomologacao': 'Sem homologação',
  'overall.declaradoOficialmente': 'Overall declarado oficialmente',
  'overall.atletaHomologado': 'Atleta homologado',
  'overall.homologadoEm': 'homologado em {data}',
  'overall.revogar': 'Revogar',
  'overall.semResultadoPublicado': 'Sem resultado publicado',
  'overall.semResultadoDescricao': 'Os candidatos aparecem quando o resultado desta classe é publicado.',
  'overall.colocacaoCurta': 'Col.',
  'overall.atleta': 'Atleta',
  'overall.matricula': 'Matrícula',
  'overall.filiacao': 'Filiação',
  'overall.colocacao': 'Colocação',
  'overall.declararOverall': 'Declarar Overall',
  'overall.homologadoAviso': 'Overall homologado.',
  'overall.falhaAoHomologar': 'Não foi possível homologar.',
  'overall.confiraOImpacto': 'Confira o impacto antes de confirmar.',
  'overall.campeonato': 'Campeonato',
  'overall.categoria': 'Categoria',
  'overall.pontosDaColocacao': 'Pontos da colocação',
  'overall.bonusOverall': 'Bônus Overall',
  'overall.totalDaParticipacao': 'Total da participação',
  'overall.impactoNoAcumulado': 'Impacto no acumulado',
  'overall.declaracaoOficial': 'Esta ação registra uma declaração oficial de Overall.',
  'overall.naoCalculamos': 'A plataforma não calcula e não decide o campeão.',
  'overall.homologando': 'Homologando…',
  'overall.confirmarHomologacao': 'Confirmar homologação',
  'overall.revogadaAviso': 'Homologação revogada.',
  'overall.falhaAoRevogar': 'Não foi possível revogar.',
  'overall.revogarHomologacao': 'Revogar homologação',
  'overall.revogarDescricao': 'A revogação retira o bônus de +10. A colocação não é alterada.',
  'overall.corrigeDecisao': 'Isto corrige uma decisão oficial já registrada.',
  'overall.motivoNaAuditoria': 'O motivo fica na auditoria, junto de quem revogou e de quando.',
  'overall.motivoDaRevogacao': 'Motivo da revogação',
  'overall.exemploDeMotivo': 'Ex.: ata oficial corrigida pela organização',
  'overall.revogando': 'Revogando…',
};
