// Dicionário PT-BR — o idioma padrão, e a lista de chaves que os outros dois
// precisam cobrir inteira. `lib/idioma.test.jsx` reprova quem ficar para trás.

export default {
  'idioma.escolher': 'Idioma',
  'idioma.abrirMenu': 'Escolher idioma',
  'idioma.pt-BR': 'Português',
  'idioma.en': 'English',
  'idioma.es': 'Español',


  // Navegação. A CHAVE é a ROTA — o mesmo identificador que o roteador usa.
  // Derivar a chave do rótulo em português quebraria na primeira renomeação;
  // derivá-la da rota amarra a tradução ao destino, que é o que não muda.
  'nav.inicio': 'Início',
  'nav.campeonatos': 'Campeonatos',
  'nav.atletas': 'Atletas',
  'nav.ranking': 'Ranking',
  'nav.social': 'Social',
  'nav.messenger': 'Messenger',
  'nav.comunidades': 'Comunidades',
  'nav.meu-painel': 'Meu painel',
  'nav.minha-filiacao': 'Minha filiação',
  'nav.meu-historico': 'Meu histórico',
  'nav.admin': 'Painel',
  'nav.admin/eventos': 'Eventos',
  'nav.admin/inscricoes': 'Inscrições',
  'nav.admin/solicitacoes': 'Solicitações',
  'nav.admin/atletas': 'Atletas',
  'nav.admin/checkin': 'Check-in',
  'nav.admin/pesagem': 'Pesagem',
  'nav.admin/credenciamento': 'Credenciamento',
  'nav.admin/palco': 'Palco',
  'nav.admin/resultados': 'Resultados',
  'nav.admin/ranking': 'Ranking',
  'nav.admin/overall': 'Overall',
  'nav.admin/lancamentos': 'Lançamentos',
  'nav.admin/musclewar': 'MuscleWare',
  'nav.admin/auditoria': 'Auditoria',
  'nav.admin/configuracoes': 'Configurações',
  'grupo.plataforma': 'Plataforma',
  'grupo.administracao': 'Administração',
  'navegacao.principal': 'Navegação principal',
  'navegacao.abrirMenu': 'Abrir menu',
  'navegacao.fecharMenu': 'Fechar menu',
  'navegacao.inicio': 'Início',
  'navegacao.campeonatos': 'Campeonatos',
  'navegacao.ranking': 'Ranking',
  'navegacao.atletas': 'Atletas',
  'navegacao.inscricoes': 'Inscrições',
  'navegacao.resultados': 'Resultados',
  'navegacao.importacoes': 'Importações',
  'navegacao.solicitacoes': 'Solicitações',
  'navegacao.minhaCarreira': 'Minha carreira',
  'navegacao.configuracoes': 'Configurações',

  'topo.busca': 'Buscar',
  'topo.somLigado': 'Som ligado',
  'topo.somDesligado': 'Som desligado',
  'topo.ligarSom': 'Ligar o som do sistema',
  'topo.desligarSom': 'Desligar o som do sistema',
  'topo.notificacoes': 'Notificações',
  'topo.naoLidas': '{n} não lidas',
  'topo.meuPerfil': 'Meu perfil social',
  'topo.sair': 'Sair',

  'acao.aplicar': 'Aplicar',
  'acao.revisar': 'Revisar',
  'acao.excluir': 'Excluir',
  'acao.invalidar': 'Invalidar',
  'acao.cancelar': 'Cancelar',
  'acao.confirmar': 'Confirmar',
  'acao.salvar': 'Salvar',
  'acao.voltar': 'Voltar',
  'acao.fechar': 'Fechar',
  'acao.filtrar': 'Filtrar',
  'acao.limparFiltros': 'Limpar filtros',

  'estado.carregando': 'Carregando…',
  'estado.vazio': 'Nada por aqui ainda',
  'estado.erro': 'Não foi possível carregar',
  'estado.semPermissao': 'Você não tem permissão para ver isto',

  'pagina.anterior': 'Página anterior',
  'pagina.proxima': 'Próxima página',
  'pagina.de': 'Página {atual} de {total}',

  'ranking.geral': 'Ranking Geral',
  'ranking.superOverall': 'Super Overall',
  'ranking.equipes': 'Ranking de equipes',
  'ranking.empresas': 'Ranking de empresas',
  'ranking.pontos': 'Pontos',
  'ranking.posicao': 'Posição',
  'ranking.etapas': 'Etapas',
  'ranking.empateNaoResolvido': 'Empate não resolvido',
  'ranking.semCadastro': 'Sem cadastro no MCI',

  'importacao.resumo':
    '{n} resultados serão adicionados ao histórico/ranking. '
    + 'Os atletas ainda não cadastrados permanecerão pendentes de vínculo. '
    + 'Nenhum atleta será criado automaticamente.',
  'importacao.totalRegistros': 'Registros lidos',
  'importacao.reconhecidos': 'Reconhecidos',
  'importacao.pendentes': 'Pendentes de vínculo',
  'importacao.conflitos': 'Conflitos',
  'importacao.duplicados': 'Duplicados',
  'importacao.rejeitados': 'Rejeitados',
  'importacao.aplicaveis': 'Aplicáveis',

  'vinculo.automatico': 'Vinculado automaticamente',
  'vinculo.porCpf': 'Vinculado automaticamente por CPF',
  'vinculo.porMatricula': 'Vinculado automaticamente por filiação + matrícula',
  'vinculo.pendente': 'Pendente de vínculo',
  'vinculo.conflito': 'Conflito de identidade',
  'vinculo.naoIdentificado': 'Não identificado',

  // Tela de recuperação do limite de erro. Ela aparece JUSTAMENTE quando algo
  // quebrou — e em espanhol ou inglês continua tendo de dizer o que fazer.
  'erro.titulo': 'Esta tela parou de responder',
  'erro.explicacao': 'O restante do sistema continua funcionando. Volte ao início e tente de novo; se acontecer outra vez, avise o suporte técnico informando em qual tela ocorreu.',
  'erro.voltarAoInicio': 'Voltar ao início',
  'erro.recarregar': 'Recarregar',

  // Abertura e entrada. O NOME do campeonato não entra aqui: é dado oficial, e
  // sai como está nos três idiomas.
  'abertura.rotulo': 'Abertura do MCI Platform',
  'abertura.entrarAgora': 'Entrar agora',
  'login.entrar': 'Entrar',
  'login.semConta': 'Não tem conta?',
  'login.criarConta': 'Criar conta',

  // Busca global do topo.
  'busca.placeholder': 'Buscar atleta, evento, perfil, comunidade…',
  'busca.rotulo': 'Busca global',
  'busca.abrir': 'Abrir busca',
  'busca.fechar': 'Fechar busca',
  'busca.nadaEncontrado': 'Nada encontrado.',
  'busca.atleta': 'Atleta',
  'busca.campeonato': 'Campeonato',
  'busca.perfil': 'Perfil',
  'busca.comunidade': 'Comunidade',
  'abertura.ativarSom': 'Ativar experiência sonora',
  'abertura.silenciar': 'Silenciar',
  'login.email': 'Email',
  'login.senha': 'Senha',
  'estado.aguarde': 'Aguarde…',
  'busca.perfilDe': 'Perfil',
  // Blocos compartilhados de interface: esqueleto, erro, vazio, modal, toast,
  // paginação e credencial. Traduzidos num lugar só porque aparecem em todas as
  // telas — texto repetido em quinze páginas é quinze chances de divergir.
  'ui.carregando': 'Carregando',
  'ui.tentarDeNovo': 'Tentar de novo',
  'ui.vazioDescricao': 'Quando houver registro, ele aparece nesta tela.',
  'ui.midiaIndisponivel': 'Mídia indisponível.',
  'ui.imagemAmpliada': 'Imagem ampliada',
  'ui.fecharImagem': 'Fechar imagem',
  'ui.dispensar': 'Dispensar',
  'ui.carregarMais': 'Carregar mais',
  'ui.qrFalhou': 'Não foi possível desenhar o QR. O código continua legível ao lado.',
  'ui.qrDaCredencial': 'QR da credencial {valor}',
  'ui.atualizadoAgora': 'Atualizado agora',
  'ui.atualizadoMinutos': 'Atualizado há {n} min',
  'ui.atualizadoHoras': 'Atualizado há {n} h',
  // Minha filiação e meu histórico — a área do atleta sobre a própria carreira.
  // O NOME da entidade, da categoria e da classe vem do banco e não é traduzido:
  // o que traduz é o rótulo em volta.
  'carreira.meuEspaco': 'Meu espaço',
  'carreira.minhaFiliacao': 'Minha filiação',
  'carreira.minhaFiliacaoDescricao': 'A entidade pela qual você compete e o seu número de registro nela.',
  'carreira.semPerfil': 'Você ainda não tem perfil de atleta',
  'carreira.semPerfilDescricao': 'Competir exige filiação confirmada pela federação. Envie sua solicitação com CPF, entidade de filiação e número de registro — um operador analisa.',
  'carreira.semFiliacao': 'Sem filiação registrada',
  'carreira.semFiliacaoDescricao': 'Seu perfil existe em {organizacao}, mas nenhuma entidade de filiação está vinculada a ele. A federação é quem registra o vínculo e o número.',
  'carreira.suaOrganizacao': 'sua organização',
  'carreira.ativa': 'Ativa',
  'carreira.inativa': 'Inativa',
  'carreira.codigoDaEntidade': 'Código da entidade',
  'carreira.minhaMatricula': 'Minha matrícula',
  'carreira.uf': 'UF',
  'carreira.organizacaoNota': 'A entidade e o número são registrados pela federação — se algo estiver errado, fale com um operador.',
  'carreira.organizacao': 'Organização',
  'carreira.meuHistorico': 'Meu histórico',
  'carreira.meuHistoricoDescricao': 'Cada participação que pontuou, com a conta aberta: colocação, bônus de Overall e total.',
  'carreira.semPontos': 'Você ainda não pontuou',
  'carreira.semPontosDescricao': 'Assim que um resultado for publicado e a etapa estiver vinculada a uma temporada, sua participação aparece aqui.',
  'carreira.porCategoria': 'Desempenho por categoria',
  'carreira.porCategoriaNota': 'Cada categoria tem ranking próprio',
  'carreira.semCategoria': 'Sem categoria',
  'carreira.participacoesContagem': '{n} participações',
  'carreira.participacaoContagem': '{n} participação',
  'carreira.participacoes': 'Participações',
  'carreira.pontosDeColocacao': 'Pontos de colocação',
  'carreira.bonusOverall': 'Bônus Overall',
  'carreira.totalGeral': 'Total geral',
  'carreira.totalGeralNota': 'Soma de todas as categorias',
  'carreira.colunaCampeonato': 'Campeonato',
  'carreira.colunaCategoriaClasse': 'Categoria · classe',
  'carreira.colunaColocacaoCurta': 'Col.',
  'carreira.colunaColocacao': 'Colocação',
  'carreira.colunaOverall': 'Overall',
  'carreira.colunaTotal': 'Total',
  'carreira.colunaFiliacaoNaEpoca': 'Filiação na época',
  'carreira.colunaPtsColocacao': 'Pts colocação',
  'carreira.colunaCategoria': 'Categoria',
  'carreira.colunaFiliacao': 'Filiação',
  'carreira.campeaoOverall': 'Campeão Overall',
  'carreira.numeroAbreviado': 'nº {numero}',
  'carreira.filiacaoNaoRegistrada': 'não registrada',
  'carreira.rodapeContagem': 'Mostrando {mostrando} de {total} participação(ões).',
  'carreira.rodapeOverall': 'O bônus de Overall é da classe absoluta e vale uma vez por título.',
  // Mensagens de validação dos formulários. A VALIDAÇÃO devolve a CHAVE, e não
  // a frase: `lib/formulario.js` não é componente, não tem contexto de idioma, e
  // devolver português de dentro dela deixaria o erro em português numa tela em
  // espanhol. Quem traduz é quem desenha o erro na tela.
  'form.erro.nome': 'Informe seu nome completo',
  'form.erro.nomeDocumento': 'Informe o nome como consta no documento',
  'form.erro.nascimento': 'Informe uma data de nascimento válida',
  'form.erro.email': 'Informe um e-mail válido',
  'form.erro.senha': 'A senha precisa de pelo menos 8 caracteres',
  'form.erro.telefone': 'Telefone com DDD e 8 ou 9 dígitos',
  'form.erro.whatsapp': 'WhatsApp com DDD e 8 ou 9 dígitos',
  'form.erro.cep': 'CEP com 8 dígitos',
  'form.erro.endereco': 'Informe o endereço',
  'form.erro.numero': 'Informe o número',
  'form.erro.uf': 'Selecione a UF',
  'form.erro.cidade': 'Informe a cidade',
  'form.erro.cpf': 'CPF inválido',
  'form.erro.sexo': 'Selecione a categoria de competição',
  'form.erro.filiacao': 'Selecione a entidade de filiação',
  'form.erro.matricula': 'Informe o número de registro',
  // Perfis abertos no cadastro. O CÓDIGO ('ATHLETE', 'COACH'…) é o que vai para
  // a API e nunca muda; aqui traduz-se só o que a pessoa lê.
  'papel.ATHLETE': 'Atleta',
  'papel.ATHLETE.descricao': 'Compete nas etapas do Campeonato Brasileiro',
  'papel.COACH': 'Coach',
  'papel.COACH.descricao': 'Prepara e acompanha atletas',
  'papel.GYM': 'Academia',
  'papel.GYM.descricao': 'Centro de treinamento',
  'papel.TEAM': 'Equipe',
  'papel.TEAM.descricao': 'Time que reúne atletas',
  'papel.BRAND': 'Marca',
  'papel.BRAND.descricao': 'Marca do ecossistema',
  'papel.SPONSOR': 'Patrocinador',
  'papel.SPONSOR.descricao': 'Apoia atletas e etapas',
  'papel.MEDIA': 'Imprensa',
  'papel.MEDIA.descricao': 'Cobertura e conteúdo',
  // Cadastro em cinco etapas.
  'cadastro.etapa1': 'IDENTIDADE',
  'cadastro.etapa1.titulo': 'Quem é você',
  'cadastro.etapa2': 'CONTATO',
  'cadastro.etapa2.titulo': 'Como falamos com você',
  'cadastro.etapa3': 'ENDEREÇO',
  'cadastro.etapa3.titulo': 'Onde você está',
  'cadastro.etapa4': 'PERFIL ESPORTIVO',
  'cadastro.etapa4.titulo': 'O que vem depois',
  'cadastro.etapa5': 'REVISÃO',
  'cadastro.etapa5.titulo': 'Confira antes de enviar',
  'cadastro.etapaDe': 'Etapa {atual} de {total}',
  'cadastro.emailJaCadastrado': 'Este e-mail já está cadastrado',
  'cadastro.nomeCompleto': 'Nome completo',
  'cadastro.dataDeNascimento': 'Data de nascimento',
  'cadastro.voceE': 'Você é',
  'cadastro.voceEHint': 'Define como você aparece na plataforma. Não é nível de acesso.',
  'cadastro.email': 'E-mail',
  'cadastro.senha': 'Senha',
  'cadastro.senhaHint': 'Ao menos 8 caracteres.',
  'cadastro.telefone': 'Telefone',
  'cadastro.whatsapp': 'WhatsApp',
  'cadastro.mesmoNumero': 'Usar o mesmo número do telefone',
  'cadastro.cep': 'CEP',
  'cadastro.cepHint': 'Preenchemos o endereço para você.',
  'cadastro.buscandoEndereco': 'Buscando endereço…',
  'cadastro.endereco': 'Endereço',
  'cadastro.numero': 'Número',
  'cadastro.complemento': 'Complemento',
  'cadastro.cidade': 'Cidade',
  'cadastro.uf': 'UF',
  'cadastro.filiacaoTitulo': 'Sua filiação é confirmada pela federação',
  'cadastro.filiacaoTexto': 'Competir exige um vínculo que a MCI não concede sozinha: quem confirma é a federação à qual você é filiado. Por isso o seu perfil de atleta passa por uma análise — e ela só começa depois de a sua conta existir.',
  'cadastro.filiacaoProximoPasso': 'Assim que você concluir o cadastro, abriremos a página <b>Minha solicitação</b>, onde você informa <b>CPF</b>, a <b>entidade de filiação</b> e o seu <b>número de registro</b>. Um operador da federação analisa e aprova.',
  'cadastro.cpfDepois': 'O CPF não é pedido aqui de propósito: ele só é digitado depois de a sua sessão existir, e vai direto para a federação — nunca fica guardado neste navegador.',
  'cadastro.semMaisNada': 'Não precisamos de mais nada',
  'cadastro.semMaisNadaTexto': 'O perfil <b>{papel}</b> não compete nas etapas, então não pedimos CPF nem filiação — seria coletar documento de quem não vai à prova.',
  'cadastro.funcoesDeOperacao': 'Funções de operação — direção de evento, credenciamento, pesagem, palco, resultados — não são escolhidas aqui. Elas são concedidas pela organização do campeonato a uma conta que já existe.',
  'cadastro.confiraOsDados': 'Confira os dados. Você pode voltar e corrigir qualquer etapa.',
  'cadastro.jaTenhoConta': 'Já tenho conta',
  'cadastro.continuar': 'Continuar',
  'cadastro.enviando': 'Enviando…',
  'cadastro.revisaoIdentidade': 'Identidade',
  'cadastro.revisaoContato': 'Contato',
  'cadastro.revisaoEndereco': 'Endereço',
  'cadastro.revisaoNome': 'Nome',
  'cadastro.revisaoNascimento': 'Nascimento',
  'cadastro.revisaoPerfil': 'Perfil',
  'cadastro.editar': 'Editar',
  // Conferência local da foto. `lib/foto.js` devolve CHAVE e valores, pelo mesmo
  // motivo de `lib/formulario.js`: não é componente e não sabe o idioma.
  'foto.erro.semArquivo': 'Escolha uma imagem.',
  'foto.erro.tipo': 'A foto precisa ser JPG, PNG ou WebP.',
  'foto.erro.tamanho': 'A foto tem {tamanho} MB e o limite é {limite} MB.',
  'foto.erro.vazio': 'O arquivo está vazio.',
  // Solicitação de perfil de atleta.
  'solicitacao.perfilDeAtleta': 'Perfil de atleta',
  'solicitacao.minhaSolicitacao': 'Minha solicitação',
  'solicitacao.descricao': 'Competir exige filiação confirmada pela federação. Você envia os dados; um operador analisa.',
  'solicitacao.emAnalise': 'Em análise',
  'solicitacao.aprovada': 'Aprovada',
  'solicitacao.recusada': 'Recusada',
  'solicitacao.cancelada': 'Cancelada',
  'solicitacao.canceladaAviso': 'Solicitação cancelada.',
  'solicitacao.perfilAtivo': 'Perfil de atleta ativo',
  'solicitacao.jaCompete': 'Você já compete pela MCI',
  'solicitacao.jaCompeteTexto': 'Seu perfil de atleta está ativo. Para corrigir filiação, número de registro ou qualquer dado da sua ficha, fale com a sua federação — esses campos são mantidos por ela, não por esta tela.',
  'solicitacao.foiAprovada': 'Sua solicitação foi aprovada',
  'solicitacao.foiAprovadaTexto': 'A federação aprovou o seu perfil. Se ele ainda não aparece aqui, atualize a sessão.',
  'solicitacao.atualizarSessao': 'Atualizar minha sessão',
  'solicitacao.cancelarSolicitacao': 'Cancelar solicitação',
  'solicitacao.cancelarAviso': 'A solicitação sai da fila da federação e o CPF enviado é apagado. Você pode enviar outra depois.',
  'solicitacao.naFila': 'Sua solicitação está na fila da federação',
  'solicitacao.enviadaEm': 'Enviada em {data}. Um operador de',
  'solicitacao.suaFederacao': 'sua federação',
  'solicitacao.vaiAnalisar': 'vai analisar. Enquanto isso, você pode usar a plataforma normalmente.',
  'solicitacao.nome': 'Nome',
  'solicitacao.entidade': 'Entidade de filiação',
  'solicitacao.numeroDeRegistro': 'Número de registro',
  'solicitacao.cpfGuardado': 'Guardado com a federação até a análise',
  'solicitacao.fotoEnviada': 'Foto enviada',
  'solicitacao.fotoEnviadaAlt': 'Foto enviada na solicitação',
  'solicitacao.semFoto': 'Sem foto',
  'solicitacao.removerFoto': 'Remover foto',
  'solicitacao.fotoEnviadaAviso': 'Foto enviada.',
  'solicitacao.fotoRemovidaAviso': 'Foto removida.',
  'solicitacao.historico': 'Histórico',
  'solicitacao.historicoTexto': 'A fila guarda o que já aconteceu — inclusive o que foi recusado.',
  'solicitacao.motivo': 'Motivo',
  'solicitacao.fotoDePerfil': 'Foto de perfil',
  'solicitacao.fotoOpcional': 'Opcional. A federação usa a foto para confirmar sua identidade.',
  'solicitacao.previaDaFoto': 'Pré-visualização da foto escolhida: {nome}',
  'solicitacao.trocarFoto': 'Trocar foto',
  'solicitacao.escolherFoto': 'Escolher foto',
  'solicitacao.remover': 'Remover',
  'solicitacao.formatosDaFoto': 'JPG, PNG ou WebP, até 5 MB.',
  'solicitacao.solicitarPerfil': 'Solicitar perfil de atleta',
  'solicitacao.solicitarTexto': 'Estes dados vão direto para a federação que você escolher. Nada fica guardado neste navegador.',
  'solicitacao.ultimaRecusada': 'Sua última solicitação foi recusada.',
  'solicitacao.nomeHint': 'Como consta no seu documento.',
  'solicitacao.cpfHint': 'Usado para vincular seus resultados. Nunca aparece em busca pública.',
  'solicitacao.cpfSeraEnviado': 'Será enviado como {resumo}',
  'solicitacao.categoriaDeCompeticao': 'Categoria de competição',
  'solicitacao.categoriaHint': 'Define em quais categorias você pode ser inscrito.',
  'solicitacao.feminino': 'Feminino',
  'solicitacao.masculino': 'Masculino',
  'solicitacao.nascimentoHint': 'Opcional. Usada para conferir sua faixa etária.',
  'solicitacao.entidadeHint': 'A federação que confirma o seu vínculo.',
  'solicitacao.semEntidades': 'Nenhuma entidade de filiação ativa está disponível para a sua conta. Fale com a organização do campeonato.',
  'solicitacao.erroEntidades': 'Não conseguimos carregar as entidades de filiação.',
  'solicitacao.matriculaHint': 'O número que a federação lhe deu.',
  'solicitacao.avisoDeEnvio': 'Seus dados serão enviados para validação da federação.',
  'solicitacao.enviarParaAnalise': 'Enviar para análise',
  'solicitacao.enviada': 'Solicitação enviada. A federação vai analisar.',
  'solicitacao.enviadaSemFoto': 'Solicitação enviada, mas a foto não subiu: {erro} Você pode reenviá-la abaixo.',
  // Painel do atleta e conta do usuário.
  'painel.meuPainel': 'Meu painel',
  'painel.descricao': 'Inscrições, agenda, baterias, resultados, ranking e vida social.',
  'painel.semPerfilDescricao': 'Competir exige filiação confirmada pela federação. Envie sua solicitação com CPF, entidade de filiação e número de registro — um operador analisa. Enquanto isso, a área social está toda disponível.',
  'painel.irParaOFeed': 'Ir para o feed',
  'painel.semFiliacao': 'Sem filiação',
  'painel.semEquipe': 'Sem equipe',
  'painel.semAcademia': 'Sem academia',
  'painel.titulos': 'Títulos',
  'painel.inscricoes': 'Inscrições',
  'painel.publicacoes': 'Publicações',
  'painel.seguidores': '{n} seguidores',
  'painel.mensagens': 'Mensagens',
  'painel.naCaixaDeEntrada': 'na caixa de entrada',
  'painel.minhaAgenda': 'Minha agenda',
  'painel.semEventosFuturos': 'Sem eventos futuros',
  'painel.semEventosFuturosDescricao': 'Suas próximas etapas aparecem aqui.',
  'painel.minhasBaterias': 'Minhas baterias',
  'painel.horarioADefinir': 'horário a definir',
  'painel.meusResultados': 'Meus resultados',
  'painel.semResultados': 'Sem resultados publicados',
  'painel.meuRanking': 'Meu ranking',
  'painel.rankingGeral': 'Geral',
  'painel.minhasInscricoes': 'Minhas inscrições',
  'painel.pesagem': 'pesagem {peso}',
  'painel.checkInFeito': 'Check-in feito',
  'painel.nenhumaInscricao': 'Nenhuma inscrição',
  'conta.conta': 'Conta',
  'conta.minhaConta': 'Minha conta',
  'conta.descricao': 'Dados de acesso, papéis e vínculos de organização.',
  'conta.dados': 'Dados',
  'conta.editar': 'Editar',
  'conta.nome': 'Nome',
  'conta.email': 'Email',
  'conta.papelGlobal': 'Papel global',
  'conta.situacao': 'Situação',
  'conta.trocarSenha': 'Trocar senha',
  'conta.organizacoes': 'Organizações',
  'conta.semVinculo': 'Sem vínculo',
  'conta.semVinculoDescricao': 'Papéis operacionais são concedidos por organização.',
  'conta.dadosAtualizados': 'Dados atualizados.',
  'conta.editarConta': 'Editar conta',
  'conta.senhaAlterada': 'Senha alterada.',
  'conta.senhaAtual': 'Senha atual',
  'conta.novaSenha': 'Nova senha',
  'conta.confirmarNovaSenha': 'Confirmar nova senha',
  'conta.senhasNaoCoincidem': 'As senhas não coincidem',
  // Fila de solicitações de perfil de atleta, do lado da federação.
  'fila.federacao': 'Federação',
  'fila.titulo': 'Solicitações de atletas',
  'fila.descricao': 'Pedidos de perfil de atleta aguardando a confirmação da filiação.',
  'fila.filtrarPorSituacao': 'Filtrar por situação',
  'fila.aprovadas': 'Aprovadas',
  'fila.recusadas': 'Recusadas',
  'fila.canceladas': 'Canceladas',
  'fila.todas': 'Todas',
  'fila.solicitante': 'Solicitante',
  'fila.registro': 'Registro',
  'fila.enviadaEm': 'Enviada em',
  'fila.enviada': 'Enviada',
  'fila.acoes': 'Ações',
  'fila.ver': 'Ver',
  'fila.verSolicitacao': 'Ver solicitação',
  'fila.aprovadaAviso': 'Solicitação aprovada. O atleta foi criado.',
  'fila.aprovadaTitulo': 'Solicitação aprovada',
  'fila.aprovadaDescricao': 'O perfil de atleta foi criado.',
  'fila.recusadaAviso': 'Solicitação recusada.',
  'fila.recusadaTitulo': 'Solicitação recusada',
  'fila.recusadaDescricao': 'O motivo foi registrado e enviado.',
  'fila.analisar': 'Analisar solicitação',
  'fila.analisarDescricao': 'Confirme a filiação antes de aprovar.',
  'fila.fotoDe': 'Foto enviada por {nome}',
  'fila.semFotoNota': 'Este pedido veio sem foto. A foto é opcional — confira a identidade pelos demais dados.',
  'fila.nomeInformado': 'Nome informado',
  'fila.contaDoSolicitante': 'Conta',
  'fila.cpfApagado': 'Já não está guardado neste pedido',
  'fila.nascimento': 'Nascimento',
  'fila.cidade': 'Cidade',
  'fila.analisadaEm': 'Analisada em',
  'fila.motivoDaRecusa': 'Motivo da recusa',
  'fila.motivoHint': 'O solicitante vê este texto. Diga o que ele precisa corrigir.',
  'fila.oQueAprovarFaz': 'Aprovar cria o perfil de atleta de <b>{nome}</b> em <b>{entidade}</b> e vincula o CPF à ficha. A ação fica registrada em auditoria com o seu nome.',
  'fila.pedidoProprio': 'Esta solicitação é sua.',
  'fila.pedidoProprioNota': 'Quem pede não analisa. Peça a outro operador da federação.',
  'fila.jaDecidida': 'Esta solicitação já foi {situacao}.',
  'fila.recusando': 'Recusando…',
  'fila.confirmarRecusa': 'Confirmar recusa',
  'fila.recusar': 'Recusar',
  'fila.aprovando': 'Aprovando…',
  'fila.aprovarECriar': 'Aprovar e criar atleta',
  // MCI Messenger.
  'messenger.mensagens': 'Mensagens',
  'messenger.novaConversa': 'Nova conversa',
  'messenger.semMensagens': 'sem mensagens',
  'messenger.nenhumaConversa': 'Nenhuma conversa',
  'messenger.nenhumaConversaDescricao': 'Comece uma conversa com um atleta, coach ou marca.',
  'messenger.selecioneUma': 'Selecione uma conversa para começar.',
  'messenger.conversa': 'Conversa',
  'messenger.conversaIndividual': 'Conversa individual',
  'messenger.participantes': '{n} participantes',
  'messenger.midiaDaMensagem': 'Mídia da mensagem',
  'messenger.mensagemApagada': 'Mensagem apagada',
  'messenger.abrirMidia': 'Abrir mídia ampliada',
  'messenger.reagirCom': 'Reagir com {emoji}',
  'messenger.apagarMensagem': 'Apagar mensagem',
  'messenger.falhaAoEnviar': 'Não foi possível enviar',
  'messenger.enviarMidia': 'Enviar mídia',
  'messenger.escrevaUmaMensagem': 'Escreva uma mensagem…',
  'messenger.mensagem': 'Mensagem',
  'messenger.enviandoMensagem': 'Enviando mensagem',
  'messenger.enviarMensagem': 'Enviar mensagem',
  'messenger.grupo': 'Grupo',
  'messenger.novaConversaDescricao': 'Busque por identificador ou nome de exibição.',
  'messenger.buscarPerfil': 'Buscar perfil…',
  'messenger.buscarPerfilRotulo': 'Buscar perfil',
  'messenger.buscar': 'Buscar',
  'messenger.selecionado': 'Selecionado',
  'messenger.busqueParaComecar': 'Busque um perfil para começar.',
  'messenger.nomeDoGrupo': 'Nome do grupo',
  'messenger.exemploDeGrupo': 'Ex: Equipe Wellness',
  'messenger.abrirConversa': 'Abrir conversa',
  // Homologação do Overall. O texto insiste em dizer, nos três idiomas, que a
  // plataforma NÃO calcula nem escolhe o campeão: é registro de decisão alheia.
  'overall.ranking': 'Ranking',
  'overall.titulo': 'Homologação do Overall',
  'overall.descricao': 'Registro da decisão oficial da organização. A plataforma não calcula nem escolhe o campeão Overall.',
  'overall.escolhaCampeonato': 'Escolha um campeonato',
  'overall.escolhaCampeonatoDescricao': 'A homologação é por campeonato e por classe absoluta.',
  'overall.semTemporada': 'Sem temporada',
  'overall.semClasseAbsoluta': 'Nenhuma classe absoluta neste campeonato',
  'overall.semClasseAbsolutaDescricao': 'O título Overall é da classe absoluta. Sem uma classe marcada como absoluta, não há o que homologar.',
  'overall.homologado': 'Homologado',
  'overall.semHomologacao': 'Sem homologação',
  'overall.declaradoOficialmente': 'Overall declarado oficialmente',
  'overall.atletaHomologado': 'Atleta homologado',
  'overall.homologadoEm': 'homologado em {data}',
  'overall.revogar': 'Revogar',
  'overall.semResultadoPublicado': 'Sem resultado publicado',
  'overall.semResultadoDescricao': 'Os candidatos aparecem quando o resultado desta classe é publicado.',
  'overall.colocacaoCurta': 'Col.',
  'overall.atleta': 'Atleta',
  'overall.matricula': 'Matrícula',
  'overall.filiacao': 'Filiação',
  'overall.colocacao': 'Colocação',
  'overall.declararOverall': 'Declarar Overall',
  'overall.homologadoAviso': 'Overall homologado.',
  'overall.falhaAoHomologar': 'Não foi possível homologar.',
  'overall.confiraOImpacto': 'Confira o impacto antes de confirmar.',
  'overall.campeonato': 'Campeonato',
  'overall.categoria': 'Categoria',
  'overall.pontosDaColocacao': 'Pontos da colocação',
  'overall.bonusOverall': 'Bônus Overall',
  'overall.totalDaParticipacao': 'Total da participação',
  'overall.impactoNoAcumulado': 'Impacto no acumulado',
  'overall.declaracaoOficial': 'Esta ação registra uma declaração oficial de Overall.',
  'overall.naoCalculamos': 'A plataforma não calcula e não decide o campeão.',
  'overall.homologando': 'Homologando…',
  'overall.confirmarHomologacao': 'Confirmar homologação',
  'overall.revogadaAviso': 'Homologação revogada.',
  'overall.falhaAoRevogar': 'Não foi possível revogar.',
  'overall.revogarHomologacao': 'Revogar homologação',
  'overall.revogarDescricao': 'A revogação retira o bônus de +10. A colocação não é alterada.',
  'overall.corrigeDecisao': 'Isto corrige uma decisão oficial já registrada.',
  'overall.motivoNaAuditoria': 'O motivo fica na auditoria, junto de quem revogou e de quando.',
  'overall.motivoDaRevogacao': 'Motivo da revogação',
  'overall.exemploDeMotivo': 'Ex.: ata oficial corrigida pela organização',
  'overall.revogando': 'Revogando…',
  // Lançamentos do campeonato: corrigir, invalidar, restaurar.
  'lancamento.titulo': 'Lançamentos do campeonato',
  'lancamento.descricao': 'Correção e invalidação de resultado já publicado. Toda alteração exige motivo e fica na auditoria.',
  'lancamento.escolhaCampeonato': 'A correção é feita com a súmula do campeonato na mão, lançamento por lançamento.',
  'lancamento.contagem': '{n} lançamento(s)',
  'lancamento.invalidados': '{n} invalidado(s)',
  'lancamento.nenhum': 'Nenhum lançamento neste campeonato',
  'lancamento.nenhumDescricao': 'Os lançamentos aparecem depois que uma importação é aplicada ou um resultado é publicado.',
  'lancamento.classe': 'Classe',
  'lancamento.pontos': 'Pontos',
  'lancamento.matricula': 'Matrícula {numero}',
  'lancamento.invalidado': 'Invalidado',
  'lancamento.valido': 'Válido',
  'lancamento.restaurar': 'Restaurar',
  'lancamento.corrigir': 'Corrigir',
  'lancamento.corrigidoAviso': 'Lançamento corrigido.',
  'lancamento.falhaAoCorrigir': 'Não foi possível corrigir.',
  'lancamento.corrigirLancamento': 'Corrigir lançamento',
  'lancamento.naoCompareceu': 'Não compareceu (NS)',
  'lancamento.naoSubiuAoPalco': 'O atleta não subiu ao palco nesta classe',
  'lancamento.colocacaoHint': 'A pontuação é calculada pelo servidor. Do 6º em diante vale zero.',
  'lancamento.motivoDaCorrecao': 'Motivo da correção',
  'lancamento.exemploCorrecao': 'Ex.: súmula oficial da organização corrigida',
  'lancamento.corrigindo': 'Corrigindo…',
  'lancamento.confirmarCorrecao': 'Confirmar correção',
  'lancamento.colocacaoAntes': 'Colocação antes',
  'lancamento.colocacaoDepois': 'Colocação depois',
  'lancamento.pontosAntes': 'Pontos antes',
  'lancamento.pontosDepois': 'Pontos depois',
  'lancamento.diferenca': 'Diferença',
  'lancamento.invalidadoAviso': 'Lançamento invalidado.',
  'lancamento.falhaAoInvalidar': 'Não foi possível invalidar.',
  'lancamento.invalidarLancamento': 'Invalidar lançamento',
  'lancamento.naoEApagada': 'A participação NÃO é apagada.',
  'lancamento.naoEApagadaTexto': 'Ela continua no histórico do atleta valendo zero, marcada como invalidada e com este motivo à vista. Perde os {pontos} ponto(s) e o bônus de Overall, se houver.',
  'lancamento.motivoDaInvalidacao': 'Motivo da invalidação',
  'lancamento.exemploInvalidacao': 'Ex.: atleta desclassificado pela comissão técnica',
  'lancamento.invalidando': 'Invalidando…',
  'lancamento.restauradoAviso': 'Lançamento restaurado.',
  'lancamento.falhaAoRestaurar': 'Não foi possível restaurar.',
  'lancamento.restaurarLancamento': 'Restaurar lançamento',
  'lancamento.voltaAoEstado': 'Volta ao estado de antes da invalidação.',
  'lancamento.voltaAoEstadoTexto': 'A colocação {colocacao} volta a pontuar pela tabela vigente da temporada, e não por um total congelado no momento da invalidação.',
  'lancamento.invalidadoPor': 'Invalidado por: {motivo}',
  'lancamento.motivoDaRestauracao': 'Motivo da restauração',
  'lancamento.exemploRestauracao': 'Ex.: desclassificação revertida pela comissão',
  'lancamento.restaurando': 'Restaurando…',
  // Resultados. O MCI NÃO julga: a tela transcreve a colocação oficial recebida.
  'resultado.competicao': 'Competição',
  'resultado.titulo': 'Resultados',
  'resultado.descricao': 'Lançamento do resultado oficial recebido, publicação protegida e correção versionada.',
  'resultado.selecioneEvento': 'Selecione um evento',
  'resultado.porClasse': 'Resultado oficial por classe',
  'resultado.publicado': 'Publicado',
  'resultado.rascunho': 'Rascunho',
  'resultado.resumoDaLinha': '{situacao} · versão {versao} · checksum {checksum}…',
  'resultado.aindaNaoRecebido': 'Resultado ainda não recebido',
  'resultado.empateNaoResolvido': 'Empate não resolvido',
  'resultado.relancar': 'Relançar',
  'resultado.lancarResultado': 'Lançar resultado',
  'resultado.publicar': 'Publicar',
  'resultado.corrigir': 'Corrigir',
  'resultado.versoes': 'Versões',
  'resultado.semClasses': 'Sem classes cadastradas',
  'resultado.tituloOverall': 'Título Overall',
  'resultado.tituloOverallNota': 'Declarado pela organização. A plataforma registra — não decide.',
  'resultado.overallDoEvento': 'Overall do evento',
  'resultado.declaradoEm': 'declarado em {data}',
  'resultado.nenhumTitulo': 'Nenhum título Overall declarado',
  'resultado.nenhumTituloDescricao': 'O Overall é decidido pela comissão e registrado aqui.',
  'resultado.versaoApurada': 'Versão {versao} · apurado em {data}',
  'resultado.empateCurto': 'EMP',
  'resultado.somaBruta': 'soma {soma} · bruta {bruta} · {votos} voto(s)',
  'resultado.lancadoComEmpate': 'Resultado lançado com empate não resolvido: a publicação fica travada até a correção.',
  'resultado.lancadoAviso': 'Resultado oficial lançado.',
  'resultado.publicacaoTravada': 'A publicação fica travada até a comissão decidir.',
  'resultado.lancadoTitulo': 'Resultado lançado',
  'resultado.lancarEm': 'Lançar resultado — {classe}',
  'resultado.julgamentoExterno': 'O julgamento é externo. Transcreva a colocação oficial recebida; a plataforma não recalcula nem desempata.',
  'resultado.colocado': 'Colocado',
  'resultado.desclassificado': 'Desclassificado',
  'resultado.ausente': 'Ausente',
  'resultado.nenhumInscrito': 'Nenhum inscrito nesta classe',
  'resultado.lancarOficial': 'Lançar resultado oficial',
  'resultado.publicadoComPontos': 'Resultado publicado. {complemento}',
  'resultado.atletasPontuaram': '{n} atleta(s) pontuaram no ranking.',
  'resultado.semPontuacao': 'Sem pontuação de ranking (evento sem temporada).',
  'resultado.publicadoTitulo': 'Resultado publicado',
  'resultado.classificacaoPublica': 'Classificação agora é pública.',
  'resultado.publicarResultado': 'Publicar resultado',
  'resultado.publicarDescricao': 'Publicar torna a classificação pública e dispara a pontuação de ranking.',
  'resultado.motivoObservacao': 'Motivo / observação',
  'resultado.motivoHint': 'Fica registrado na versão publicada.',
  'resultado.exemploMotivo': 'Ex: Resultado oficial conferido pela comissão técnica',
  'resultado.correcaoRegistradaAviso': 'Correção registrada como nova versão.',
  'resultado.correcaoRegistrada': 'Correção registrada',
  'resultado.versaoPreservada': 'A versão anterior foi preservada.',
  'resultado.corrigirResultado': 'Corrigir resultado',
  'resultado.corrigirDescricao': 'A correção não sobrescreve: cria a versão seguinte, preserva a anterior e exige motivo.',
  'resultado.motivoDaCorrecao': 'Motivo da correção',
  'resultado.exemploCorrecao': 'Ex: Desempate decidido em reunião da comissão técnica',
  'resultado.situacaoDe': 'Situação de {nome}',
  'resultado.colocacaoDe': 'Colocação de {nome}',
  'resultado.classificado': 'Classificado',
  'resultado.colocacaoRepetida': 'Colocação repetida',
  'resultado.colocacaoRepetidaTexto': 'Duas colocações iguais não formam uma classificação válida.',
  'resultado.registrarCorrecao': 'Registrar correção',
  'resultado.historicoDeVersoes': 'Histórico de versões',
  'resultado.historicoDescricao': 'Cada mudança de estado do resultado gera uma versão preservada.',
  'resultado.sistema': 'sistema',
  'resultado.semVersoes': 'Sem versões registradas',
  'resultado.tituloDeclaradoAviso': 'Título Overall declarado. Os resultados publicados foram repontuados.',
  'resultado.campeaoOverall': 'Campeão Overall',
  'resultado.declararTitulo': 'Declarar título Overall',
  'resultado.declararDescricao': 'A comissão decide; a plataforma registra. A declaração fica na auditoria e repontua os resultados já publicados.',
  'resultado.tituloNaoDeclarado': 'Título não declarado',
  'resultado.nadaFoiRegistrado': 'Nada foi registrado. Confira a escolha e tente de novo.',
  'resultado.somenteInscritos': 'Somente inscritos neste evento.',
  'resultado.selecione': 'Selecione…',
  'resultado.recorte': 'Recorte',
  'resultado.recorteHint': 'Sem recorte, é o Overall do evento inteiro.',
  'resultado.observacao': 'Observação',
  'resultado.observacaoHint': 'Fica registrada junto da declaração.',
  'resultado.exemploObservacao': 'Ex: decisão da comissão técnica em 14/09',
  // Telas públicas: início, campeonatos, atletas e ranking.
  'publico.subtitulo': 'Gestão de competição, resultados, ranking e a comunidade do fisiculturismo brasileiro em uma única plataforma.',
  'publico.onzeCategorias': 'Onze categorias oficiais',
  'publico.quemParticipa': 'Atletas, coaches, equipes e academias',
  'publico.temporadasERanking': 'Temporadas e ranking nacional',
  'publico.campeonatos': 'Campeonatos',
  'publico.atletas': 'Atletas',
  'publico.atletasPro': 'Atletas PRO',
  'publico.resultadosPublicados': 'Resultados publicados',
  'publico.destinoCampeonatos': 'os campeonatos',
  'publico.destinoAtletas': 'os atletas',
  'publico.destinoRanking': 'o ranking',
  'publico.proximosCampeonatos': 'Próximos campeonatos',
  'publico.verTodos': 'Ver todos',
  'publico.localADefinir': 'Local a definir',
  'publico.nenhumAgendado': 'Nenhum campeonato agendado',
  'publico.nenhumAgendadoDescricao': 'Assim que uma etapa for planejada, ela aparece aqui.',
  'publico.completo': 'Completo',
  'publico.geral': 'Geral',
  'publico.rankingEmConstrucao': 'Ranking em construção',
  'publico.rankingEmConstrucaoDescricao': 'A pontuação aparece após a publicação dos primeiros resultados.',
  'publico.competicoes': 'Competições',
  'publico.etapasDoCampeonato': 'Etapas do Campeonato Brasileiro Muscle Contest.',
  'publico.buscarCampeonato': 'Buscar campeonato…',
  'publico.buscarCampeonatoRotulo': 'Buscar campeonato',
  'publico.nenhumEncontrado': 'Nenhum campeonato encontrado',
  'publico.nenhumEncontradoDescricao': 'Ajuste a busca para ver outras etapas.',
  'publico.proximaEtapa': 'Próxima etapa',
  'publico.descricaoPadraoDaEtapa': 'Etapa do Campeonato Brasileiro Muscle Contest.',
  'publico.voltarParaCampeonatos': '← Campeonatos',
  'publico.voltarParaAtletas': '← Atletas',
  'publico.atletasContagem': '{n} atletas',
  'publico.abaResultados': 'Resultados',
  'publico.abaCategorias': 'Categorias',
  'publico.abaAgenda': 'Agenda',
  'publico.abaPatrocinadores': 'Patrocinadores',
  'publico.publicado': 'Publicado',
  'publico.semEquipe': 'Sem equipe',
  'publico.semResultados': 'Resultados ainda não publicados',
  'publico.semResultadosDescricao': 'A classificação aparece aqui quando a organização publicar a apuração.',
  'publico.semClasses': 'Sem classes cadastradas',
  'publico.semDivisoes': 'Divisões ainda não cadastradas.',
  'publico.semCategorias': 'Categorias não definidas',
  'publico.semCategoriasDescricao': 'A organização ainda não montou o quadro de categorias.',
  'publico.chamadasEBaterias': 'Chamadas e baterias',
  'publico.horarioADefinir': 'Horário a definir',
  'publico.semAgenda': 'Agenda não publicada',
  'publico.semAgendaDescricao': 'As baterias aparecem quando a ordem de palco for montada.',
  'publico.atletasInscritos': 'Atletas inscritos',
  'publico.semInscritos': 'Sem inscritos confirmados',
  'publico.patrocinadoresEMarcas': 'Patrocinadores e marcas',
  'publico.semPatrocinadores': 'Sem patrocinadores registrados',
  'publico.semPatrocinadoresDescricao': 'O apoio institucional do evento aparece aqui.',
  'publico.comunidade': 'Comunidade',
  'publico.perfisPublicos': 'Perfis públicos dos atletas da plataforma.',
  'publico.buscarAtleta': 'Buscar por nome ou nome esportivo…',
  'publico.buscarAtletaRotulo': 'Buscar atleta',
  'publico.nenhumAtleta': 'Nenhum atleta encontrado',
  'publico.nenhumAtletaDescricao': 'Ajuste a busca ou aguarde novos cadastros.',
  'publico.semFiliacao': 'Sem filiação',
  'publico.comCoach': 'Coach {nome}',
  'publico.semCoach': 'Sem coach',
  'publico.titulos': 'Títulos',
  'publico.temporadasNoRanking': 'Temporadas no ranking',
  'publico.pontosSomados': 'Pontos somados',
  'publico.historicoEsportivo': 'Histórico esportivo',
  'publico.verEtapa': 'Ver etapa',
  'publico.semResultadosDoAtleta': 'Ainda sem resultados publicados',
  'publico.participacoes': '{n} participação(ões)',
  'publico.semPontuacao': 'Sem pontuação de ranking',
  'publico.abaCampeonato': 'Campeonato',
  'publico.abaSuperOverall': 'Super Overall',
  'publico.abaEquipes': 'Equipes',
  'publico.abaEmpresas': 'Empresas',
  'publico.temporada': 'Temporada',
  'publico.rankingDescricao': 'Pontuação por atleta, equipe, empresa e temporada. Cada ponto é rastreável até a sua origem.',
  'publico.classificatorioAnual': 'Classificatório anual',
  'publico.classificatorioTexto': 'Todas as classes pontuam no campeonato, mas somente a <b>Open</b> alimenta o Super Overall. Os números desta aba não se somam aos das outras.',
  'publico.temporadaMaisRecente': 'Temporada aberta mais recente',
  'publico.todasAsCategorias': 'Todas as categorias',
  'ajuste.acao': 'Editar pontos',
  'ajuste.titulo': 'Editar pontos',
  'ajuste.descricao': 'Altera somente a pontuação. Colocação, categoria, classe, campeonato, temporada e atleta ficam como estão.',
  'ajuste.pontosAtuais': 'Pontos atuais',
  'ajuste.novoValor': 'Novo valor',
  'ajuste.motivo': 'Motivo da alteração',
  'ajuste.motivoAjuda': 'Obrigatório, no mínimo 5 caracteres. Fica registrado na auditoria.',
  'ajuste.diferenca': 'Diferença',
  'ajuste.confirmar': 'Confirmar ajuste',
  'ajuste.enviando': 'Registrando…',
  'ajuste.registrado': 'Ajuste registrado.',
  'ajuste.falhou': 'Não foi possível registrar o ajuste.',
  'publico.campeonato': 'Campeonato',
  'publico.classe': 'Classe',
  'publico.todasAsClasses': 'Todas as classes',
  'publico.uf': 'UF',
  'publico.etapas': 'Etapas',
  'publico.pontos': 'Pontos',
  'publico.legendaDoRanking': 'Cada colocação vale pela tabela oficial da temporada (1º = 5, 2º = 4, 3º = 3, 4º = 2, 5º = 1). Cada título de <b>Overall</b> soma <b>+10</b>, uma vez por campeonato — quem venceu o Overall de dois campeonatos soma +20 na temporada.',
  'publico.rankingVazio': 'Ranking vazio',
  'publico.rankingVazioDescricao': 'A pontuação aparece quando resultados forem publicados ou importados.',
  'publico.semElegiveis': 'Nenhum resultado elegível',
  'publico.semEquipes': 'Nenhuma equipe pontuou',
  'publico.semEmpresas': 'Nenhuma empresa pontuou',
  'publico.semElegiveisDescricao': 'Só resultados da classe Open publicados alimentam o classificatório anual.',
  'publico.semEquipesDescricao': 'A equipe pontua pelo que os seus atletas conquistam.',
  'publico.semEmpresasDescricao': 'A empresa pontua pelo que as suas equipes conquistam.',
  'publico.equipe': 'Equipe',
  'publico.empresa': 'Empresa',
  'publico.primeiroCriterio': 'Primeiro critério de desempate',
  'publico.empate': 'empate',
  // MCI Social: feed, stories, publicações, perfis, comunidades e notificações.
  'social.storyPublicado': 'Story publicado.',
  'social.enviando': 'Enviando…',
  'social.seuStory': 'Seu story',
  'social.publicarStory': 'Publicar story',
  'social.story': 'Story',
  'social.expira': 'expira {quando}',
  'social.publicacaoCriadaAviso': 'Publicação criada.',
  'social.publicacaoCriada': 'Publicação criada',
  'social.jaNoPerfil': 'Já está no seu perfil.',
  'social.compartilhePlaceholder': 'Compartilhe treino, bastidor, resultado…',
  'social.conteudoDaPublicacao': 'Conteúdo da publicação',
  'social.midia': 'Mídia',
  'social.anexarMidia': 'Anexar mídia',
  'social.previaDe': 'Prévia de {nome}',
  'social.removerArquivo': 'Remover {nome}',
  'social.visibilidade': 'Visibilidade',
  'social.publica': 'Pública',
  'social.seguidores': 'Seguidores',
  'social.somenteEu': 'Somente eu',
  'social.publicando': 'Publicando…',
  'social.publicar': 'Publicar',
  'social.responder': 'Responder',
  'social.apagar': 'Apagar',
  'social.respondendoA': 'Respondendo @{handle}…',
  'social.comentarPlaceholder': 'Comentar…',
  'social.comentario': 'Comentário',
  'social.compartilhadaAviso': 'Publicação compartilhada.',
  'social.removidaAviso': 'Publicação removida.',
  'social.motivoDaDenuncia': 'Descreva o motivo da denúncia:',
  'social.denunciaRegistrada': 'Denúncia registrada. A moderação vai analisar.',
  'social.visibilidadeSeguidores': 'seguidores',
  'social.visibilidadePrivado': 'privado',
  'social.apagarPublicacao': 'Apagar publicação',
  'social.denunciarPublicacao': 'Denunciar publicação',
  'social.midiaDaPublicacao': 'Mídia da publicação',
  'social.curtirRotulo': 'Curtir publicação ({n})',
  'social.descurtirRotulo': 'Descurtir publicação ({n})',
  'social.abrirComentarios': 'Abrir comentários ({n})',
  'social.fecharComentarios': 'Fechar comentários ({n})',
  'social.compartilharRotulo': 'Compartilhar publicação ({n})',
  'social.salvarRotulo': 'Salvar publicação ({n})',
  'social.removerDosSalvosRotulo': 'Remover publicação dos salvos ({n})',
  'social.mciSocial': 'MCI Social',
  'social.feed': 'Feed',
  'social.feedDescricao': 'A comunidade Muscle Contest: atletas, coaches, academias, equipes e marcas.',
  'social.seguindo': 'Seguindo',
  'social.descobrir': 'Descobrir',
  'social.feedVazio': 'Seu feed está vazio',
  'social.semPublicasAinda': 'Ainda não há publicações públicas',
  'social.feedVazioDescricao': 'Siga atletas, coaches e marcas para acompanhar o que eles publicam.',
  'social.publiqueAlgo': 'Publique algo para começar a conversa.',
  'social.descobrirPerfis': 'Descobrir perfis',
  'social.comunidades': 'Comunidades',
  'social.membrosEPublicacoes': '{membros} membros · {publicacoes} publicações',
  'social.membro': 'Membro',
  'social.perfilBloqueado': 'Perfil bloqueado.',
  'social.publicacoes': 'publicações',
  'social.seguidoresContagem': 'seguidores',
  'social.seguindoContagem': 'seguindo',
  'social.deixarDeSeguir': 'Deixar de seguir',
  'social.seguir': 'Seguir',
  'social.bloquear': 'Bloquear',
  'social.titulos': 'Títulos',
  'social.podios': 'Pódios',
  'social.equipe': 'Equipe',
  'social.academia': 'Academia',
  'social.verEtapa': 'Ver etapa',
  'social.semPublicacoes': 'Sem publicações',
  'social.semPublicacoesDescricao': 'Este perfil ainda não publicou nada visível para você.',
  'social.perfilPrivado': 'Perfil privado',
  'social.perfilPrivadoDescricao': 'Siga este perfil para acompanhar as publicações.',
  'social.mciCommunity': 'MCI Community',
  'social.comunidadesDescricao': 'Espaços por categoria, papel e campeonato.',
  'social.privada': 'Privada',
  'social.semDescricao': 'Sem descrição.',
  'social.membros': '{n} membros',
  'social.publicacoesContagem': '{n} publicações',
  'social.abrir': 'Abrir',
  'social.entrar': 'Entrar',
  'social.nenhumaComunidade': 'Nenhuma comunidade disponível',
  'social.entrouEm': 'Você entrou em {nome}.',
  'social.publicadoNaComunidade': 'Publicado na comunidade.',
  'social.voltarParaComunidades': '← Comunidades',
  'social.sair': 'Sair',
  'social.regras': 'Regras',
  'social.publicarEm': 'Publicar em {nome}…',
  'social.publicacaoNaComunidade': 'Publicação na comunidade',
  'social.sejaOPrimeiro': 'Seja o primeiro a publicar aqui.',
  'social.entreParaParticipar': 'Entre na comunidade para participar.',
  'social.membrosTitulo': 'Membros',
  'social.admin': 'Admin',
  'social.salvos': 'Salvos',
  'social.salvosDescricao': 'Publicações que você guardou.',
  'social.nadaSalvo': 'Nada salvo ainda',
  'social.nadaSalvoDescricao': 'Use o marcador de uma publicação para guardá-la aqui.',
  'social.central': 'Central',
  'social.notificacoes': 'Notificações',
  'social.notificacoesDescricao': 'Interações sociais, mensagens e movimentações do campeonato.',
  'social.marcarTodas': 'Marcar todas como lidas',
  'social.marcarLida': 'Marcar lida',
  'social.nenhumaNotificacao': 'Nenhuma notificação',
  'social.nenhumaNotificacaoDescricao': 'Curtidas, comentários, mensagens e resultados aparecem aqui.',
  'social.meuPerfilSocial': 'Meu perfil social',
  'social.meuPerfilDescricao': 'Identidade pública na comunidade Muscle Contest.',
  'social.semBio': 'Sem bio.',
  'social.editarPerfil': 'Editar perfil',
  'social.formatoNaoAceito': 'Formato não aceito. Use JPG, PNG ou WebP.',
  'social.fotoGrandeDemais': 'A foto passa de 5 MB. Escolha uma menor.',
  'social.fotoAtualizada': 'Foto de perfil atualizada.',
  'social.fotoRemovida': 'Foto de perfil removida.',
  'social.previaDaNovaFoto': 'Prévia da nova foto de perfil',
  'social.salvando': 'Salvando…',
  'social.salvarFoto': 'Salvar foto',
  'social.trocarFoto': 'Trocar foto',
  'social.adicionarFoto': 'Adicionar foto',
  'social.removerFoto': 'Remover foto',
  'social.escolherFoto': 'Escolher foto de perfil',
  'social.perfilAtualizado': 'Perfil atualizado.',
  'social.editarPerfilSocial': 'Editar perfil social',
  'social.nomeDeExibicao': 'Nome de exibição',
  'social.identificador': 'Identificador',
  'social.identificadorHint': 'Somente letras minúsculas, números, ponto e sublinhado.',
  'social.bio': 'Bio',
  'social.perfilPrivadoOpcao': 'Perfil privado (só seguidores veem as publicações)',
  // Administração de eventos: etapas, quadro de categorias, inscrições,
  // check-in, pesagem, credenciamento e ordem de palco.
  'evento.selecionarEvento': 'Selecionar evento',
  'evento.listaIndisponivel': 'Lista indisponível',
  'evento.selecioneOEvento': 'Selecione o evento…',
  'evento.administracao': 'Administração',
  'evento.eventos': 'Eventos',
  'evento.eventosDescricao': 'Etapas, quadro de categorias e estados da competição.',
  'evento.filtrarPorEstado': 'Filtrar por estado',
  'evento.todosOsEstados': 'Todos os estados',
  'evento.colunaEvento': 'Evento',
  'evento.colunaEstado': 'Estado',
  'evento.colunaData': 'Data',
  'evento.abrir': 'Abrir',
  'evento.nenhumEvento': 'Nenhum evento',
  'evento.nenhumEventoDescricao': 'Crie a primeira etapa para começar.',
  'evento.criadoRascunho': 'Evento criado como rascunho.',
  'evento.novoEvento': 'Novo evento',
  'evento.novoEventoDescricao': 'O evento nasce em rascunho e só aceita inscrição depois de aberto.',
  'evento.organizacao': 'Organização',
  'evento.selecione': 'Selecione…',
  'evento.nome': 'Nome',
  'evento.exemploNome': 'Ex: Etapa Cuiabá 2026',
  'evento.identificadorNaUrl': 'Identificador na URL',
  'evento.identificadorHint': 'Minúsculas, números e hífen.',
  'evento.descricao': 'Descrição',
  'evento.inicio': 'Início',
  'evento.termino': 'Término',
  'evento.cidade': 'Cidade',
  'evento.local': 'Local',
  'evento.temporada': 'Temporada',
  'evento.temporadaHint': 'Vincular a uma temporada é o que faz o resultado pontuar no ranking.',
  'evento.semTemporada': 'Sem temporada',
  'evento.criarEvento': 'Criar evento',
  'evento.atualizado': 'Evento atualizado.',
  'evento.editarEvento': 'Editar evento',
  'evento.editarDescricao': 'Endereço na URL, federação e estado do evento não mudam por aqui.',
  'evento.salvarAlteracoes': 'Salvar alterações',
  'evento.editar': 'Editar',
  'evento.estadoFinal': 'Estado final: não há transição disponível.',
  'evento.inscritos': 'Inscritos',
  'evento.checkInFeito': 'Check-in feito',
  'evento.pesagens': 'Pesagens',
  'evento.credenciaisAtivas': 'Credenciais ativas',
  'evento.quadroDeCategorias': 'Quadro de categorias',
  'evento.masculina': 'Masculina',
  'evento.feminina': 'Feminina',
  'evento.nenhumaClasse': 'Nenhuma classe.',
  'evento.semDivisoes': 'Sem divisões.',
  'evento.semCategorias': 'Sem categorias',
  'evento.semCategoriasDescricao': 'Adicione as categorias oficiais que este evento vai disputar.',
  'evento.mudarEstado': 'Mudar o estado do evento',
  'evento.resultadosVisiveis': 'Resultados publicados ficam visíveis ao público.',
  'evento.categoriaAdicionada': 'Categoria adicionada ao evento.',
  'evento.adicionarCategoria': 'Adicionar categoria',
  'evento.catalogoOficial': 'Catálogo oficial do Campeonato Brasileiro Muscle Contest.',
  'evento.categoria': 'Categoria',
  'evento.adicionar': 'Adicionar',
  'evento.divisaoCriada': 'Divisão criada.',
  'evento.novaDivisao': 'Nova divisão',
  'evento.novaDivisaoDescricao': 'Ex.: faixa de altura, faixa de peso ou recorte definido pelo regulamento.',
  'evento.exemploDivisao': 'Ex: Até 163 cm',
  'evento.codigo': 'Código',
  'evento.criarDivisao': 'Criar divisão',
  'evento.classeCriada': 'Classe criada.',
  'evento.novaClasse': 'Nova classe',
  'evento.novaClasseDescricao': 'Classes iniciais: Junior, Novice, Open e Master. A estrutura aceita outras.',
  'evento.idadeMinima': 'Idade mínima',
  'evento.idadeMaxima': 'Idade máxima',
  'evento.pesoMinimo': 'Peso mínimo (kg)',
  'evento.pesoMaximo': 'Peso máximo (kg)',
  'evento.criarClasse': 'Criar classe',
  'evento.operacao': 'Operação',
  'evento.inscricoes': 'Inscrições',
  'evento.buscarAtleta': 'Buscar atleta…',
  'evento.buscarInscrito': 'Buscar inscrito',
  'evento.selecioneUmEvento': 'Selecione um evento',
  'evento.inscricoesPorEvento': 'As inscrições são sempre de um evento específico.',
  'evento.limparFiltro': 'Limpar filtro',
  'evento.maisRegistros': 'Há mais registros neste evento. Use “Carregar mais” no fim da lista, ou a busca pelo nome do atleta.',
  'evento.atleta': 'Atleta',
  'evento.classes': 'Classes',
  'evento.situacao': 'Situação',
  'evento.feito': 'Feito',
  'evento.pendente': 'Pendente',
  'evento.cancelar': 'Cancelar',
  'evento.nadaEncontrado': 'Nada encontrado',
  'evento.nenhumaInscricao': 'Nenhuma inscrição',
  'evento.nenhumaInscricaoDescricao': 'Use “Nova inscrição” para registrar o primeiro atleta.',
  'evento.atletaReconhecido': 'Atleta reconhecido e inscrito.',
  'evento.perfilCriado': 'Perfil criado e atleta inscrito.',
  'evento.inscricaoRealizada': 'Inscrição realizada',
  'evento.reconhecidoPeloCpf': 'Atleta reconhecido pelo CPF.',
  'evento.novaInscricao': 'Nova inscrição',
  'evento.novaInscricaoDescricao': 'CPF → perfil → filiação → categoria, divisão e classe.',
  'evento.cpfDoAtleta': 'CPF do atleta',
  'evento.cpfHint': 'A plataforma reconhece o atleta pelo CPF antes de criar qualquer perfil.',
  'evento.consultando': 'Consultando…',
  'evento.consultar': 'Consultar',
  'evento.atletaReconhecidoTitulo': 'Atleta reconhecido',
  'evento.cpfNaoCadastrado': 'CPF não cadastrado',
  'evento.informeOsDados': 'Informe os dados para criar o perfil do atleta.',
  'evento.nomeCompleto': 'Nome completo',
  'evento.nomeEsportivo': 'Nome esportivo',
  'evento.sexo': 'Sexo',
  'evento.feminino': 'Feminino',
  'evento.masculino': 'Masculino',
  'evento.nascimento': 'Nascimento',
  'evento.nascimentoHint': 'Necessário para classes com faixa etária.',
  'evento.filiacao': 'Filiação',
  'evento.filiacaoHint': 'Vínculo esportivo do atleta. Também é chave de conferência na importação MuscleWare.',
  'evento.semFiliacao': 'Sem filiação',
  'evento.categoriasDivisoesClasses': 'Categorias, divisões e classes',
  'evento.semClassesCadastradas': 'Este evento ainda não tem classes cadastradas.',
  'evento.inscricaoRecusada': 'Inscrição recusada',
  'evento.registrarInscricao': 'Registrar inscrição',
  'evento.inscricaoCancelada': 'Inscrição cancelada.',
  'evento.inscricaoCanceladaTitulo': 'Inscrição cancelada',
  'evento.cancelarInscricao': 'Cancelar inscrição',
  'evento.motivo': 'Motivo',
  'evento.motivoHint': 'Fica registrado na auditoria.',
  'evento.checkInCancelado': 'Check-in cancelado.',
  'evento.checkInConfirmado': 'Check-in confirmado.',
  'evento.checkInConfirmadoTitulo': 'Check-in confirmado',
  'evento.checkIn': 'Check-in',
  'evento.checkInDescricao': 'Conferência de atleta, inscrição e elegibilidade no dia do evento.',
  'evento.nomeOuNumero': 'Nome ou número do atleta…',
  'evento.selecioneEventoEmOperacao': 'Selecione um evento em operação',
  'evento.janelaOperacional': 'O check-in só acontece com o evento em janela operacional.',
  'evento.atualizandoAoVivo': 'Atualizando ao vivo',
  'evento.pendentes': 'Pendentes',
  'evento.maisRegistrosCheckIn': 'Use “Carregar mais” no fim da lista, ou a busca pelo nome ou número do atleta.',
  'evento.semClasse': 'Sem classe',
  'evento.desfazendo': 'Desfazendo…',
  'evento.desfazer': 'Desfazer',
  'evento.confirmando': 'Confirmando…',
  'evento.fazerCheckIn': 'Fazer check-in',
  'evento.nenhumConfirmado': 'Nenhum inscrito confirmado',
  'evento.pesagem': 'Pesagem',
  'evento.pesagemDescricao': 'Registro auditável de peso e altura, com operador, momento e observação.',
  'evento.semPesagem': 'Sem pesagem registrada',
  'evento.pesagemForaDaFaixa': 'Pesagem registrada. Há classe fora da faixa de peso.',
  'evento.reclassificacaoEDaOrganizacao': 'A pesagem foi gravada. A reclassificação é decisão da organização.',
  'evento.pesagemRegistrada': 'Pesagem registrada.',
  'evento.pesagemRegistradaTitulo': 'Pesagem registrada',
  'evento.registrarPesagem': 'Registrar pesagem',
  'evento.pesoForaDaFaixa': 'Peso fora da faixa',
  'evento.pesoForaDaFaixaTexto': 'A pesagem foi gravada. As classes abaixo estão fora da faixa cadastrada — a reclassificação é decisão da organização.',
  'evento.entendi': 'Entendi',
  'evento.pesagemNaoRegistrada': 'Pesagem não registrada',
  'evento.confiraOValor': 'Confira o valor e registre de novo. Nada foi gravado.',
  'evento.pesoKg': 'Peso (kg)',
  'evento.alturaCm': 'Altura (cm)',
  'evento.observacao': 'Observação',
  'evento.registrar': 'Registrar',
  'evento.portaria': 'Portaria',
  'evento.acessoLiberado': 'Acesso liberado',
  'evento.acessoRecusado': 'Acesso recusado',
  'evento.credencialNaoAceita': 'Credencial não aceita.',
  'evento.credenciamento': 'Credenciamento',
  'evento.credenciamentoDescricao': 'Emissão e leitura de credenciais de atleta, coach, staff, juiz, imprensa, fotógrafo, patrocinador e convidado.',
  'evento.credenciaisEmitidas': 'Credenciais emitidas',
  'evento.ativa': 'Ativa',
  'evento.revogada': 'Revogada',
  'evento.credencialRevogada': 'Credencial revogada.',
  'evento.revogar': 'Revogar',
  'evento.nenhumaCredencial': 'Nenhuma credencial emitida',
  'evento.leitura': 'Leitura',
  'evento.codigoDaCredencial': 'Código da credencial',
  'evento.conteudoDoQr': 'Conteúdo do QR Code impresso.',
  'evento.validando': 'Validando…',
  'evento.validar': 'Validar',
  'evento.semCheckIn': 'Atleta ainda sem check-in.',
  'evento.credencialEmitida': 'Credencial emitida',
  'evento.emitirCredencial': 'Emitir credencial',
  'evento.tipo': 'Tipo',
  'evento.nomeDoPortador': 'Nome do portador',
  'evento.inscricaoVinculada': 'Inscrição vinculada',
  'evento.inscricaoVinculadaHint': 'Vincular permite conferir o check-in na leitura.',
  'evento.semVinculo': 'Sem vínculo',
  'evento.emitir': 'Emitir',
  'evento.bateriaChamada': 'Bateria chamada. Os atletas foram notificados.',
  'evento.bateriaAtualizada': 'Bateria atualizada.',
  'evento.bateriaChamadaTitulo': 'Bateria chamada',
  'evento.ordemDePalco': 'Ordem de palco',
  'evento.ordemDePalcoDescricao': 'Baterias, chamadas e ordem de entrada por classe.',
  'evento.noPalco': 'No palco',
  'evento.ordem': 'Ordem',
  'evento.chamando': 'Chamando…',
  'evento.chamar': 'Chamar',
  'evento.entrando': 'Entrando…',
  'evento.encerrando': 'Encerrando…',
  'evento.encerrar': 'Encerrar',
  'evento.nenhumaBateria': 'Nenhuma bateria',
  'evento.nenhumaBateriaDescricao': 'Crie a primeira bateria para montar a ordem de palco.',
  'evento.bateriaCriada': 'Bateria criada.',
  'evento.novaBateria': 'Nova bateria',
  'evento.classe': 'Classe',
  'evento.exemploBateria': 'Ex: Bateria 1',
  'evento.horario': 'Horário',
  'evento.criarBateria': 'Criar bateria',
  'evento.ordemSalva': 'Ordem de palco salva.',
  'evento.posicaoDeEntrada': 'Posição de entrada dos atletas nesta bateria.',
  'evento.ordemDefinida': 'Ordem definida',
  'evento.subir': 'Subir',
  'evento.descer': 'Descer',
  'evento.nenhumAtletaNaOrdem': 'Nenhum atleta na ordem.',
  'evento.disponiveis': 'Disponíveis',
  'evento.todosNaOrdem': 'Todos os inscritos já estão na ordem.',
  'evento.fechar': 'Fechar',
  'evento.salvarOrdem': 'Salvar ordem',
  'evento.temporadaDe': 'Temporada {nome}',
  'evento.moverPara': 'Mover o evento para "{estado}"?',
  'evento.falhaAoCarregarEventos': 'Não foi possível carregar os eventos.',
  // Painel da plataforma: temporadas, tabela de pontos, importação MuscleWare,
  // auditoria e configurações.
  'plataforma.painel': 'Painel',
  'plataforma.painelDescricao': 'Números reais da operação. Nenhuma métrica desta tela é estimada.',
  'plataforma.eventosAtivos': 'Eventos ativos',
  'plataforma.checkIns': 'Check-ins',
  'plataforma.baterias': 'Baterias',
  'plataforma.importacoes': 'Importações MuscleWare',
  'plataforma.criarEtapas': 'Criar etapas, montar o quadro de categorias e mover estados.',
  'plataforma.trilhaDasAcoes': 'Trilha das ações críticas da plataforma.',
  'plataforma.rankingETemporadas': 'Ranking e temporadas',
  'plataforma.tabelaEDoRegulamento': 'A tabela de pontos por colocação é dado do regulamento, não constante do sistema.',
  'plataforma.aberta': 'Aberta',
  'plataforma.encerrada': 'Encerrada',
  'plataforma.tabelaDePontos': 'Tabela de pontos',
  'plataforma.recalculoSemTabela': 'Sem tabela de pontos nesta temporada: nada foi recalculado. Cadastre a tabela e recalcule.',
  'plataforma.recalculoAlterou': '{alterados} de {total} lançamentos recalculados.',
  'plataforma.recalculoSemMudanca': '{total} lançamentos conferidos. Nenhuma alteração.',
  'overall.doHistorico': 'Histórico importado',
  'overall.semCadastro': 'Sem cadastro no MCI',
  'plataforma.autocadastroAbertoEtiqueta': 'Autocadastro aberto',
  'plataforma.autocadastroFechadoEtiqueta': 'Autocadastro fechado',
  'plataforma.abrirAutocadastro': 'Abrir autocadastro',
  'plataforma.fecharAutocadastro': 'Fechar autocadastro',
  'plataforma.autocadastroAberto': 'Autocadastro aberto. As filiações desta organização passam a aparecer para quem se cadastra.',
  'plataforma.autocadastroFechado': 'Autocadastro fechado. As filiações desta organização saem de circulação.',
  'plataforma.recalcular': 'Recalcular',
  'plataforma.semTabela': 'Sem tabela de pontos',
  'plataforma.semTabelaTexto': 'Nenhum resultado desta temporada vai pontuar até que a tabela seja cadastrada.',
  'plataforma.nenhumaTemporada': 'Nenhuma temporada',
  'plataforma.nenhumaTemporadaDescricao': 'Crie a temporada para que os resultados publicados pontuem no ranking.',
  'plataforma.conferirPontuacao': 'Conferir pontuação',
  'plataforma.duasMetricas': 'Duas métricas, não uma',
  'plataforma.pontosDoCampeonato': 'Pontos do Campeonato',
  'plataforma.elegiveisAoSuperOverall': 'Elegíveis ao Super Overall',
  'plataforma.verOrigem': 'Ver a origem de cada ponto',
  'plataforma.empateNaoResolvido': 'empate não resolvido',
  'plataforma.nenhumaPontuacao': 'Nenhuma pontuação',
  'plataforma.nenhumaPontuacaoDescricao': 'Publique resultados para que a temporada pontue.',
  'plataforma.ptsColocacao': 'Pts colocação',
  'plataforma.origem': 'Origem',
  'plataforma.naoElegivel': 'não elegível',
  'plataforma.totais': 'Totais',
  'plataforma.semPontosNaTemporada': 'Sem pontos nesta temporada',
  'plataforma.semPontosDescricao': 'Nenhum resultado publicado ou importado gerou pontuação.',
  'plataforma.temporadaCriada': 'Temporada criada.',
  'plataforma.novaTemporada': 'Nova temporada',
  'plataforma.exemploTemporada': 'Ex: Temporada 2026',
  'plataforma.ano': 'Ano',
  'plataforma.criarTemporada': 'Criar temporada',
  'plataforma.tabelaSalva': 'Tabela de pontos salva.',
  'plataforma.quantosPontos': 'Quantos pontos cada colocação vale nesta temporada. O sistema não presume nenhuma pontuação.',
  'plataforma.semTabelaTitulo': 'Esta temporada não tem tabela de pontos',
  'plataforma.informeATabela': 'Nada pontua até que ela seja cadastrada. Informe a tabela do regulamento.',
  'plataforma.salvarTabela': 'Salvar tabela',
  'plataforma.invalidarImportacaoPublicada': 'Invalidar importação publicada',
  'plataforma.excluirImportacao': 'Excluir importação',
  'plataforma.importacaoInvalidada': 'Importação invalidada com sucesso.',
  'plataforma.importacaoExcluida': 'Importação excluída com sucesso.',
  'plataforma.falhaNaOperacao': 'Não foi possível concluir a operação.',
  'plataforma.invalidarImportacaoPergunta': 'Invalidar importação?',
  'plataforma.excluirImportacaoPergunta': 'Excluir importação?',
  'plataforma.enviadaEm': 'Enviada em',
  'plataforma.temResultadosVinculados': 'Esta importação possui resultados vinculados ao ranking. A exclusão será tratada como',
  'plataforma.invalidacao': 'invalidação',
  'plataforma.ficaNaAuditoria': 'e ficará registrada na auditoria: os lançamentos continuam no histórico, marcados e valendo zero.',
  'plataforma.semResultadosPublicados': 'Esta importação ainda não publicou resultados.',
  'plataforma.motivoDaInvalidacao': 'Motivo da invalidação',
  'plataforma.motivoOpcional': 'Motivo (opcional)',
  'plataforma.exemploMotivo': 'erro na súmula, arquivo incorreto, evento incorreto...',
  'plataforma.invalidarImportacao': 'Invalidar importação',
  'plataforma.integracao': 'Integração',
  'plataforma.muscleWare': 'MuscleWare',
  'plataforma.muscleWareDescricao': 'Importação de resultados externos com reconhecimento por CPF, confirmação por filiação e idempotência.',
  'plataforma.quando': 'Quando',
  'plataforma.revisar': 'Revisar',
  'plataforma.nenhumaImportacao': 'Nenhuma importação',
  'plataforma.nenhumaImportacaoDescricao': 'Envie um arquivo do MuscleWare para começar.',
  'plataforma.previaGerada': 'Pré-visualização gerada. Nada foi aplicado ainda.',
  'plataforma.importarResultados': 'Importar resultados MuscleWare',
  'plataforma.arquivoEConferido': 'O arquivo é lido e conferido; nada é aplicado antes da sua confirmação.',
  'plataforma.semEvento': 'Sem evento',
  'plataforma.escolhaOrganizacao': 'Escolha a organização primeiro',
  'plataforma.semTemporadaHint': 'Sem temporada, o resultado entra no histórico mas não pontua no ranking.',
  'plataforma.arquivo': 'Arquivo',
  'plataforma.filiacaoDaEtapa': 'Filiação de toda a etapa',
  'plataforma.exemploNpc': 'Ex.: NPC',
  'plataforma.prefixoDoIdentificador': 'Prefixo do identificador',
  'plataforma.exemploIpiranga': 'Ex.: IPIRANGA',
  'plataforma.previsualizar': 'Pré-visualizar',
  'plataforma.reconhecidas': 'Reconhecidas',
  'plataforma.duplicadas': 'Duplicadas',
  'plataforma.rejeitadas': 'Rejeitadas',
  'plataforma.aplicadas': 'Aplicadas',
  'plataforma.pontosDoArquivo': 'Pontos do arquivo',
  'plataforma.revisarImportacao': 'Revisar importação',
  'plataforma.revisarDescricao': 'Confira os totais antes de aplicar. Linhas pendentes podem ser vinculadas manualmente.',
  'plataforma.semEtapaAviso': 'Os resultados entram no histórico sem etapa, e o ponto do ranking não saberá de qual campeonato veio.',
  'plataforma.registros': 'Registros',
  'plataforma.reconhecidos': 'Reconhecidos',
  'plataforma.pendentes': 'Pendentes',
  'plataforma.conflitos': 'Conflitos',
  'plataforma.duplicados': 'Duplicados',
  'plataforma.rejeitados': 'Rejeitados',
  'plataforma.aplicados': 'Aplicados',
  'plataforma.nenhumCriadoAutomaticamente': 'Nenhum atleta é criado automaticamente.',
  'plataforma.registrosQueNaoEntram': 'Há registros que não entram',
  'plataforma.buscarNaImportacao': 'Buscar na importação',
  'plataforma.buscarNaImportacaoPlaceholder': 'Buscar atleta, matrícula, classe...',
  'plataforma.todas': 'Todas',
  'plataforma.exportarDica': 'Exportar as linhas desta página, com os filtros aplicados',
  'plataforma.exportar': 'Exportar',
  'plataforma.nenhumRegistroNoFiltro': 'Nenhum registro no filtro',
  'plataforma.matricula': 'Matrícula',
  'plataforma.ptsArquivo': 'Pts arquivo',
  'plataforma.por': 'por',
  'plataforma.sugerido': 'sugerido',
  'plataforma.conflitoDeIdentidade': 'Conflito de identidade',
  'plataforma.arquivoRotulo': 'arquivo',
  'plataforma.regraOficial': 'regra oficial',
  'plataforma.diferenca': 'diferença',
  'plataforma.vincularAoAtleta': 'Vincular ao atleta',
  'plataforma.anterior': 'Anterior',
  'plataforma.proxima': 'Próxima',
  'plataforma.aplicarImportacao': 'Aplicar importação',
  'plataforma.semEventoMaiusculo': 'SEM EVENTO — os resultados ficarão sem etapa no histórico',
  'plataforma.registroVinculado': 'Registro vinculado ao atleta.',
  'plataforma.nomeOuNomeEsportivo': 'Nome ou nome esportivo…',
  'plataforma.nenhumAtletaEncontrado': 'Nenhum atleta encontrado.',
  'plataforma.vincular': 'Vincular',
  'plataforma.seguranca': 'Segurança',
  'plataforma.auditoria': 'Auditoria',
  'plataforma.auditoriaDescricao': 'Trilha das ações críticas: quem fez, o quê, quando e sobre qual registro.',
  'plataforma.entidadeExemplo': 'Entidade (ex: Result)',
  'plataforma.filtrarPorEntidade': 'Filtrar por entidade',
  'plataforma.acaoExemplo': 'Ação (ex: RESULT_PUBLICATION)',
  'plataforma.filtrarPorAcao': 'Filtrar por ação',
  'plataforma.ator': 'Ator',
  'plataforma.acao': 'Ação',
  'plataforma.entidade': 'Entidade',
  'plataforma.detalhe': 'Detalhe',
  'plataforma.semRegistros': 'Sem registros',
  'plataforma.semRegistrosDescricao': 'Nenhuma ação corresponde ao filtro.',
  'plataforma.configuracoes': 'Configurações',
  'plataforma.configuracoesDescricao': 'Organizações, filiações, catálogo de categorias, parceiros e usuários.',
  'plataforma.filiacoes': 'Filiações',
  'plataforma.categorias': 'Categorias',
  'plataforma.parceiros': 'Parceiros',
  'plataforma.vinculoDeEquipe': 'Vínculo de equipe',
  'plataforma.usuarios': 'Usuários',
  'plataforma.organizacoes': 'Organizações',
  'plataforma.nova': 'Nova',
  'plataforma.membros': 'Membros',
  'plataforma.nenhumaOrganizacao': 'Nenhuma organização',
  'plataforma.nenhumaOrganizacaoDescricao': 'Crie a organização que vai operar os campeonatos.',
  'plataforma.organizacaoCriada': 'Organização criada. Você entrou como administrador dela.',
  'plataforma.novaOrganizacao': 'Nova organização',
  'plataforma.identificador': 'Identificador',
  'plataforma.criar': 'Criar',
  'plataforma.papelConcedido': 'Papel concedido nesta organização.',
  'plataforma.vinculoRemovido': 'Vínculo removido.',
  'plataforma.papelValeNaOrganizacao': 'O papel vale apenas dentro desta organização.',
  'plataforma.usuario': 'Usuário',
  'plataforma.papel': 'Papel',
  'plataforma.conceder': 'Conceder',
  'plataforma.remover': 'Remover',
  'plataforma.todasAsOrganizacoes': 'Todas as organizações',
  'plataforma.inativa': 'Inativa',
  'plataforma.desativar': 'Desativar',
  'plataforma.ativar': 'Ativar',
  'plataforma.nenhumaFiliacao': 'Nenhuma filiação',
  'plataforma.filiacaoDescricao': 'A filiação é o vínculo esportivo do atleta e chave de conferência na importação MuscleWare.',
  'plataforma.filiacaoCriada': 'Filiação criada.',
  'plataforma.novaFiliacao': 'Nova filiação',
  'plataforma.novaFiliacaoDescricao': 'Federação, entidade, associação ou vínculo esportivo responsável pelo atleta.',
  'plataforma.usadoNoMatching': 'Usado no matching MuscleWare.',
  'plataforma.criarFiliacao': 'Criar filiação',
  'plataforma.catalogoOficial': 'Catálogo oficial',
  'plataforma.categoriaAdicionada': 'Categoria adicionada ao catálogo.',
  'plataforma.novaCategoria': 'Nova categoria',
  'plataforma.catalogoExtensivel': 'O catálogo é extensível: categorias novas entram por aqui, sem alteração de código.',
  'plataforma.empresas': 'Empresas',
  'plataforma.equipes': 'Equipes',
  'plataforma.academias': 'Academias',
  'plataforma.marcas': 'Marcas',
  'plataforma.patrocinadores': 'Patrocinadores',
  'plataforma.nenhumRegistro': 'Nenhum registro.',
  'plataforma.novaEmpresa': 'Nova empresa',
  'plataforma.novaEquipe': 'Nova equipe',
  'plataforma.novaAcademia': 'Nova academia',
  'plataforma.novaMarca': 'Nova marca',
  'plataforma.novoPatrocinador': 'Novo patrocinador',
  'plataforma.registroCriado': 'Registro criado.',
  'plataforma.relacaoComercial': 'Relação COMERCIAL: não vincula atleta e não pontua. Nenhum valor financeiro é armazenado.',
  'plataforma.empresaCompetidora': 'Empresa competidora: entra no campeonato com as suas equipes e pontua pela mesma tabela.',
  'plataforma.identificadorSocial': 'Também vira o identificador do perfil social da marca.',
  'plataforma.empresa': 'Empresa',
  'plataforma.empresaHint': 'Opcional. A equipe pode competir sozinha; vinculada, os pontos dos seus atletas também contam para a empresa.',
  'plataforma.semEmpresa': 'Sem empresa',
  'plataforma.selecioneOrganizacao': 'Selecione a organização…',
  'plataforma.selecioneParaBuscar': 'Selecione a organização para buscar.',
  'plataforma.semEquipe': 'Sem equipe',
  'plataforma.vinculo': 'Vínculo',
  'plataforma.nenhumAtletaSelecionado': 'Nenhum atleta selecionado',
  'plataforma.escolhaUmAtleta': 'Escolha um atleta para ver o vínculo atual e o histórico.',
  'plataforma.equipeAtual': 'Equipe atual',
  'plataforma.transferir': 'Transferir',
  'plataforma.encerrarVinculo': 'Encerrar vínculo',
  'plataforma.ativo': 'ativo',
  'plataforma.semHistoricoDeVinculo': 'Sem histórico de vínculo.',
  'plataforma.vincularAEquipe': 'Vincular à equipe',
  'plataforma.transferirDeEquipe': 'Transferir de equipe',
  'plataforma.vinculoAtualizado': 'Vínculo atualizado.',
  'plataforma.equipe': 'Equipe',
  'plataforma.motivoNaAuditoria': 'Fica registrado na auditoria junto com quem autorizou.',
  'plataforma.buscarPorNomeOuEmail': 'Buscar por nome ou email…',
  'plataforma.buscarUsuario': 'Buscar usuário',
  'plataforma.usuarioAtualizado': 'Usuário atualizado.',
  'plataforma.papelGlobalDescricao': 'Papel global e situação da conta. Papéis por organização ficam em Organizações → Membros.',
  'plataforma.papelGlobal': 'Papel global',
  'plataforma.papelPrivilegiado': 'Papel privilegiado só é concedido por SUPER_ADMIN.',
  'plataforma.ativa': 'Ativa',
  'plataforma.suspensa': 'Suspensa',
  'plataforma.desativada': 'Desativada',
  // Cabeçalhos da planilha exportada da revisão.
  'plataforma.colunaNumero': '#',
  'plataforma.colunaCpf': 'CPF',
  'plataforma.colunaAtleta': 'Atleta',
  'plataforma.colunaFiliacao': 'Filiação',
  'plataforma.colunaCategoria': 'Categoria',
  'plataforma.colunaClasse': 'Classe',
  'plataforma.colunaColocacao': 'Colocação',
  'plataforma.colunaSituacao': 'Situação',
  'plataforma.colunaMotivo': 'Motivo',

  // ------------------------------------------------ ADMINISTRAÇÃO → ATLETAS
  // A lista e o perfil por onde o operador da federação gerencia o atleta.
  'atletas.titulo': 'Atletas',
  'atletas.descricao': 'Cadastro, estado e histórico esportivo de quem compete pela federação.',
  'atletas.buscar': 'Buscar atleta',
  'atletas.buscarPlaceholder': 'Nome, nome esportivo ou CPF…',
  'atletas.filtrarPorEstado': 'Filtrar por estado',
  'atletas.filtrarPorFiliacao': 'Filtrar por entidade de filiação',
  'atletas.todasAsFiliacoes': 'Todas as entidades',
  'atletas.todos': 'Todos',
  'atletas.situacao': 'Situação',
  'atletas.abrir': 'Abrir',

  'atleta.administracao': 'Administração',
  'atleta.abaResumo': 'Resumo',
  'atleta.abaCadastro': 'Cadastro',
  'atleta.abaHistorico': 'Histórico esportivo',
  'atleta.abaPontuacao': 'Pontuação',
  'atleta.estadoAtivo': 'Ativo',
  'atleta.estadoSuspenso': 'Suspenso',
  'atleta.estadoArquivado': 'Arquivado',
  'atleta.identidade': 'Identidade',
  'atleta.contato': 'Contato',
  'atleta.filiacao': 'Filiação',
  'atleta.entidade': 'Entidade de filiação',
  'atleta.matricula': 'Matrícula',
  'atleta.numeroDeAtleta': 'Número de atleta',
  'atleta.nomeCompleto': 'Nome completo',
  'atleta.nomeEsportivo': 'Nome esportivo',
  'atleta.cpf': 'CPF',
  'atleta.sexo': 'Sexo',
  'atleta.nascimento': 'Nascimento',
  'atleta.telefone': 'Telefone',
  'atleta.email': 'E-mail',
  'atleta.cidade': 'Cidade',
  'atleta.estadoUf': 'Estado',
  'atleta.equipe': 'Equipe',
  'atleta.treinador': 'Treinador',
  'atleta.campeonatos': 'Campeonatos',
  'atleta.campeonato': 'Campeonato',
  'atleta.categoria': 'Categoria',
  'atleta.classe': 'Classe',
  'atleta.colocacao': 'Colocação',
  'atleta.temporada': 'Temporada',
  'atleta.pontos': 'Pontos',
  'atleta.pontosAcumulados': 'Pontos acumulados',
  'atleta.etapas': 'Etapas',
  'atleta.overall': 'Overall',
  'atleta.posicao': 'Posição',
  'atleta.geral': 'Geral',
  'atleta.empateNaoResolvido': 'Empate não resolvido',
  'atleta.semCpf': 'CPF não disponível',
  'atleta.semFiliacao': 'Sem entidade de filiação',
  'atleta.semHistorico': 'Nenhum resultado publicado',
  'atleta.semHistoricoDescricao': 'O histórico esportivo aparece aqui quando um resultado deste atleta for publicado.',
  'atleta.semPontuacao': 'Nenhuma pontuação',
  'atleta.semPontuacaoDescricao': 'A pontuação aparece aqui depois que os lançamentos da temporada forem apurados.',
  'atleta.suspender': 'Suspender',
  'atleta.arquivar': 'Arquivar',
  'atleta.reativar': 'Reativar',
  'atleta.excluir': 'Excluir',
  'atleta.excluindo': 'Excluindo…',
  'atleta.excluirDescricao': 'A exclusão só é possível enquanto não houver histórico esportivo. Havendo, o servidor recusa e indica o arquivamento.',
  'atleta.motivo': 'Motivo',
  'atleta.motivoFicaNaAuditoria': 'O motivo fica registrado na auditoria, junto de quem mudou e quando.',
  'atleta.motivoOpcional': 'Opcional.',
  'atleta.nadaDeHistoricoMuda': 'Nenhum resultado, ponto ou inscrição é alterado por esta ação.',
  'atleta.suspensoAviso': 'Atleta suspenso.',
  'atleta.arquivadoAviso': 'Atleta arquivado.',
  'atleta.reativadoAviso': 'Atleta reativado.',
  'atleta.excluidoAviso': 'Atleta excluído.',
  'atleta.editar': 'Editar cadastro',
  'atleta.editarDescricao': 'O CPF e a equipe não mudam por aqui: um é a identidade que liga o histórico, o outro tem vínculo e transferência próprios.',
  'atleta.cadastroAtualizado': 'Cadastro atualizado.',
  'atleta.sexoMasculino': 'Masculino',
  'atleta.sexoFeminino': 'Feminino',
  'atleta.entidadeDica': 'A entidade e a matrícula são o par pelo qual o resultado oficial reconhece o atleta.',
  'atleta.verCpf': 'Ver CPF completo',
  'atleta.revelando': 'Consultando…',
  'atleta.cpfRegistradoNaAuditoria': 'Esta consulta ficou registrada na auditoria.',
};
